INSERT INTO `repositories` (`type`, `dir`, `name`, `version`, `upgrade`, `file`, `url`, `active`) VALUES
('GIT', '<InstallDir>/web/apps/ru', 'ruTorrent', '3.7', 1, 'ruTorrent_v3.7.zip', 'https://github.com/Novik/ruTorrent', 1),
('TARGZ', '<InstallDir>/web/apps/ru/plugins/chat', 'ruTorrent Plugin Chat', '2.0', 0, 'chat_v2.0.tar.gz', 'https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/rutorrent-chat/chat-2.0.tar.gz', 1),
('TARGZ', '<InstallDir>/web/apps/ru/plugins/logoff', 'ruTorrent Plugin Logoff', '1.3', 0, 'logoff_v1.3.tar.gz', 'https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/rutorrent-logoff/logoff-1.3.tar.gz', 1),
('TARGZ', '<InstallDir>/web/apps/ru/plugins/lbll-suite', 'ruTorrent Plugin LBLL-Suite', '0.8.1', 1, 'lbll-suite_v0.8.1.tar.gz', 'https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/rutorrent-tadd-labels/lbll-suite_0.8.1.tar.gz', 1),
('SVN', '<InstallDir>/web/apps/ru/plugins/nfo', 'ruTorrent Plugin NFO', '3.6', 1, 'nfo_v3.6.zip', 'https://github.com/AceP1983/ruTorrent-plugins/trunk/nfo', 1),
('SVN', '<InstallDir>/web/apps/ru/plugins/checksfv', 'ruTorrent Plugin Check SFV', '3.6', 1, 'checksfv_v3.6.zip', 'https://github.com/AceP1983/ruTorrent-plugins/trunk/checksfv', 1),
('SVN', '<InstallDir>/web/apps/ru/plugins/disklog', 'ruTorrent Plugin Disk Log', '3.6', 1, 'disklog_v3.6.zip', 'https://github.com/AceP1983/ruTorrent-plugins/trunk/disklog', 1),
('SVN', '<InstallDir>/web/apps/ru/plugins/showip', 'ruTorrent Plugin Show IP', '3.6', 1, 'showip_v3.6.zip', 'https://github.com/AceP1983/ruTorrent-plugins/trunk/showip', 0),
('SVN', '<InstallDir>/web/apps/ru/plugins/speedgraph', 'ruTorrent Plugin Speed Graph', '3.6', 1, 'speedgraph_v3.6.zip', 'https://github.com/AceP1983/ruTorrent-plugins/trunk/speedgraph', 1),
('ZIP', '<InstallDir>/web/apps/ru/plugins/filemanager', 'ruTorrent Plugin FileManager', '0.09', 1, 'filemanager_v0.09.zip', 'https://github.com/toulousain79/MySB/raw/v4.0/files/filemanager_v0.09.zip', 1),
('ZIP', '<InstallDir>/web/apps/ru/plugins/fileupload', 'ruTorrent Plugin FileUpload', '0.02', 1, 'fileupload_v0.02.zip', 'https://github.com/toulousain79/MySB/raw/v4.0/files/fileupload_v0.02.zip', 0),
('ZIP', '<InstallDir>/web/apps/ru/plugins/fileshare', 'ruTorrent Plugin FileShare', '1.0', 1, 'fileshare_v1.0.zip', 'https://github.com/toulousain79/MySB/raw/v4.0/files/fileshare_v0.03.zip', 1),
('ZIP', '<InstallDir>/web/apps/ru/plugins/mediastream', 'ruTorrent Plugin MediaStream', '0.01', 1, 'mediastream_v0.01.zip', 'https://github.com/toulousain79/MySB/raw/v4.0/files/mediastream_v0.01.zip', 1),
('GIT', '<InstallDir>/web/apps/ru/plugins/ratiocolor', 'ruTorrent Plugin RatioColor', '0.5', 0, 'ratiocolor_v0.5.zip', 'https://github.com/Gyran/rutorrent-ratiocolor', 1),
('TARGZ', '<InstallDir>/web/apps/ru/plugins/stream', 'ruTorrent Plugin Stream', '1.0', 0, 'stream_v1.0.tar.gz', 'https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/rutorrent-stream-plugin/stream.tar.gz', 1),
('ZIP', '<InstallDir>/web/apps/ru/plugins/pausewebui', 'ruTorrent Plugin Pause WebUI', '1.2', 0, 'pausewebui_v1.2.zip', 'https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/rutorrent-pausewebui/pausewebui.1.2.zip', 1),
('GIT', '<InstallDir>/web/apps/ru/plugins/mobile', 'ruTorrent Plugin Mobile', '1.0', 0, 'mobile_v1.0.zip', 'https://github.com/xombiemp/rutorrentMobile.git', 1),
('ZIP', '<InstallDir>/web/apps/ru/plugins/instantsearch', 'ruTorrent Plugin InstantSearch', '1.0', 0, 'instantsearch_v1.0.zip', 'https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/rutorrent-instantsearch/instantsearch.1.0.zip', 1),
('GIT', '<InstallDir>/web/apps/ru/plugins/linkseedboxmanager', 'ruTorrent Plugin Link Manager', '1.0', 0, 'linkseedboxmanager_v1.0.zip', 'https://github.com/Hydrog3n/linkseedboxmanager.git', 1),
('GIT', '<InstallDir>/web/apps/ru/plugins/linkcakebox', 'ruTorrent Plugin Link Cakebox', '1.0', 0, 'linkcakebox_v1.0.zip', 'https://github.com/Cakebox/linkcakebox.git', 1),
('GIT', '<InstallDir>/sources/plowshare', 'Plowshare', '2.1.6', 1, 'Plowshare_v2.1.6.zip', 'https://github.com/mcrapet/plowshare.git', 1),
('CURL', '/usr/bin/composer', 'Composer', '1.4.2', 1, 'composer.phar', 'https://getcomposer.org/download/1.4.2/composer.phar', 1),
('TARGZ', '<InstallDir>/sources/nodejs', 'NodeJS', '0.12.18', 1, 'node_v0.12.18.tar.gz', 'https://nodejs.org/dist/latest-v0.12.x/node-v0.12.18.tar.gz', 1),
('GIT', '<InstallDir>/web/apps/sm', 'Seedbox-Manager', '3.0.1', 1, 'seedbox-manager_v3.0.1.zip', 'https://github.com/Magicalex/seedbox-manager.git', 1),
('GIT', '<InstallDir>/web/apps/cb', 'Cakebox-Light', '1.8.6', 1, 'cakebox-light_v1.8.6.zip', 'https://github.com/Cakebox/Cakebox-light.git', 1),
('TARGZ', '<InstallDir>/sources/libsodium', 'Libsodium', '1.0.12', 1, 'libsodium_v1.0.12.tar.gz', 'https://download.libsodium.org/libsodium/releases/libsodium-1.0.12.tar.gz', 1),
('TARGZ', '<InstallDir>/sources/minisign', 'Minisign', '0.7.5', 0, 'minisign_v0.7.5.tar.gz', 'https://github.com/jedisct1/minisign/tarball/master', 1),
('TARGZ', '<InstallDir>/sources/dnscrypt-proxy', 'DNScrypt-proxy', '1.9.5', 1, 'dnscrypt-proxy_v1.9.5.tar.gz', 'https://download.dnscrypt.org/dnscrypt-proxy/dnscrypt-proxy-1.9.5.tar.gz', 1),
('WBM', '<InstallDir>/files', 'OpenVPNadmin Webmin', '2.6', 0, 'openvpn_v2.6.wbm', 'http://www.openit.it/downloads/OpenVPNadmin/openvpn-2.6.wbm.gz', 1),
('WBM', '<InstallDir>/files', 'Nginx Webmin Module', '0.10', 0, 'nginx_v0.10.wbm', 'https://www.justindhoffman.com/sites/justindhoffman.com/files/nginx-0.10.wbm_.gz', 1),
('TARGZ', '<InstallDir>/sources/libtorrent', 'LibTorrent', '0.13.6', 0, 'libtorrent_v0.13.6.tar.gz', 'http://rtorrent.net/downloads/libtorrent-0.13.6.tar.gz', 1),
('TARGZ', '<InstallDir>/sources/rtorrent', 'rTorrent', '0.9.6', 0, 'rtorrent_v0.9.6.tar.gz', 'http://rtorrent.net/downloads/rtorrent-0.9.6.tar.gz', 1),
('SVN', '<InstallDir>/sources/xmlrpc-c', 'XMLRPC', '1.49.0', 1, 'xmlrpc-c_v1.49.0.zip', 'http://svn.code.sf.net/p/xmlrpc-c/code/advanced/', 1),
('GIT', '<InstallDir>/web/apps/la', 'LoadAvg', '2.2', 0, 'loadavg_v2.2.zip', 'https://github.com/loadavg/loadavg.git', 1),
('ZIP', '<InstallDir>/web/apps/nc', 'NextCloud', '12.0.0', 1, 'nextcloud_v12.0.0.zip', 'https://download.nextcloud.com/server/releases/nextcloud-12.0.0.zip', 1),
('TARGZ', '<InstallDir>/sources/rkhunter', 'RKHunter', '1.4.2', 0, 'rkhunter_v1.4.2.tar.gz', 'http://downloads.sourceforge.net/project/rkhunter/rkhunter/1.4.2/rkhunter-1.4.2.tar.gz?r=&ts=1456674223&use_mirror=freefr', 1),
('TARGZ', '<InstallDir>/sources/wget', 'Wget', '1.19.1', 1, 'wget_v1.19.1.tar.gz', 'http://ftp.gnu.org/gnu/wget/wget-1.19.1.tar.gz', 1),
('TARGZ', '<InstallDir>/sources/geoipupdate', 'GeoIPupdate', '2.4.0', 1, 'GeoIPupdate_v2.4.0.tar.gz', 'https://github.com/maxmind/geoipupdate/releases/download/v2.4.0/geoipupdate-2.4.0.tar.gz', 1),
('ZIP', '<InstallDir>/web/wolf', 'Wolf CMS', '0.8.3.1', 1, 'wolf_v0.8.3.1.zip', 'https://github.com/toulousain79/MySB/raw/v4.0/files/wolf_v0.8.3.1.zip', 1),
('GIT', '/opt/plexpy', 'PlexPy', '1.4.20', 1, 'PlexPy_v1.4.20.zip', 'https://github.com/JonnyWong16/plexpy.git', 1);
