INSERT INTO `repositories` (`id_repositories`, `type`, `dir`, `name`, `version`, `file`, `upgrade`, `url`, `active`) VALUES
(1, 'GIT', '/web/apps/ru', 'ruTorrent', '3.7', 'ruTorrent_v3.7.zip', '1', 'https://github.com/Novik/ruTorrent.git', 1),
(2, 'TARGZ', '/web/apps/ru/plugins/chat', 'ruTorrent Plugin Chat', '2.0', 'chat_v2.0.tar.gz', '0', 'https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/rutorrent-chat/chat-2.0.tar.gz', 1),
(3, 'TARGZ', '/web/apps/ru/plugins/logoff', 'ruTorrent Plugin Logoff', '1.3', 'logoff_v1.3.tar.gz', '0', 'https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/rutorrent-logoff/logoff-1.3.tar.gz', 1),
(4, 'TARGZ', '/web/apps/ru/plugins/lbll-suite', 'ruTorrent Plugin tAdd-Labels', '0.8.1', 'lbll-suite_v0.8.1.tar.gz', '1', 'https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/rutorrent-tadd-labels/lbll-suite_0.8.1.tar.gz', 1),
(5, 'SVN', '/web/apps/ru/plugins/nfo', 'ruTorrent Plugin NFO', '3.6', 'nfo_v3.6.zip', '1', 'https://github.com/AceP1983/ruTorrent-plugins/trunk/nfo', 1),
(6, 'SVN', '/web/apps/ru/plugins/checksfv', 'ruTorrent Plugin Check SFV', '3.6', 'checksfv_v3.6.zip', '1', 'https://github.com/AceP1983/ruTorrent-plugins/trunk/checksfv', 1),
(7, 'SVN', '/web/apps/ru/plugins/disklog', 'ruTorrent Plugin Disk Log', '3.6', 'disklog_v3.6.zip', '1', 'https://github.com/AceP1983/ruTorrent-plugins/trunk/disklog', 1),
(8, 'SVN', '/web/apps/ru/plugins/showip', 'ruTorrent Plugin Show IP', '3.6', 'showip_v3.6.zip', '1', 'https://github.com/AceP1983/ruTorrent-plugins/trunk/showip', 1),
(9, 'SVN', '/web/apps/ru/plugins/speedgraph', 'ruTorrent Plugin Speed Graph', '3.6', 'speedgraph_v3.6.zip', '1', 'https://github.com/AceP1983/ruTorrent-plugins/trunk/speedgraph', 1),
(10, 'ZIP', '/web/apps/ru/plugins/filemanager', 'ruTorrent Plugin FileManager', '0.09', 'filemanager_v0.09.zip', '1', 'https://github.com/toulousain79/MySB/raw/v3.5/files/filemanager_v0.09.zip', 1),
(11, 'ZIP', '/web/apps/ru/plugins/fileupload', 'ruTorrent Plugin FileUpload', '0.02', 'fileupload_v0.02.zip', '1', 'https://github.com/toulousain79/MySB/raw/v3.5/files/fileupload_v0.02.zip', 0),
(12, 'ZIP', '/web/apps/ru/plugins/fileshare', 'ruTorrent Plugin FileShare', '1.0', 'fileshare_v1.0.zip', '1', 'https://github.com/toulousain79/MySB/raw/v3.5/files/fileshare_v0.03.zip', 1),
(13, 'ZIP', '/web/apps/ru/plugins/mediastream', 'ruTorrent Plugin MediaStream', '0.01', 'mediastream_v0.01.zip', '1', 'https://github.com/toulousain79/MySB/raw/v3.5/files/mediastream_v0.01.zip', 1),
(14, 'GIT', '/web/apps/ru/plugins/ratiocolor', 'ruTorrent Plugin RatioColor', '0.5', 'ratiocolor_v0.5.zip', '0', 'https://github.com/Gyran/rutorrent-ratiocolor', 1),
(15, 'TARGZ', '/web/apps/ru/plugins/stream', 'ruTorrent Plugin Stream', '1.0', 'stream_v1.0.tar.gz', '0', 'https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/rutorrent-stream-plugin/stream.tar.gz', 1),
(16, 'ZIP', '/web/apps/ru/plugins/pausewebui', 'ruTorrent Plugin Pause WebUI', '1.2', 'pausewebui_v1.2.zip', '0', 'https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/rutorrent-pausewebui/pausewebui.1.2.zip', 1),
(17, 'GIT', '/web/apps/ru/plugins/mobile', 'ruTorrent Plugin Mobile', '1.0', 'mobile_v1.0.zip', '0', 'https://github.com/xombiemp/rutorrentMobile.git', 1),
(18, 'GIT', '/web/apps/ru/plugins/linkseedboxmanager', 'ruTorrent Plugin Link Manager', '1.0', 'linkseedboxmanager_v1.0.zip', '0', 'https://github.com/Hydrog3n/linkseedboxmanager.git', 1),
(19, 'GIT', '/web/apps/ru/plugins/linkcakebox', 'ruTorrent Plugin Link Cakebox', '1.0', 'linkcakebox_v1.0.zip', '0', 'https://github.com/Cakebox/linkcakebox.git', 1),
(20, 'GIT', '/sources/plowshare', 'Plowshare', '2.1.6', 'Plowshare_v2.1.6.zip', '1', 'https://github.com/mcrapet/plowshare.git', 1),
(21, 'CURL', '/usr/bin/composer', 'Composer', '1.2.4', 'composer.phar', '1', 'https://getcomposer.org/installer', 1),
(22, 'TARGZ', '/sources/nodejs', 'NodeJS', '0.12.17', 'node_v0.12.17.tar.gz', '1', 'https://nodejs.org/dist/v0.12.17/node-v0.12.17.tar.gz', 1),
(23, 'GIT', '/web/apps/sm', 'Seedbox-Manager', '2.5.0', 'seedbox-manager_v2.5.0.zip', '1', 'https://github.com/Magicalex/seedbox-manager.git', 1),
(24, 'GIT', '/web/apps/cb', 'Cakebox-Light', '1.8.6', 'cakebox-light_v1.8.6.zip', '1', 'https://github.com/Cakebox/Cakebox-light.git', 1),
(25, 'TARGZ', '/sources/libsodium', 'Libsodium', '1.0.11', 'libsodium_v1.0.11.tar.gz', '0', 'https://download.libsodium.org/libsodium/releases/libsodium-1.0.11.tar.gz', 1),
(26, 'TARGZ', '/sources/dnscrypt-proxy', 'DNScrypt-proxy', '1.7.0', 'dnscrypt-proxy_v1.7.0.tar.gz', '1', 'https://download.dnscrypt.org/dnscrypt-proxy/dnscrypt-proxy-1.7.0.tar.gz', 1),
(27, 'WBM', '/files', 'OpenVPNadmin WebMin', '2.6', 'openvpn_v2.6.wbm', '0', 'http://www.openit.it/downloads/OpenVPNadmin/openvpn-2.6.wbm.gz', 1),
(28, 'WBM', '/files', 'Nginx Webmin Module', '0.10', 'nginx_v0.10.wbm', '0', 'https://www.justindhoffman.com/sites/justindhoffman.com/files/nginx-0.10.wbm_.gz', 1),
(29, 'TARGZ', '/sources/libtorrent', 'LibTorrent', '0.13.6', 'libtorrent_v0.13.6.tar.gz', '0', 'http://rtorrent.net/downloads/libtorrent-0.13.6.tar.gz', 1),
(30, 'TARGZ', '/sources/rtorrent', 'rTorrent', '0.9.6', 'rtorrent_v0.9.6.tar.gz', '0', 'http://rtorrent.net/downloads/rtorrent-0.9.6.tar.gz', 1),
(31, 'SVN', '/sources/xmlrpc-c', 'XMLRPC', '1.43.03', 'xmlrpc-c_v1.43.03.zip', '1', 'http://svn.code.sf.net/p/xmlrpc-c/code/stable', 1),
(32, 'TARGZ', '/web/apps/la', 'LoadAvg', '2.2', 'loadavg_v2.2.tar.gz', '0', 'http://www.loadavg.com/files/loadavg.tar.gz', 1),
(33, 'ZIP', '/web/apps/oc', 'ownCloud', '9.1.3', 'owncloud_v9.1.3.zip', '1', 'https://download.owncloud.org/community/owncloud-9.1.3.zip', 1),
(34, 'GIT', '/usr/local/src/letsencrypt', 'Lets Encrypt', '0.9.2', 'LetsEncrypt_v0.9.2.zip', '0', 'https://github.com/certbot/certbot', 1),
(35, 'TARGZ', '/sources/rkhunter', 'RKHunter', '1.4.2', 'rkhunter_v1.4.2.tar.gz', '0', 'http://downloads.sourceforge.net/project/rkhunter/rkhunter/1.4.2/rkhunter-1.4.2.tar.gz?r=&ts=1456674223&use_mirror=freefr', 1),
(36, 'TARGZ', '/sources/wget', 'Wget', '1.18', 'wget_v1.18.tar.gz', '0', 'http://ftp.gnu.org/gnu/wget/wget-1.18.tar.gz', 1);
