#!/bin/bash
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#	_\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#	 _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#	  _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#	   _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#		_\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#		 _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#		  _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
######################################################################
{ [[ -z "${vars}" ]] || [[ "${vars}" -ne 1 ]]; } && {
    echo "Please load 'vars' file before..."
    exit 0
}
##################### FIRST LINE #####################################

# Display/log functions
function fnLogging() {
    gbDisplay=${gbDisplay:-0}
    gbLogging=${gbLogging:-0}
    if [[ -n ${gsLogFile} ]] && [[ -f ${gsLogFile} ]]; then
        gbLogging=1
    fi
}
# A title string prefixed by a header
# Usage: stitle <TITLE> ...
function stitle() {
    local D
    if [[ -n $* ]]; then
        D="$(date "+%Y%m%d-%H%M%S")"
        fnLogging
        [[ ${gbDisplay} -eq 1 ]] && echo -e " -  $*"
        [[ ${gbLogging} -eq 1 ]] && echo -e "${D} -  $*" >>"${gsLogFile}"
    fi
}

# A title string prefixed by a header
# Usage: stitle <TITLE> ...
function ssubtitle() {
    local D
    if [[ -n $* ]]; then
        D="$(date "+%Y%m%d-%H%M%S")"
        fnLogging
        [[ ${gbDisplay} -eq 1 ]] && echo -e " -    > ${CYAN}$*${CEND}"
        [[ ${gbLogging} -eq 1 ]] && echo -e "${D} -    > $*" >>"${gsLogFile}"
    fi
}

# A simple message string prefixed by a header
# Usage: smessage <HEADER> ...
function smessage() {
    local D
    if [[ -n $* ]]; then
        D="$(date "+%Y%m%d-%H%M%S")"
        fnLogging
        [[ ${gbDisplay} -eq 1 ]] && echo -e " -   - $*"
        [[ ${gbLogging} -eq 1 ]] && echo -e "${D} -   - $*" >>"${gsLogFile}"
    fi
}

# A OK message string prefixed by a header
# Usage: smessage <HEADER> ...

function smessage_ok() {
    local D
    if [[ -n $* ]]; then
        D="$(date "+%Y%m%d-%H%M%S")"
        fnLogging
        [[ ${gbDisplay} -eq 1 ]] && echo -e " -       ${GREEN}[+]${CEND}  $*"
        [[ ${gbLogging} -eq 1 ]] && echo -e "${D} -       [+]  $*" >>"${gsLogFile}"
    fi
}

# A NOT OK message string prefixed by a header
# Usage: smessage <HEADER> ...

function smessage_nok() {
    local D
    if [[ -n $* ]]; then
        D="$(date "+%Y%m%d-%H%M%S")"
        fnLogging
        [[ ${gbDisplay} -eq 1 ]] && echo -e " -       ${YELLOW}[-]${CEND}  $*"
        [[ ${gbLogging} -eq 1 ]] && echo -e "${D} -       [-]  $*" >>"${gsLogFile}"
    fi
}

# A NOT OK message string prefixed by a header
# Usage: smessage <HEADER> ...

function smessage_ko() {
    local D
    if [[ -n $* ]]; then
        D="$(date "+%Y%m%d-%H%M%S")"
        fnLogging
        [[ ${gbDisplay} -eq 1 ]] && echo -e " -       ${RED}[-]${CEND}  $*"
        [[ ${gbLogging} -eq 1 ]] && echo -e "${D} -       [-]  $*" >>"${gsLogFile}"
    fi
}

# A NOT OK message string prefixed by a header
# Usage: smessage <HEADER> ...

function smessage_infos() {
    local D
    if [[ -n $* ]]; then
        D="$(date "+%Y%m%d-%H%M%S")"
        fnLogging
        [[ ${gbDisplay} -eq 1 ]] && echo -e " -       ${LGRAY}[*]${CEND}  $*"
        [[ ${gbLogging} -eq 1 ]] && echo -e "${D} -       [*]  $*" >>"${gsLogFile}"
    fi
}

# Stdout lines prefixed by a header
# usage: <STDOUT> | smultiheaders
function smultiheaders() {
    local D
    if [[ -n $* ]]; then
        D="$(date "+%Y-%m-%d %H:%M:%S")"
        fnLogging
        while IFS= read -r STDOUT; do
            [[ ${gbDisplay} -eq 1 ]] && echo -e " -     | ${STDOUT}"
            [[ ${gbLogging} -eq 1 ]] && echo -e "${D} -     | ${STDOUT}" >>"${gsLogFile}"
        done
    fi
}
