#!/bin/bash
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### ownCloud
Func_ownCloud_DB() {
	Type="$1"
	Tables="$2"
	Columns="$3"
	Values="$3"
	MySQL_MysbPassword="`cat $MySB_InstallDir/files/MySQL_MysbPassword`"

	case "$Type" in
		"CreateUser")
			User="$2"
			Mail="$3"
			Lang="$4"
			TimeStamp=$(date +%s)

			/usr/bin/mysql -u MySB_user -p$MySQL_MysbPassword ownCloud_db <<-EOF
			INSERT INTO oc_preferences (userid, appid, configkey, configvalue) VALUES('admin', 'files_external', '/Home_$User', '$TimeStamp');
			INSERT INTO oc_preferences (userid, appid, configkey, configvalue) VALUES('$User', 'core', 'lang', '$Lang');
			INSERT INTO oc_preferences (userid, appid, configkey, configvalue) VALUES('$User', 'settings', 'email', '$Mail');
			INSERT INTO oc_storages (id) VALUES('local::/home/$User/');
			EOF
		;;
		"DeleteUser")
			User="$2"

			/usr/bin/mysql -u MySB_user -p$MySQL_MysbPassword ownCloud_db <<-EOF
			DELETE FROM oc_storages WHERE id = 'local::/home/$User';
			DELETE FROM oc_preferences WHERE configkey = '/Home_$User';
			EOF
		;;
		"INSERT")
			/usr/bin/mysql -u MySB_user -p$MySQL_MysbPassword ownCloud_db -e "INSERT INTO $Tables ($Columns) VALUES ($Values)";
		;;
	esac
}

##################### LAST LINE ######################################
