#!/bin/bash 
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___        
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_       
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_      
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__     
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_    
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_   
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_  
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__ 
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### 1 - includes
source /etc/MySB/inc/vars
source /etc/MySB/inc/funcs

#### 2 - cleaning
case "$SCRIPT_name" in
	"MySB_Install.sh")
		#if [ "`screen -ls | grep MySB`" == "" ]; then
			# delete MySB_Install.sh script downloaded by hand
			if [ "$(pwd)/$(basename $0)" != "/etc/MySB/MySB_Install.sh" ]; then
				rm $0
			fi
		#fi
	;;
	"MySB_CreateUser")
		if [ "`screen -ls | grep MySB`" != "" ]; then
			#### 4 - Create MySB banner
			if [ "$BANNER" == "ON" ]; then
				BannerGenerator
			fi

			if [ -f /etc/MySB/infos/password.info ]; then
				rm -f /etc/MySB/infos/password.info
			fi
			if [ -f /etc/MySB/infos/newuser.info ]; then
				rm -f /etc/MySB/infos/newuser.info
			fi
			if [ -f /etc/MySB/infos/myip.info ]; then
				rm -f /etc/MySB/infos/myip.info
			fi
			if [ -f /etc/MySB/infos/smtp_pass.info ]; then
				rm -f /etc/MySB/infos/smtp_pass.info
			fi				
		fi
	;;
esac

#### 4 - stop/start/restart services
case "$SCRIPT_name" in
	"FirewallAndSecurity.sh")
	if [ "`ps ax | grep 'FirewallAndSecurity.sh' | grep 'clean' | sed '/grep/d'`" != "" ]; then
		echo &> /dev/null
	else
		ManageServices start
	fi
	;;
	*)
		ManageServices start	
	;;
esac

#### 3 - Save Iptables
sudo iptables-save > /etc/iptables.up.rules
cp /etc/iptables.up.rules /etc/MySB/files/current-iptables-rules
if [ -d /etc/webmin/firewall/ ]; then
	cp /etc/iptables.up.rules /etc/webmin/firewall/iptables.save
fi

#### 5 - create ccze files (HTML)
if [ "$LOGSTD" != "NO" ] ; then
	if [ -f /etc/MySB/logs/$SCRIPT_name.err ] && [ -d /etc/MySB/web/logs/install/ ]; then
		echo "--------------------" >> /etc/MySB/logs/$SCRIPT_name.err
		echo "END: "`date` "-" $SCRIPT_name >> /etc/MySB/logs/$SCRIPT_name.err
		echo "--------------------" >> /etc/MySB/logs/$SCRIPT_name.err
		sudo ccze -h < /etc/MySB/logs/$SCRIPT_name.err > /etc/MySB/web/logs/install/$SCRIPT_name-errors.html
	fi
	if [ -f /etc/MySB/logs/$SCRIPT_name.log ] && [ -d /etc/MySB/web/logs/ ]; then
		echo "--------------------" >> /etc/MySB/logs/$SCRIPT_name.log
		echo "END: "`date` "-" $SCRIPT_name >> /etc/MySB/logs/$SCRIPT_name.log
		echo "--------------------" >> /etc/MySB/logs/$SCRIPT_name.log
		sudo ccze -h < /etc/MySB/logs/$SCRIPT_name.log > /etc/MySB/web/logs/install/$SCRIPT_name-log.html
	fi
	if [ -d /etc/MySB/web/logs/ ]; then
		if [ ! "`ls /etc/MySB/logs/ | grep .html`" = "" ]; then
			mv /etc/MySB/logs/*.html /etc/MySB/web/logs/install/
		fi
	fi
fi

#### Reboot after install
if [ "$REBOOT" == "YES" ]; then
	reboot	
fi

##################### LAST LINE ######################################