#!/bin/bash 
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### 1 - includes
source /etc/MySB/inc/vars
source /etc/MySB/inc/funcs
source /lib/lsb/init-functions

#### 2 - Check services again
if [ "$IsInstalled_PlexMedia" == "YES" ]; then IsInstalled_PlexMedia="`CheckCommand 1 plexmediaserver`"; fi
if [ "$IsInstalled_Webmin" == "YES" ]; then IsInstalled_Webmin="`CheckCommand 1 webmin`"; fi
if [ "$IsInstalled_OpenVPN" == "YES" ]; then IsInstalled_OpenVPN="`CheckCommand 1 openvpn`"; fi
if [ "$IsInstalled_Samba" == "YES" ]; then IsInstalled_Samba="`CheckCommand 1 smbd`"; fi
if [ "$IsInstalled_NFS" == "YES" ]; then IsInstalled_NFS="`CheckCommand 1 nfs-kernel-server`"; fi
if [ "$IsInstalled_LogWatch" == "YES" ]; then IsInstalled_LogWatch="`CheckCommand 1 logwatch`"; fi
if [ "$IsInstalled_Fail2Ban" == "YES" ]; then IsInstalled_Fail2Ban="`CheckCommand 1 fail2ban`"; fi
if [ "$IsInstalled_PeerGuardian" == "YES" ]; then IsInstalled_PeerGuardian="`CheckCommand 1 pgld`"; fi
if [ "$IsInstalled_DNScrypt" == "YES" ]; then IsInstalled_DNScrypt="`CheckCommand 1 dnscrypt-proxy`"; fi

#### 3 - SWITCHES
# Default
BANNER=ON		# Banner for all script (ON/OFF)
LOGSTD=NO		# Standard Outpout and Error redicted to 'scriptname.log' (STDOUT/NO)
USAGE=ON		# All usage display to user, like questions (ON/OFF)
END=ON			# Launch some commands at the end (ldconfig, updatedb, drop cache) (see includes_after) (ON/OFF)
TIMESTAMP=ON	# Adds a time stamp at the beginning and end of the script in the logs (ON/OFF)

# Check by script name BEFORE check arguments (to force default switches)
case "$ScriptName" in
	"DynamicAddressResolver.bsh")
		BANNER=OFF
		LOGSTD=NO
		USAGE=OFF
		END=OFF
		TIMESTAMP=OFF
	;;	
	"ApplyConfig.bsh") # Launched by ApplyConfig.bsh (web)
		BANNER=OFF
		END=OFF
		TIMESTAMP=OFF
	;;
	"MySB_SecurityRules")
		TIMESTAMP=OFF
		END=OFF
	;;	
esac

# Check by arguments
for Arg in "$@"; do
	case "$Arg" in
		"REFRESH"|"INSTALL")
			BANNER=OFF
			LOGSTD=STDOUT
			USAGE=OFF
			END=ON
			TIMESTAMP=ON
		;;
		"UPGRADE"|"CRON"|"APPLYCONFIG"|"INIT")
			BANNER=OFF
			LOGSTD=STDOUT
			USAGE=OFF
			END=OFF
			TIMESTAMP=ON
		;;
	esac
done

# Check by script name AFTER check arguments (to force any switches)
case "$ScriptName" in
	"MySB.bsh") # Upgrade ?
		BANNER=ON
		LOGSTD=NO
		USAGE=ON
		END=OFF
		TIMESTAMP=OFF
		sleep 10
	;;
	"Questions")
		BANNER=ON
		LOGSTD=NO
		USAGE=ON
		END=OFF
		TIMESTAMP=OFF
	;;
	"MySB_GitHubRepoUpdate")
		TIMESTAMP=OFF
		END=OFF
	;;	
	"MySB_Install.bsh")
		TIMESTAMP=ON
		END=OFF
	;;
	"From_v1.1-to-dev.bsh") # Upgrade ?
		MySB_CurrentVersion="dev"
		TIMESTAMP=OFF
		END=OFF
		sleep 10
	;;		
esac

#### 4 - Create MySB banner
if [ "$BANNER" == "ON" ]; then
	BannerGenerator
fi

#### 5 -STD Out/Err (after banner)
if [ "$TIMESTAMP" == "ON" ]; then
	echo "------------------------------------------------------------" >> /etc/MySB/logs/$ScriptName.log
	echo "START Out/Err: "`date` "-" $ScriptName $@ >> /etc/MySB/logs/$ScriptName.log
	echo "------------------------------------------------------------" >> /etc/MySB/logs/$ScriptName.log
fi
if [ "$LOGSTD" == "STDOUT" ]; then
	exec >> /etc/MySB/logs/$ScriptName.log	2>&1
fi

##################### LAST LINE ######################################