#!/bin/bash 
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___        
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_       
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_      
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__     
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_    
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_   
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_  
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__ 
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################
#
# If you want add files in next vars. Thanks to add it as follow.
# - TYPE_	(GIT, SVN, TAR, WBM, ...) in UPPERCASE
# - dir_ (ruttorrent, libtorrent, ...) in LOWERCASE
# - suddir_ (plugins, ...) in LOWERCASE
# - FILE
# Result:	TYPE_dir_suddir_FILE
# Example:	SVN_rutorrent_plugins_CHAT
#			SVN_ 		(will use svn download it)
#			rutorrent_	(will create 'rutorrent' dir)
#			plugins_ 	(will be create 'plugins' subdir)
#			CHAT		(use destination file for TAR or WBM)
#
##################### FIRST LINE #####################################

#### rTorrent / ruTorrent / XmlRpc-C
# xmlrpc-c
SVN_xmlrpc="http://svn.code.sf.net/p/xmlrpc-c/code/advanced"
# libtorrent
GIT_libtorrent="git://github.com/rakshasa/libtorrent.git"
# rTorrent
GIT_rtorrent="git://github.com/rakshasa/rtorrent.git"
# ruTorrent
SVN_rutorrent="http://rutorrent.googlecode.com/svn/trunk/rutorrent"
# ruTorrent Official Plugins
SVN_rutorrent_plugins="http://rutorrent.googlecode.com/svn/trunk/plugins"

#### - ruTorrent Plugins
# Chat
SVN_rutorrent_plugins_CHAT="http://rutorrent-chat.googlecode.com/svn/trunk/"
# Logoff
SVN_rutorrent_plugins_LOGOFF="http://rutorrent-logoff.googlecode.com/svn/trunk/"
# tAdd-Labels
TARGZ_rutorrent_plugins_TADDLABELS="https://rutorrent-tadd-labels.googlecode.com/files/lbll-suite_0.8.1.tar.gz"
# Filemanager
SVN_rutorrent_plugins_FILEMANAGER="http://svn.rutorrent.org/svn/filemanager/trunk/filemanager"
# Theme
SVN_rutorrent_plugins_THEME="http://rutorrent.googlecode.com/svn/trunk/plugins/theme"
# NFO
TARGZ_rutorrent_plugins_NFO="http://srious.biz/nfo.tar.gz"
# RatioColor
GIT_rutorrent_plugins_RATIOCOLOR="https://github.com/Gyran/rutorrent-ratiocolor"
# FileUpload
SVN_rutorrent_plugins_FILEUPLOAD="http://svn.rutorrent.org/svn/filemanager/trunk/fileupload"
# Fileshare
SVN_rutorrent_plugins_FILESHARE="http://svn.rutorrent.org/svn/filemanager/trunk/fileshare"
# Stream
TARGZ_rutorrent_plugins_STREAM="https://rutorrent-stream-plugin.googlecode.com/files/stream.tar.gz"
# MediaStream
SVN_rutorrent_plugins_MEDIASTREAM="http://svn.rutorrent.org/svn/filemanager/trunk/mediastream"
# PlowShare4
GIT_plowshare="https://code.google.com/p/plowshare/"

#### Seedbox-Manager
CURL_composer="http://getcomposer.org/installer"
TARGZ_nodejs="http://nodejs.org/dist/node-latest.tar.gz"
GIT_manager="https://github.com/Magicalex/seedbox-manager.git"
GIT_rutorrent_plugins_MANAGER="https://github.com/Hydrog3n/linkseedboxmanager.git"

#### CakeBox Light
GIT_cakebox="https://github.com/Cakebox/Cakebox-light.git"
GIT_rutorrent_plugins_CAKEBOX="https://github.com/Cakebox/linkcakebox.git"

#### Webmin Modules
# OpenVPN
WBM_webmin_openvpn="http://www.openit.it/downloads/OpenVPNadmin/openvpn-2.6.wbm.gz"
# NginX
WBM_webmin_nginx="http://www.justindhoffman.com/sites/justindhoffman.com/files/nginx-0.08.wbm__0.gz"
# miniDLNA
WBM_webmin_dlna="http://downloads.sourceforge.net/project/minidlnawebmin/Webmin%20alpha1.12%20svn26/minidlnawebmin_alpha1_12.wbm?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fminidlnawebmin%2Ffiles%2FWebmin%2520alpha1.12%2520svn26%2F&ts=1402185772&use_mirror=freefr"

##################### LAST LINE ######################################