#!/bin/bash 
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___        
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_       
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_      
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__     
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_    
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_   
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_  
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__ 
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### Colors
CSI="\033["
CEND="${CSI}0m"
CBLACK="${CSI}0;30m"
CRED="${CSI}1;31m"
CGREEN="${CSI}1;32m"
CYELLOW="${CSI}1;33m"
CBLUE="${CSI}1;34m"

#### System
HOSTNAME=$(hostname)
DOMAINNAME=$(hostname -d)
SCRIPT_name=`basename $0`
PROCESSOR=`cat /proc/cpuinfo | grep processor | wc -l`
MEMORY=`free -m | grep Mem | awk '{ print $2 }'`
DEBIAN_VERSION=`lsb_release -cs`
IFPVEKERNEL=`uname -r | grep pve`
FILESYSTEMTYPE=`df -T "/home/" | awk '{print $2}' | tail -n1`

if [ -z $DOMAINNAME ]; then
	HOSTNAME="$HOSTNAME"
else
	if [ "$HOSTname" == "$DOMAINNAME" ]; then
		HOSTNAME="$HOSTNAME"
	else
		echo $HOSTNAME | grep "$DOMAINNAME" &> /dev/null
		if [ $? -eq 0 ];then
			HOSTNAME="$HOSTNAME"
		else
			HOSTNAME="$HOSTNAME"."$DOMAINNAME"
		fi
	fi
fi

#### All Variables

# ----- Main user info
if [ -f /etc/MySB/infos/email.info ]; then
	EMAILUSER=`cat /etc/MySB/infos/email.info`
fi
if [ -f /etc/MySB/infos/mainuser.info ]; then
	MAINUSER=`cat /etc/MySB/infos/mainuser.info`
fi
if [ -f /etc/MySB/infos/certpass.info ]; then
	CERTPASS=`cat /etc/MySB/infos/certpass.info`
else
	if hash mkpasswd 2>/dev/null; then
		mkpasswd $HOSTFQDN > /etc/MySB/infos/certpass.info
	fi
fi
# ----- Main user info

if [ -f /etc/MySB/infos/timezone.info ]; then
	TIMEZONE=`cat /etc/MySB/infos/timezone.info`
fi
if [ -f /etc/MySB/infos/primaryinet.info ]; then
	PRIMARYINET=`cat /etc/MySB/infos/primaryinet.info`
else
	PRIMARYINET=`ip route get 8.8.8.8 | grep 8.8.8.8 | awk '{ print $5 }'`
fi
if [ -f /etc/MySB/infos/version.info ]; then
	MYSBCURRENTVERSION=`cat /etc/MySB/infos/version.info`
fi
if [ -f /etc/MySB/infos/blocklist.info ]; then
	MYBLOCKLIST=`cat /etc/MySB/infos/blocklist.info`
fi
if [ -f /etc/MySB/infos/hostfqdn.info ]; then
	HOSTFQDN=`cat /etc/MySB/infos/hostfqdn.info`
else
	HOSTFQDN=`hostname -f`
fi
if [ -f /etc/MySB/infos/ipaddress.info ]; then
	IPADDRESS=`cat /etc/MySB/infos/ipaddress.info`
else
	IPADDRESS=$(wget -qO- ipv4.icanhazip.com)
	if [ -z $IPADDRESS ]; then
		IPADDRESS=`ifconfig | sed -n 's/.*inet addr:\([0-9.]\+\)\s.*/\1/p' | grep -v 127 | head -n 1`
		if [ -z $IPADDRESS ]; then
			IPADDRESS=`ifconfig | sed -n 's/.*inet adr:\([0-9.]\+\)\s.*/\1/p' | grep -v 127 | head -n 1`
		fi	
	fi
fi
if [ -f /etc/MySB/infos/port_http.info ]; then
	NGINXHTTPPORT=`cat /etc/MySB/infos/port_http.info`
fi
if [ -f /etc/MySB/infos/port_https.info ]; then
	NGINXHTTPSPORT=`cat /etc/MySB/infos/port_https.info`
fi
if [ -f /etc/MySB/infos/port_ssh.info ]; then
	NEWSSHPORT=`cat /etc/MySB/infos/port_ssh.info`
fi
if [ -f /etc/MySB/infos/port_cakebox.info ]; then
	CAKEBOXPORT=`cat /etc/MySB/infos/port_cakebox.info`
fi
if [ -f /etc/MySB/infos/port_ftp.info ]; then
	NEWFTPPORT=`cat /etc/MySB/infos/port_ftp.info`
	FTP_PASSIVE=""
	if [ -e '/etc/vsftpd.conf' ]; then
		MIN_PORT=$(grep "^pasv_min_port=" '/etc/vsftpd.conf' | cut --delimiter="=" --fields=2)
		MAX_PORT=$(grep "^pasv_max_port=" '/etc/vsftpd.conf' | cut --delimiter="=" --fields=2)
		if [ -n "${MIN_PORT}" -a -n "${MAX_PORT}" ]; then
			FTP_PASSIVE="${MIN_PORT}:${MAX_PORT}"
		fi
	fi	
fi
if [ -f /etc/MySB/infos/port_ftpdata.info ]; then
	NEWFTPDATAPORT=`cat /etc/MySB/infos/port_ftpdata.info`
fi
if [ -f /etc/MySB/infos/port_webmin.info ]; then
	WEBMINPORT=`cat /etc/MySB/infos/port_webmin.info`
fi
if [ -f /etc/MySB/infos/port_openvpn.info ]; then
	OPENVPNPORT=`cat /etc/MySB/infos/port_openvpn.info`
fi
if [ -f /etc/MySB/infos/proto_openvpn.info ]; then
	OPENVPNPROTO=`cat /etc/MySB/infos/proto_openvpn.info`
	OPENVPNPROTO=`echo $OPENVPNPROTO | tr '[:upper:]' '[:lower:]'`
fi
if [ -f /etc/MySB/infos/install_cakebox.info ]; then
	INSTALLCAKEBOX=`cat /etc/MySB/infos/install_cakebox.info`
fi
if [ -f /etc/MySB/infos/install_manager.info ]; then
	INSTALLMANAGER=`cat /etc/MySB/infos/install_manager.info`
fi
if [ -f /etc/MySB/infos/install_fail2ban.info ]; then
	INSTALLFAIL2BAN=`cat /etc/MySB/infos/install_fail2ban.info`
fi
if [ -f /etc/MySB/infos/install_logwatch.info ]; then
	INSTALLLOGWATCH=`cat /etc/MySB/infos/install_logwatch.info`
fi
if [ -f /etc/MySB/infos/install_plexmedia.info ]; then
	INSTALLPLEXMEDIA=`cat /etc/MySB/infos/install_plexmedia.info`
fi
if [ -f /etc/MySB/infos/install_webmin.info ]; then
	INSTALLWEBMIN=`cat /etc/MySB/infos/install_webmin.info`
fi
if [ -f /etc/MySB/infos/install_openvpn.info ]; then
	INSTALLOPENVPN=`cat /etc/MySB/infos/install_openvpn.info`
fi
if [ -f /etc/MySB/infos/install_dnscrypt.info ]; then
	INSTALLDNSCRYPT=`cat /etc/MySB/infos/install_dnscrypt.info`
fi
if [ -f /etc/MySB/infos/MySB_password.info ]; then
	MYSBUSER=`cat /etc/MySB/infos/MySB_password.info | grep user | awk '{ print $2 }'`
	MYSBPASSD=`cat /etc/MySB/infos/MySB_password.info | grep pass | awk '{ print $2 }'`
fi
if [ -f /etc/MySB/infos/smtp.info ]; then
	SMTP=`cat /etc/MySB/infos/smtp.info`
fi
if [ -f /etc/MySB/infos/smtp_port.info ]; then
	SMTP_PORT=`cat /etc/MySB/infos/smtp_port.info`
fi
if [ -f /etc/MySB/infos/smtp_host.info ]; then
	SMTP_HOST=`cat /etc/MySB/infos/smtp_host.info`
fi
if [ -f /etc/MySB/infos/smtp_security.info ]; then
	SMTP_SECURITY=`cat /etc/MySB/infos/smtp_security.info`
fi

# ----- Renting infos
if [ -f /etc/MySB/inc/renting ]; then
	source /etc/MySB/inc/renting
fi
# ----- Renting infos

# ----- Tempory, used for the first install
if [ -f /etc/MySB/infos/newuser.info ]; then
	NEWUSER=`cat /etc/MySB/infos/newuser.info`
	UPPERNEWUSER=`echo $NEWUSER | tr '[:lower:]' '[:upper:]'`
fi
if [ -f /etc/MySB/infos/password.info ]; then
	PASSWORD=`cat /etc/MySB/infos/password.info`
fi
if [ -f /etc/MySB/infos/myip.info ]; then
	MYIP=`cat /etc/MySB/infos/myip.info`
fi
if [ -f /etc/MySB/infos/smtp_pass.info ]; then
	SMTP_PASS=`cat /etc/MySB/infos/smtp_pass.info`
fi
if [ -f /etc/MySB/infos/smtp_user.info ]; then
	SMTP_USER=`cat /etc/MySB/infos/smtp_user.info`
fi
# ----- Tempory, used for the first install

#### White IP addresses
Fail2banWhiteList="127.0.0.1/32"
VpnIPs="10.0.0.0/24 10.0.1.0/24"

#### Networks ports (Services ports)
PLEXMEDIA_TCP_PORTS="32400 32469"
PLEXMEDIA_UDP_PORTS="1900 5353 2410 32412 32413 32414"

#### Networks ports (Permanently opened ports)
WHITE_TCP_IN=""
WHITE_UDP_IN=""
WHITE_TCP_OUT="80 443"
WHITE_UDP_OUT=""

##################### LAST LINE ######################################