#!/bin/bash 
# ----------------------------------
source /etc/MySB/inc/includes_before.bsh
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___        
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_       
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_      
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__     
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_    
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_   
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_  
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__ 
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#http://www.guillaume-leduc.fr/creer-un-serveur-upnp-en-10-min-avec-minidlna.html
#http://homeserver-diy.net/wiki/index.php?title=Installer_et_configurer_MiniDLNA_sous_Debian_Squeeze

#### install
PackagesManage install "minidlna"

#### /etc/default/minidlna
(
cat <<'EOF'
# Defaults for minidlna initscript
# sourced by /etc/init.d/minidlna
# installed at /etc/default/minidlna by the maintainer scripts
 
# These options can be set to modify the behavior of the minidlna init script.
# The options commented out show the default values.
 
# Start the daemon if set to "yes"
START_DAEMON="yes"
 
# Path to the configuration file
CONFIGFILE="/etc/minidlna.conf"
 
# Path to the log file
LOGFILE="/var/log/minidlna.log"
 
# User and group the daemon should run as
USER="minidlna"
GROUP="minidlna"
 
# Additional options that are passed to the daemon
# DAEMON_OPTS=""

EOF
) > /etc/default/minidlna

#### /etc/minidlna.conf
(
cat <<'EOF'
# port for HTTP (descriptions, SOAP, media transfer) traffic
port=49200
network_interface=<interface>
 
# set this to the directory you want scanned.
# * if have multiple directories, you can have multiple media_dir= lines
# * if you want to restrict a media_dir to a specific content type, you
#   can prepend the type, followed by a comma, to the directory:
#   + "A" for audio  (eg. media_dir=A,/home/jmaggard/Music)
#   + "V" for video  (eg. media_dir=V,/home/jmaggard/Videos)
#   + "P" for images (eg. media_dir=P,/home/jmaggard/Pictures)
media_dir=V,/home/samba/public/Video
 
# set this if you want to customize the name that shows up on your clients
friendly_name=Serveur Multimédia
 
# set this if you would like to specify the directory where you want MiniDLNA to store its database and album art cache
db_dir=/tmp
 
# set this if you would like to specify the directory where you want MiniDLNA to store its log file
log_dir=/var/log
 
# this should be a list of file names to check for when searching for album art
# note: names should be delimited with a forward slash ("/")
album_art_names=Cover.jpg/cover.jpg/AlbumArtSmall.jpg/albumartsmall.jpg/AlbumArt.jpg/albumart.jpg/Album.jpg/album.jpg/Folder.jpg/folder.jpg/Thumb.jpg/thumb.jpg
 
# set this to no to disable inotify monitoring to automatically discover new files
# note: the default is yes
inotify=yes
 
# set this to yes to enable support for streaming .jpg and .mp3 files to a TiVo supporting HMO
enable_tivo=no
 
# set this to strictly adhere to DLNA standards.
# * This will allow server-side downscaling of very large JPEG images,
#   which may hurt JPEG serving performance on (at least) Sony DLNA products.
strict_dlna=no
 
# default presentation url is http address on port 80
#presentation_url=http://www.mylan/index.php
 
# notify interval in seconds. default is 895 seconds.
notify_interval=900
 
# serial and model number the daemon will report to clients
# in its XML description
serial=12345678
model_number=1

EOF
) > /etc/minidlna.conf
sed -i "s/<interface>/$NEWUSER\:$PASSWORD/g" /etc/MySB/web/rutorrent/conf/users/$NEWUSER/plugins/stream/config.php
	
# -----------------------------------------
source /etc/MySB/inc/includes_after.bsh
# -----------------------------------------
##################### LAST LINE ######################################