#!/bin/bash
# ----------------------------------
source $(dirname $0)/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### Install packages
gfnPackageBundleInstall "backup-manager"

#### Configuration file
[ -f /etc/backup-manager.conf ] && rm -vf /etc/backup-manager.conf
install -v -o root -g root -m 0600 $MySB_InstallDir/templates/backup-manager/etc.backup-manager.conf.tmpl /etc/MySB/BM_MySB.conf
source /etc/MySB/config_db
perl -pi -e "s/<MySB_InstallDir>/$gsInstallDirEscaped/g" /etc/MySB/BM_MySB.conf
perl -pi -e "s/<MySQL_BackupManager>/$MySQL_BackupManager/g" /etc/MySB/BM_MySB.conf

#### Cron daily
#install -v -o root -g root -m 0755 $MySB_InstallDir/templates/backup-manager/etc.cron.daily.backup-manager.tmpl /etc/cron.daily/backup-manager

#### Tool
install -v -o root -g root -m 0755 $MySB_InstallDir/templates/backup-manager/usr.bin.backup-manager-tools.tmpl /usr/bin/backup-manager-tools

#### Scripts PRE and POST command
if [ ! -d $MySB_InstallDir/confs ]; then
	mkdir -vp $MySB_InstallDir/confs
fi
install -v -o root -g root -m 0600 $MySB_InstallDir/templates/backup-manager/confs.bm_pre.sh.tmpl $MySB_InstallDir/confs/bm_pre.sh
install -v -o root -g root -m 0600 $MySB_InstallDir/templates/backup-manager/confs.bm_post.sh.tmpl $MySB_InstallDir/confs/bm_post.sh
perl -pi -e "s/<MySB_InstallDir>/$gsInstallDirEscaped/g" $MySB_InstallDir/confs/bm_post.sh

#### Creating backup directory if doesn't exist
if [ ! -d ${MySB_InstallDir}_backup ]; then
	mkdir -vp ${MySB_InstallDir}_backup
fi

# -----------------------------------------
source $(dirname $0)/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################