#!/bin/bash
# ----------------------------------
source $(dirname $0)/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### Install packages
if ! CheckCommand 0 named; then
	PackagesManage install "bind9"
fi

#### Correcting minor bug display in Bind9 init script
if [ -z "`cat /etc/init.d/bind9 | grep 'echo "waiting for pid \$pid to die" > /dev/null'`" ]; then
	sed -i "s/echo \"waiting for pid \$pid to die\"/echo \"waiting for pid \$pid to die\" > \/dev\/null/g" /etc/init.d/bind9
fi
if [ -z "`cat /etc/init.d/bind9 | grep 'echo "giving up on pid \$pid with kill -0; trying -9" > /dev/null'`" ]; then
	sed -i "s/echo \"giving up on pid \$pid with kill -0; trying -9\"/echo \"giving up on pid \$pid with kill -0; trying -9\" > \/dev\/null/g" /etc/init.d/bind9
fi
if [ -z "`cat /etc/init.d/bind9 | grep 'echo "giving up on pid \$pid" > /dev/null'`" ]; then
	sed -i "s/echo \"giving up on pid \$pid\"/echo \"giving up on pid \$pid\" > \/dev\/null/g" /etc/init.d/bind9
fi

#### START services
ManageServices stop "bind9"

#### /etc/bind/named.conf.local
sed -i '/\/etc\/bind\/zones.rfc1918/d' /etc/bind/named.conf.local
sed -i '/\/etc\/bind\/rndc.key/d' /etc/bind/named.conf.local
sed -i '/\/etc\/bind\/bind.keys/d' /etc/bind/named.conf.local
sed -i '/\/etc\/bind\/log.conf/d' /etc/bind/named.conf.local
sed -i '/\/etc\/bind\/MySB.zones.blakclists/d' /etc/bind/named.conf.local
echo "include \"/etc/bind/zones.rfc1918\";" | tee -a /etc/bind/named.conf.local
echo "include \"/etc/bind/rndc.key\";" | tee -a /etc/bind/named.conf.local
echo "include \"/etc/bind/bind.keys\";" | tee -a /etc/bind/named.conf.local
echo "include \"/etc/bind/log.conf\";" | tee -a /etc/bind/named.conf.local
echo "include \"/etc/bind/MySB.zones.blakclists\";" | tee -a /etc/bind/named.conf.local

#### /etc/bind/log.conf
if [ -f /etc/bind/log.conf ]; then rm -vf /etc/bind/log.conf; fi
touch /etc/bind/log.conf
cat $MySB_InstallDir/templates/etc.bind.log.conf.template | tee -a /etc/bind/log.conf
chmod 0644 /etc/bind/log.conf
chown root:bind /etc/bind/log.conf
if [ ! -d /var/log/bind ]; then
	mkdir /var/log/bind
	chown -R bind:bind /var/log/bind
	chmod 0755 /var/log/bind
fi

#### /etc/bind/named.conf.options
sed -i '/listen-on-v6/d' /etc/bind/named.conf.options
sed -i '/allow-transfer/d' /etc/bind/named.conf.options
sed -i '/recursion/d' /etc/bind/named.conf.options
sed -i '/forwarders/d' /etc/bind/named.conf.options
sed -i '/forward/d' /etc/bind/named.conf.options
sed -i '/DNScrypt-proxy/d' /etc/bind/named.conf.options
sed -i '/version/d' /etc/bind/named.conf.options
sed -i '/auth-nxdomain/d' /etc/bind/named.conf.options
sed -i '/listen-on/d' /etc/bind/named.conf.options
sed -i '/allow-query/d' /etc/bind/named.conf.options
sed -i '/dnssec-enable/d' /etc/bind/named.conf.options
sed -i '/dnssec-validation/d' /etc/bind/named.conf.options
sed -i '/dnssec-lookaside/d' /etc/bind/named.conf.options
sed -i '/transfer-source/d' /etc/bind/named.conf.options
sed -i '/notify-source/d' /etc/bind/named.conf.options

NumLign=$(sed -n "/directory \"\/var\/cache\/bind\";/=" /etc/bind/named.conf.options)
(( NumLign++ ))
sed -i "${NumLign}i\        version \"MySB DNS server\";" /etc/bind/named.conf.options
(( NumLign++ ))
sed -i "${NumLign}i\        auth-nxdomain no;    # conform to RFC1035" /etc/bind/named.conf.options
(( NumLign++ ))
sed -i "${NumLign}i\        listen-on    { 127.0.0.1; 10.0.0.1; 10.0.1.1; 10.0.2.1; };" /etc/bind/named.conf.options
(( NumLign++ ))
sed -i "${NumLign}i\        allow-query { any; };" /etc/bind/named.conf.options
(( NumLign++ ))
sed -i "${NumLign}i\        dnssec-enable yes;" /etc/bind/named.conf.options
(( NumLign++ ))
sed -i "${NumLign}i\        dnssec-validation yes;" /etc/bind/named.conf.options
(( NumLign++ ))
sed -i "${NumLign}i\        dnssec-lookaside auto;" /etc/bind/named.conf.options
(( NumLign++ ))
sed -i "${NumLign}i\        transfer-source $SrvIpAddress;" /etc/bind/named.conf.options
(( NumLign++ ))
sed -i "${NumLign}i\        notify-source $SrvIpAddress;" /etc/bind/named.conf.options

chmod 0644 /etc/bind/named.conf.options
chown root:bind /etc/bind/named.conf.options

#### /etc/bind/MySB.zones.blakclists
touch /etc/bind/MySB.zones.blakclists
echo "#### MySB - Blacklisted domains (ex: inactive trackers)" | tee -a /etc/bind/MySB.zones.blakclists
chmod 0644 /etc/bind/MySB.zones.blakclists
chown root:bind /etc/bind/MySB.zones.blakclists

#### logrotate
if [ -f /etc/logrotate.d/bind ]; then rm -vf /etc/logrotate.d/bind; fi
(
cat <<'EOF'
/var/log/bind/*.log {
	weekly
	missingok
	rotate 10
	compress
	delaycompress
	create 775 root bind
	postrotate
	/etc/init.d/bind9 reload > /dev/null
	endscript
}

EOF
) | tee -a /etc/logrotate.d/bind

#### Disable init
update-rc.d bind9 remove -f

#### START services
ManageServices start "bind9"

#### Check if service is OK and running
if ! GetPid bind9; then
	service bind9 status | tee -a $MySB_InstallDir/temp/continue
else
	sqlite3 -cmd '.timeout 150000' -echo $MySB_DB "UPDATE services SET to_install = '0', is_installed = '1' WHERE serv_name = 'BIND';"
fi

# -----------------------------------------
source $(dirname $0)/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################