#!/bin/bash
# ----------------------------------
# shellcheck source=inc/includes_before
source "$(dirname "$0")"/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#	_\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#	 _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#	  _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#	   _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#		_\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#		 _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#		  _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
######################################################################
# https://www.dnsperf.com/
# https://makeawebsitehub.com/free-and-public-dns-services/
# DNS Watch: 84.200.69.80 84.200.70.40
# CloudFlare: 1.1.1.1 1.0.0.1
##################### FIRST LINE #####################################

#### Install packages
if ! gfnCheckCommand 0 named; then
    gfnPackageBundleInstall 'bind9'
fi

#### START services
gfnManageServices stop "bind9"

#### /etc/bind/named.conf.local
install -v -o bind -g root -m 0774 "${MySB_InstallDir}"/templates/bind/etc.bind.named.conf.local.tmpl /etc/bind/named.conf.local

#### /etc/bind/log.conf
install -v -o bind -g root -m 0774 "${MySB_InstallDir}"/templates/bind/etc.bind.log.conf.tmpl /etc/bind/log.conf
install -d -v -o bind -g root -m 0775 /var/log/bind
while read -r sFile; do
    touch "${sFile//\"/}"
done < <(grep 'file ' /etc/bind/log.conf | awk '{ print $2 }')
chmod -v 0664 /var/log/bind/*.log
chown -v bind:bind /var/log/bind/*.log

#### /etc/bind/named.conf.options
sValues=()
for sDNS in "${gaDnsList[@]}"; do
    sValues+=("${sDNS};")
done
install -v -o bind -g root -m 0774 "${MySB_InstallDir}"/templates/bind/etc.bind.named.conf.options.tmpl /etc/bind/named.conf.options
sed -i "s/<gsSrvIpAddress>/${gsSrvIpAddress}/g;" /etc/bind/named.conf.options
sed -i "s/<DNS>/${sValues[*]}/g;" /etc/bind/named.conf.options

#### /etc/bind/MySB.zones.blacklists
echo "#### MySB - Blacklisted domains (ex: inactive trackers)" >/etc/bind/MySB.zones.blacklists
chown bind:root /etc/bind
chmod 2774 /etc/bind

#### logrotate
gfnLogRotate 'bind'

# Disable IPv6
{
    echo "# run resolvconf?"
    echo "RESOLVCONF=yes"
    echo
    echo "# startup options for the server"
    echo 'OPTIONS="-u bind -4"'
    echo
} >/etc/default/bind9
chown 0644 /etc/default/bind9

#### START services
gfnManageServices start "bind9"

# Switch to bind
gfnSwitchDNS "bind"

#### Check internet
ping -c3 github.com

#### Check if service is OK and running
if ! gfnGetPid bind9 || ! gfnCheckCommand 0 bind9; then
    cmdMySQL 'MySB_db' "UPDATE services SET to_install = '0', is_installed = '0' WHERE serv_name = 'BIND';" -v
    systemctl status bind9 | tee -a "${MySB_InstallDir}"/temp/continue
else
    cmdMySQL 'MySB_db' "UPDATE services SET to_install = '0', is_installed = '1' WHERE serv_name = 'BIND';" -v
fi

# -----------------------------------------
# shellcheck source=inc/includes_after
source "$(dirname "$0")"/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################
