#!/bin/bash
# ----------------------------------
source /etc/MySB/inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___        
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_       
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_      
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__     
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_    
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_   
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_  
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__ 
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################
#
# Usage:	Certificates$CEND {CreateCACertificate|CreateServiceCertificate <service_name>}
#
##################### FIRST LINE #####################################

COMMAND=$1
SERVICENAME=$2

#### Create CA
CreateCACertificate() {
	# create needed files and directories
	if [ -d /etc/MySB/ssl/CA ]; then
		rm -rf /etc/MySB/ssl/CA
	else
		mkdir -p /etc/MySB/ssl/CA
	fi
	if [ ! -d /etc/MySB/ssl/CA/private/ ]; then
		mkdir -p /etc/MySB/ssl/CA/private/
	fi
	if [ ! -d /etc/MySB/ssl/CA/newcerts/ ]; then
		mkdir -p /etc/MySB/ssl/CA/newcerts/
	fi
	if [ ! -d /etc/MySB/ssl/CA/certs/ ]; then
		mkdir -p /etc/MySB/ssl/CA/certs/
	fi
	if [ ! -d /etc/MySB/ssl/crl/ ]; then
		mkdir -p /etc/MySB/ssl/CA/crl/
	fi

	# 2 - Change working directory
	cd /etc/MySB/ssl/CA/

	# 3 - OpenSSL config
	cp /etc/MySB/templates/root.ca.cacert.conf.template ./MySB_caconfig.cnf
	perl -pi -e "s/<servername>/$HOSTFQDN/g" ./MySB_caconfig.cnf
	perl -pi -e "s/<email>/$EMAILUSER/g" ./MySB_caconfig.cnf
	perl -pi -e "s/<ipaddress>/$IPADDRESS/g" ./MySB_caconfig.cnf

	#### 4 - Certificate Authority
	echo '01' > ./serial
	touch ./index.txt

	openssl req -new -x509 -extensions v3_ca -keyout ./private/cakey.pem -passout pass:$CERTPASS -out ./certs/cacert.pem -days 3650 -config ./MySB_caconfig.cnf
	openssl req -new -nodes -out ./req.pem -passout pass:$CERTPASS -config ./MySB_caconfig.cnf
	openssl ca -batch -out ./cert.pem -config ./MySB_caconfig.cnf -passin pass:$CERTPASS -infiles ./req.pem
	mv ./cert.pem ./tmp.pem
	openssl x509 -in ./tmp.pem -out ./cert.pem
	cat ./key.pem ./cert.pem > ./key-cert.pem
	chmod 644 ./cert.pem
	chmod 644 ./key.pem
}

# Services Certificate
CreateServiceCertificate() {
	cd /etc/MySB/ssl/CA/

	SUBJ="/C=FR/ST=FR/L=FR/O=MySB/CN=$HOSTFQDN/emailAddress=$EMAILUSER/OU=$SERVICENAME"
	
	if [ ! -f /etc/MySB/ssl/$SERVICENAME.key ]; then
		openssl genrsa 1024 | sudo tee ./$SERVICENAME.key
		openssl req -new -x509 -nodes -sha1 -days 3650 -key ./$SERVICENAME.key -config ./MySB_caconfig.cnf -batch -subj $SUBJ | sudo tee ./$SERVICENAME.cert
		openssl ca -batch -keyfile ./private/cakey.pem -passin pass:$CERTPASS -subj $SUBJ -out ./$SERVICENAME.pem -config ./MySB_caconfig.cnf -passin pass:$CERTPASS -ss_cert ./$SERVICENAME.cert
		chmod 600 ./$SERVICENAME.*
		mv ./$SERVICENAME.* ../
	fi
}

case "$COMMAND" in
	"CreateCACertificate")
		CreateCACertificate
	;;
	"CreateServiceCertificate")
		if [ ! -z $2 ]; then
			CreateServiceCertificate '$2'
		else
			echo -e "${CBLUE}Usage:$CEND	${CYELLOW}bash /etc/MySB/install/Certificates$CEND ${CGREEN}{CreateCACertificate|CreateServiceCertificate <service_name>}$CEND"
			echo -e "${CBLUE}Give me the service name too please.$CEND"
		fi
	;;
	*)
		echo -e "${CBLUE}Usage:$CEND	${CYELLOW}bash /etc/MySB/install/Certificates$CEND ${CGREEN}{CreateCACertificate|CreateServiceCertificate <service_name>}$CEND"
		exit	
	;;
esac

# -----------------------------------------
source /etc/MySB/inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################