#!/bin/bash
# ----------------------------------
# shellcheck source=inc/includes_before
source "$(dirname "$0")"/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#	_\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#	 _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#	  _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#	   _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#		_\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#		 _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#		  _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation les (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### Net check
if (! ping -c2 www.cpan.org >/dev/null 2>&1); then
    gfnEndingScript 0
fi

#### Directories
[ ! -d /root/.cpan/CPAN ] && {
    mkdir -pv /root/.cpan/CPAN
    chmod -v 0755 /root/.cpan
    chmod -v 0755 /root/.cpan/CPAN
}

#### Config
install -v -o root -g root -m 0750 ${MySB_InstallDir}/templates/cpan/root.cpan.listmodules.pl.tmpl /root/.cpan/listmodules.pl
install -v -o root -g root -m 0644 ${MySB_InstallDir}/templates/cpan/root.cpan.CPAN.MyConfig.pm.tmpl /root/.cpan/CPAN/MyCong.pm

#### Modules updates
if [ ! -f /tmp/CPAN.lock ]; then
    touch /tmp/CPAN.lock
    cpan -u
    rm -f /tmp/CPAN.lock
fi

#### Modules install
# CPAN::SQLite
[ -z "$(perl /root/.cpan/listmodules.pl | grep "^CPAN::SQLite$")" ] && cpan -i -T CPAN::SQLite

# Log::Log4perl
[ -z "$(perl /root/.cpan/listmodules.pl | grep "^Log::Log4perl$")" ] && cpan -i -T Log::Log4perl

# CPAN
[ -z "$(perl /root/.cpan/listmodules.pl | grep "^CPAN$")" ] && cpan -i -T CPAN

# YAML
[ -z "$(perl /root/.cpan/listmodules.pl | grep "^YAML$")" ] && cpan -i -T YAML

# Crypt::RIPEMD160
[ -z "$(perl /root/.cpan/listmodules.pl | grep "^Crypt::RIPEMD160$")" ] && cpan -i -T Crypt::RIPEMD160

# Digest::SHA
[ -z "$(perl /root/.cpan/listmodules.pl | grep "^Digest::SHA$")" ] && cpan -i -T Digest::SHA

# Digest::SHA1
[ -z "$(perl /root/.cpan/listmodules.pl | grep "^Digest::SHA1$")" ] && cpan -i -T Digest::SHA1

# Digest::SHA256
[ -z "$(perl /root/.cpan/listmodules.pl | grep "^Digest::SHA256$")" ] && cpan -i -T Digest::SHA256

# Digest::SHA::PurePerl
[ -z "$(perl /root/.cpan/listmodules.pl | grep "^Digest::SHA::PurePerl$")" ] && cpan -i -T Digest::SHA::PurePerl

# Digest::Whirlpool
[ -z "$(perl /root/.cpan/listmodules.pl | grep "^Digest::Whirlpool$")" ] && cpan -i -T Digest::Whirlpool

# LWP
[ -z "$(perl /root/.cpan/listmodules.pl | grep "^LWP$")" ] && cpan -i -T LWP

# HTTP::Daemon::SSL
[ -z "$(perl /root/.cpan/listmodules.pl | grep "^HTTP::Daemon::SSL$")" ] && cpan -i -T HTTP::Daemon::SSL

# Convert::Bencode_XS
[ -z "$(perl /root/.cpan/listmodules.pl | grep "^Convert::Bencode_XS$")" ] && cpan -i -T Convert::Bencode_XS

# File::stat
[ -z "$(perl /root/.cpan/listmodules.pl | grep "^File::stat$")" ] && cpan -i -T File::stat

# Getopt::Long
[ -z "$(perl /root/.cpan/listmodules.pl | grep "^Getopt::Long$")" ] && cpan -i -T Getopt::Long

# Digest::MD5
[ -z "$(perl /root/.cpan/listmodules.pl | grep "^Digest::MD5$")" ] && cpan -i -T Digest::MD5

# URI
[ -z "$(perl /root/.cpan/listmodules.pl | grep "^URI$")" ] && cpan -i -T URI

# HTTP::Status
[ -z "$(perl /root/.cpan/listmodules.pl | grep "^HTTP::Status$")" ] && cpan -i -T HTTP::Status

# HTTP::Date
[ -z "$(perl /root/.cpan/listmodules.pl | grep "^HTTP::Date$")" ] && cpan -i -T HTTP::Date

# Socket
[ -z "$(perl /root/.cpan/listmodules.pl | grep "^Socket$")" ] && cpan -i -T Socket

# Carp
[ -z "$(perl /root/.cpan/listmodules.pl | grep "^Carp$")" ] && cpan -i -T Carp

# inc::latest
[ -z "$(perl /root/.cpan/listmodules.pl | grep "^inc::latest$")" ] && cpan -i -T inc::latest

#### List all modules
perl /root/.cpan/listmodules.pl

# -----------------------------------------
# shellcheck source=inc/includes_after
source "$(dirname "$0")"/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################
