#!/bin/bash
# ----------------------------------
source $(dirname $0)/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#	_\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#	 _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#	  _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#	   _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#		_\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#		 _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#		  _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### CPAN
if [ ! -d /root/.cpan/CPAN ]; then
	mkdir -pv /root/.cpan/CPAN
	chmod -v 0755 /root/.cpan
	chmod -v 0755 /root/.cpan/CPAN
fi
install -v -o root -g root -m 0750 $MySB_InstallDir/templates/cpan/root.cpan.listmodules.pl.tmpl /root/.cpan/listmodules.pl
install -v -o root -g root -m 0644 $MySB_InstallDir/templates/cpan/root.cpan.CPAN.MyConfig.pm.tmpl /root/.cpan/CPAN/MyConfig.pm

#### Modules install
# CPAN::SQLite
if [ -z "`perl /root/.cpan/listmodules.pl | grep "^CPAN::SQLite$"`" ]; then
	cpan -i -T CPAN::SQLite
fi
# Log::Log4perl
if [ -z "`perl /root/.cpan/listmodules.pl | grep "^Log::Log4perl$"`" ]; then
	cpan -i -T Log::Log4perl
fi
# CPAN
if [ -z "`perl /root/.cpan/listmodules.pl | grep "^CPAN$"`" ];then
	cpan -i -T CPAN
fi
# YAML
if [ -z "`perl /root/.cpan/listmodules.pl | grep "^YAML$"`" ];then
	cpan -i -T YAML
fi
# Crypt::RIPEMD160
if [ -z "`perl /root/.cpan/listmodules.pl | grep "^Crypt::RIPEMD160$"`" ]; then
	cpan -i -T Crypt::RIPEMD160
fi
# Digest::SHA1
if [ -z "`perl /root/.cpan/listmodules.pl | grep "^Digest::SHA1$"`" ]; then
	cpan -i -T Digest::SHA1
fi
# Digest::SHA256
if [ -z "`perl /root/.cpan/listmodules.pl | grep "^Digest::SHA256$"`" ]; then
	cpan -i -T Digest::SHA256
fi
# Digest::SHA::PurePerl
if [ -z "`perl /root/.cpan/listmodules.pl | grep "^Digest::SHA::PurePerl$"`" ]; then
	cpan -i -T Digest::SHA::PurePerl
fi
# Digest::Whirlpool
if [ -z "`perl /root/.cpan/listmodules.pl | grep "^Digest::Whirlpool$"`" ]; then
	cpan -i -T Digest::Whirlpool
fi
# LWP
if [ -z "`perl /root/.cpan/listmodules.pl | grep "^LWP$"`" ]; then
	cpan -i -T LWP
fi
# HTTP::Daemon::SSL
if [ -z "`perl /root/.cpan/listmodules.pl | grep "^HTTP::Daemon::SSL$"`" ]; then
	cpan -i -T HTTP::Daemon::SSL
fi
# inc::latest
if [ -z "`perl /root/.cpan/listmodules.pl | grep "^inc::latest$"`" ]; then
	cpan -i -T inc::latest
fi

#### List all modules
perl /root/.cpan/listmodules.pl

# -----------------------------------------
source $(dirname $0)/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################
