#!/bin/bash
# ----------------------------------
# shellcheck source=inc/includes_before
source "$(dirname "$0")"/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#	_\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#	 _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#	  _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#	   _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#		_\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#		 _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#		  _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation les (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### Net check
if (! ping -c2 www.cpan.org >/dev/null 2>&1); then
    gfnEndingScript 0
fi

#### Directories
[ ! -d /root/.cpan/CPAN ] && {
    mkdir -pv /root/.cpan/CPAN
    chmod -v 0755 /root/.cpan
    chmod -v 0755 /root/.cpan/CPAN
}

if [ "${gsSwitch}" != "CRON" ]; then
    #### Config
    install -v -o root -g root -m 0750 "${MySB_InstallDir}"/templates/cpan/root.cpan.listmodules.pl.tmpl /root/.cpan/listmodules.pl
    install -v -o root -g root -m 0644 "${MySB_InstallDir}"/templates/cpan/root.cpan.CPAN.MyConfig.pm.tmpl /root/.cpan/CPAN/MyConfig.pm

    #### Install
    cpan -i -T CPAN::SQLite
    cpan -i -T Log::Log4perl
    cpan -i -T Term::ANSIColor
fi

if [ "${gsSwitch}" == "CRON" ] && [ ! -f /tmp/CPAN.lock ]; then
    #### Modules install
    aModules=('CPAN' 'YAML' 'Crypt::RIPEMD160' 'Digest::SHA' 'Digest::SHA1' 'Digest::SHA256' 'Digest::SHA::PurePerl' 'Digest::Whirlpool' 'LWP' 'HTTP::Daemon::SSL')
    aModules+=('Convert::Bencode_XS' 'File::stat' 'Getopt::Long' 'Digest::MD5' 'URI' 'HTTP::Status' 'HTTP::Date' 'Socket' 'Carp' 'inc::latest')
    touch /tmp/CPAN.lock
    for sModule in "${aModules[@]}"; do
        (! grep -q "^${sModule}$" <<<"$(perl /root/.cpan/listmodules.pl)") && cpan -i -T "${sModule}"
    done
    rm -f /tmp/CPAN.lock

    #### Modules updates
    if [ ! -f /tmp/CPAN.lock ]; then
        touch /tmp/CPAN.lock
        cpan -u
        rm -f /tmp/CPAN.lock
    fi
fi

#### Remove temp files
rm -fv /tmp/cpan_install_*.txt
rm -f /tmp/CPAN.lock

#### List all modules
perl /root/.cpan/listmodules.pl

# -----------------------------------------
# shellcheck source=inc/includes_after
source "$(dirname "$0")"/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################
