#!/bin/bash 
# ----------------------------------
source /etc/MySB/inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___        
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_       
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_      
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__     
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_    
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_   
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_  
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__ 
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

if [ ! -d /etc/MySB/sources ]; then
	mkdir /etc/MySB/sources
fi		
if [ ! -d /etc/MySB/users ]; then
	mkdir /etc/MySB/users
fi
if [ ! -d /etc/MySB/infos ]; then
	mkdir /etc/MySB/infos
fi
if [ ! -d /etc/MySB/logs ]; then
	mkdir /etc/MySB/logs
fi		
if [ ! -d /etc/MySB/files ]; then
	mkdir /etc/MySB/files
fi
if [ ! -d /etc/MySB/temp ]; then
	mkdir /etc/MySB/temp
fi	
if [ ! -d /etc/MySB/web/logs/install ]; then
	mkdir -p /etc/MySB/web/logs/install
fi
if [ ! -d /etc/MySB/web/logs/scripts ]; then
	mkdir -p /etc/MySB/web/logs/scripts
fi
if [ ! -d /etc/MySB/web/logs/bin ]; then
	mkdir -p /etc/MySB/web/logs/bin
fi
if [ ! -d /etc/MySB/web/logs/nginx ]; then
	mkdir -p /etc/MySB/web/logs/nginx
fi
if [ ! -d /etc/MySB/web/logs/security ]; then
	mkdir -p /etc/MySB/web/logs/security
fi			
			
chmod +x /etc/MySB/MySB_Install.sh
chmod +x /etc/MySB/MySB_CleanAll.sh
chmod +x /etc/MySB/bin/*
chmod +x /etc/MySB/scripts/*
chmod +x /etc/MySB/install/*
			
dos2unix /etc/MySB/*
dos2unix /etc/MySB/inc/*
dos2unix /etc/MySB/bin/*
dos2unix /etc/MySB/files/*
dos2unix /etc/MySB/scripts/*
dos2unix /etc/MySB/install/*
dos2unix /etc/MySB/templates/*
	
# -----------------------------------------
source /etc/MySB/inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################