#!/bin/bash
# ----------------------------------
source $(dirname $0)/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

if [ "$ToInstall_Fail2Ban" == "YES" ]; then
	#### Install packages
	PackagesManage install "fail2ban"
	
	#### STOP services
	ManageServices stop "fail2ban"	

	# conf fail2ban
	cp $MySB_InstallDir/templates/etc.fail2ban.jail.local.template /etc/fail2ban/jail.local
	sed -i 's/<Port_SSH>/'$Port_SSH'/g;' /etc/fail2ban/jail.local
	sed -i 's/<Port_HTTP>/'$Port_HTTP'/g;' /etc/fail2ban/jail.local
	sed -i 's/<Port_HTTPS>/'$Port_HTTPS'/g;' /etc/fail2ban/jail.local
	sed -i 's/<Port_FTP>/'$Port_FTP'/g;' /etc/fail2ban/jail.local
	sed -i 's/<Port_FTP_Data>/'$Port_FTP_Data'/g;' /etc/fail2ban/jail.local

	cp $MySB_InstallDir/templates/etc.fail2ban.filter.d.nginx-auth.conf.template /etc/fail2ban/filter.d/nginx-auth.conf
	cp $MySB_InstallDir/templates/etc.fail2ban.filter.d.nginx-badbots.conf.template /etc/fail2ban/filter.d/nginx-badbots.conf
	cp $MySB_InstallDir/templates/etc.fail2ban.filter.d.nginx-login.template /etc/fail2ban/filter.d/nginx-login.conf

	#### Add white list
	Fail2BanWhitheList 0
	
	#### Disable init, Fail2Ban will be started by MySB_SecurityRules
	update-rc.d fail2ban remove -f

	#### Clean current log file
	logrotate -f /etc/logrotate.d/fail2ban
	
	if CheckCommand 0 fail2ban; then
		sqlite3 -cmd '.timeout 150000' -echo $MySB_DB "UPDATE services SET to_install = '0', is_installed = '1' WHERE serv_name = 'Fail2Ban';"
	fi
	
	#### Create new security rules
	ScriptInvoke 'screen' "$MySB_InstallDir/bin/MySB_SecurityRules" 'create'
fi

# -----------------------------------------
source $(dirname $0)/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################