#!/bin/bash
# ----------------------------------
source $(dirname $0)/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### LoadAvg
LoadAvgValues="`Func_SQL_Command 'SELECT' 'MySB_db' 'url,file,version' 'repositories' "name = 'LoadAvg'"`"
LoadAvgUrl="`echo $LoadAvgValues | awk '{split($0,a,"|"); print a[1]}'`"
LoadAvgFile="`echo $LoadAvgValues | awk '{split($0,a,"|"); print a[2]}'`"
LoadAvgVersion="`echo $LoadAvgValues | awk '{split($0,a,"|"); print a[3]}'`"
echo
echo "########## LoadAvg"
echo "Directory : "$LoadAvgDir
echo "Version : "$LoadAvgVersion
echo "File : "$LoadAvgFile
echo "URL : "$LoadAvgUrl
echo
if [ ! -f $MySB_InstallDir/files/$LoadAvgFile ]; then
	curl --retry 2 -kSL -o "$MySB_InstallDir/files/$LoadAvgFile" "$LoadAvgUrl"
fi
if [ ! -d $LoadAvgDir ] && [ -f $MySB_InstallDir/files/$LoadAvgFile ]; then
	tar -zxvf $MySB_InstallDir/files/$LoadAvgFile -C $MySB_InstallDir/temp/
	SubDir="`tar -ztf $MySB_InstallDir/files/$LoadAvgFile | sed -e 's@/.*@@' | uniq`"
	if [ -d $MySB_InstallDir/temp/$SubDir ]; then
		mv $MySB_InstallDir/temp/$SubDir $LoadAvgDir
	fi
fi

if [ ! -d $LoadAvgDir/logs ]; then
	mkdir $LoadAvgDir/logs
	chmod 0777 $LoadAvgDir/logs
	chown root:www-data $LoadAvgDir/logs
fi

#### Install
cd $LoadAvgDir/
chmod 0777 $LoadAvgDir/configure
./configure

#### settings.ini.php
cp -vf $LoadAvgDir/app/config/default_settings.ini.php $LoadAvgDir/app/config/settings.ini.php
FakePassword="`GenPassword 32`"
TimeZoneEscaped="`echo $TimeZone | sed s,/,\\\\\\\\\\/,g`"
sed -i "/title/s/\"\"/\"$HostNameFQDN\"/g" $LoadAvgDir/app/config/settings.ini.php
sed -i "/allow_anyone/s/false/true/g" $LoadAvgDir/app/config/settings.ini.php
perl -pi -e "s/America\/New_York/$TimeZoneEscaped/g" $LoadAvgDir/app/config/settings.ini.php
sed -i "/username/s/\"\"/\"fake_user\"/g" $LoadAvgDir/app/config/settings.ini.php
sed -i "/password/s/\"\"/\"$FakePassword\"/g" $LoadAvgDir/app/config/settings.ini.php
sed -i "/https/s/false/true/g" $LoadAvgDir/app/config/settings.ini.php
sed -i "/checkforupdates/s/false/true/g" $LoadAvgDir/app/config/settings.ini.php
sed -i "/ban_ip/s/true/false/g" $LoadAvgDir/app/config/settings.ini.php
sed -i "/autoreload/s/false/true/g" $LoadAvgDir/app/config/settings.ini.php
perl -pi -e "s/eno16777736/$PrimaryInet/g" $LoadAvgDir/app/config/settings.ini.php
sed -i "/lo/s/false/true/g" $LoadAvgDir/app/config/settings.ini.php
if [ "$IsInstalled_OpenVPN" == "YES" ] || [ "$ToInstall_OpenVPN" == "YES" ]; then
	NumLign=$(sed -n "/network_interface/=" $LoadAvgDir/app/config/settings.ini.php)
	(( NumLign++ ))
	sed -i "${NumLign}i\br0 = \"true\"" $LoadAvgDir/app/config/settings.ini.php
	sed -i "${NumLign}i\tap0 = \"true\"" $LoadAvgDir/app/config/settings.ini.php
	sed -i "${NumLign}i\tun0 = \"true\"" $LoadAvgDir/app/config/settings.ini.php
	sed -i "${NumLign}i\tun1 = \"true\"" $LoadAvgDir/app/config/settings.ini.php
fi
sed -i "/Processor/s/false/true/g" $LoadAvgDir/app/config/settings.ini.php
sed -i "/Ssh/s/false/true/g" $LoadAvgDir/app/config/settings.ini.php
sed -i "/Swap/s/false/true/g" $LoadAvgDir/app/config/settings.ini.php

#### ssh.ini.php
perl -pi -e "s/\/var\/log\/secure/\/var\/log\/auth.log/g" $LoadAvgDir/lib/modules/Ssh/ssh.ini.php

#### Clean
DeleteDirectory 1 "$LoadAvgDir/install"
chmod 0640 $LoadAvgDir/configure

#### Cron
crontab -l > /tmp/crontab.tmp
sed -i '/loadavg/d' /tmp/crontab.tmp
echo "*/5 * * * * /usr/bin/php -q $LoadAvgDir/logger.php > /dev/null 2>&1" >> /tmp/crontab.tmp
crontab /tmp/crontab.tmp
rm -f /tmp/crontab.tmp

# -----------------------------------------
source $(dirname $0)/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################