#!/bin/bash
# ----------------------------------
source $(dirname $0)/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### LoadAvg
gfnGetRepoValues 'LoadAvg' && gfnRepoManageByType

if [ ! -d $gsLoadAvgDir/logs ]; then
	mkdir -v $gsLoadAvgDir/logs
	chmod -v 0777 $gsLoadAvgDir/logs
	chown -v root:www-data $gsLoadAvgDir/logs
fi

#### Install
cd $gsLoadAvgDir/
chmod -v 0777 $gsLoadAvgDir/configure
./configure

#### settings.ini.php
install -v -o root -g www-data -m 0640 $gsLoadAvgDir/app/config/default_settings.ini.php $gsLoadAvgDir/app/config/settings.ini.php
FakePassword="`gfnGenPassword 32`"
sed -i "/title/s/\"\"/\"$gsHostNameFqdn\"/g" $gsLoadAvgDir/app/config/settings.ini.php
sed -i "/allow_anyone/s/false/true/g" $gsLoadAvgDir/app/config/settings.ini.php
perl -pi -e "s/America\/New_York/$gsTimeZoneEscaped/g" $gsLoadAvgDir/app/config/settings.ini.php
sed -i "/username/s/\"\"/\"fake_user\"/g" $gsLoadAvgDir/app/config/settings.ini.php
sed -i "/password/s/\"\"/\"$FakePassword\"/g" $gsLoadAvgDir/app/config/settings.ini.php
sed -i "/https/s/false/true/g" $gsLoadAvgDir/app/config/settings.ini.php
sed -i "/checkforupdates/s/false/true/g" $gsLoadAvgDir/app/config/settings.ini.php
sed -i "/ban_ip/s/true/false/g" $gsLoadAvgDir/app/config/settings.ini.php
sed -i "/autoreload/s/false/true/g" $gsLoadAvgDir/app/config/settings.ini.php
perl -pi -e "s/eno16777736/$gsPrimaryInet/g" $gsLoadAvgDir/app/config/settings.ini.php
sed -i "/lo/s/false/true/g" $gsLoadAvgDir/app/config/settings.ini.php
if [ "$gbIsInstalled_OpenVPN" == "YES" ] || [ "$gbToInstall_OpenVPN" == "YES" ]; then
	NumLign=$(sed -n "/network_interface/=" $gsLoadAvgDir/app/config/settings.ini.php)
	(( NumLign++ ))
	#sed -i "${NumLign}i\br0 = \"true\"" $gsLoadAvgDir/app/config/settings.ini.php
	#sed -i "${NumLign}i\tap0 = \"true\"" $gsLoadAvgDir/app/config/settings.ini.php
	sed -i "${NumLign}i\tun0 = \"true\"" $gsLoadAvgDir/app/config/settings.ini.php
	sed -i "${NumLign}i\tun1 = \"true\"" $gsLoadAvgDir/app/config/settings.ini.php
fi
sed -i "/Processor/s/false/true/g" $gsLoadAvgDir/app/config/settings.ini.php
sed -i "/Ssh/s/false/true/g" $gsLoadAvgDir/app/config/settings.ini.php
sed -i "/Swap/s/false/true/g" $gsLoadAvgDir/app/config/settings.ini.php

#### ssh.ini.php
perl -pi -e "s/\/var\/log\/secure/\/var\/log\/auth.log/g" $gsLoadAvgDir/lib/modules/Ssh/ssh.ini.php

#### header.php
install -v -o root -g www-data -m 0640 $MySB_InstallDir/templates/loadavg/header.php.tmpl $gsLoadAvgDir/app/layout/header.php

#### Clean
gfnDeleteDirectory 1 "$gsLoadAvgDir/install"
chmod -v 0640 $gsLoadAvgDir/configure

#### Cron
crontab -l > /tmp/crontab.tmp
sed -i '/logger.php/d' /tmp/crontab.tmp
echo "*/5 * * * * /usr/bin/php -q $gsLoadAvgDir/logger.php > /dev/null 2>&1" >> /tmp/crontab.tmp
crontab /tmp/crontab.tmp
rm -f /tmp/crontab.tmp

# -----------------------------------------
source $(dirname $0)/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################