#!/bin/bash 
# ----------------------------------
source ../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

LoadAvgUrl="`sqlite3 -cmd '.timeout 150000' $MySB_DB \"SELECT url FROM repositories WHERE name = 'LoadAvg'\"`"
if [ -d $LoadAvgDir ]; then
	cd $LoadAvgDir
	git stash
	git pull
else
	git clone $LoadAvgUrl $LoadAvgDir
fi

if [ ! -d $LoadAvgDir/logs ]; then
	mkdir $LoadAvgDir/logs
	chmod 0777 $LoadAvgDir/logs
	chown root:www-data $LoadAvgDir/logs
fi

cd $LoadAvgDir
chmod 0777 $LoadAvgDir/configure
./configure

#### Config
cp $InstallDir/templates/etc.myb.web.loadavg.app.config.template $LoadAvgDir/app/config/settings.ini.php
perl -pi -e "s/<server_name>/$HostNameFQDN/g" $LoadAvgDir/app/config/settings.ini.php
TimeZoneEscaped="`echo $TimeZone | sed s,/,\\\\\\\\\\/,g`"
perl -pi -e "s/<time_zone>/$TimeZoneEscaped/g" $LoadAvgDir/app/config/settings.ini.php
perl -pi -e "s/<user_name>/noadmin/g" $LoadAvgDir/app/config/settings.ini.php
FakePassword="`GenPassword 32`"
perl -pi -e "s/<password>/$FakePassword/g" $LoadAvgDir/app/config/settings.ini.php
perl -pi -e "s/eth0/$PrimaryInet/g" $LoadAvgDir/app/config/settings.ini.php
perl -pi -e "s/\/var\/log\/secure/\/var\/log\/auth.log/g" $LoadAvgDir/lib/modules/Ssh/ssh.ini.php

#### Clean
if [ -d $LoadAvgDir/install ]; then
	rm -rf $LoadAvgDir/install
fi
chmod 0640 $LoadAvgDir/configure

#### Cron
crontab -l > /tmp/crontab.tmp
sed -i '/loadavg/d' /tmp/crontab.tmp
echo "*/5 * * * * /usr/bin/php -q $LoadAvgDir/logger.php /dev/null 2>1" >> /tmp/crontab.tmp
crontab /tmp/crontab.tmp
rm -f /tmp/crontab.tmp

# -----------------------------------------
source ../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################