#!/bin/bash
# ----------------------------------
source $(dirname $0)/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

if [ "$ToInstall_LogWatch" == "YES" ]; then
	#### Install packages
	if ! CheckCommand 0 logwatch; then
		PackagesManage install "logwatch"
	fi

	# Config
	if [ ! -d /var/cache/logwatch ]; then
		mkdir -p /var/cache/logwatch
	fi
	# Configuration file
	if [ -f /usr/share/logwatch/default.conf/services/http.conf ]; then
		rm -vf /usr/share/logwatch/default.conf/services/http.conf
	fi
	cp -vf $MySB_InstallDir/templates/logwatch/etc.logwatch.conf.logwatch.conf.tmpl /etc/logwatch/conf/logwatch.conf
	cp -vf $MySB_InstallDir/templates/logwatch/usr.share.logwatch.default.conf.logfiles.nginx.conf.tmpl /usr/share/logwatch/default.conf/logfiles/nginx.conf
	cp -vf $MySB_InstallDir/templates/logwatch/usr.share.logwatch.default.conf.services.nginx.conf.tmpl /usr/share/logwatch/default.conf/services/nginx.conf
	cp -vf /usr/share/logwatch/scripts/services/http /usr/share/logwatch/scripts/services/nginx

	if CheckCommand 0 logwatch; then
		Func_SQL_Command 'UPDATE' 'MySB_db' 'system' "to_install = '0', is_installed = '1'" "serv_name = 'LogWatch'" '-echo'
		Func_SQL_Command 'UPDATE' 'MySB_db' 'services' "logwatch = '1'" "id_system = '1'" '-echo'
	fi
fi

# -----------------------------------------
source $(dirname $0)/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################