#!/bin/bash
# ----------------------------------
source $(dirname $0)/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

if [ "$ToInstall_LogWatch" == "YES" ]; then
	#### Install packages
	PackagesManage install "logwatch"

	# Config
	if [ ! -d /var/cache/logwatch ]; then
		mkdir -p /var/cache/logwatch
	fi
	if [ -f /usr/share/logwatch/default.conf/logwatch.conf ] && [ ! -f /etc/logwatch/conf/logwatch.conf ]; then
		cp /usr/share/logwatch/default.conf/logwatch.conf /etc/logwatch/conf/
	fi
	perl -pi -e "s/^Output = stdout/Output = mail/g" /etc/logwatch/conf/logwatch.conf
	perl -pi -e "s/^Format = text/Format = html/g" /etc/logwatch/conf/logwatch.conf
	perl -pi -e "s/^Range = All/Range = Yesterday/g" /etc/logwatch/conf/logwatch.conf
	NumLign=$(sed -n "/Service = All/=" /etc/logwatch/conf/logwatch.conf)
	(( NumLign++ ))
	sed -i "${NumLign}i\Service = \"-exim\"" /etc/logwatch/conf/logwatch.conf

	# Add Nginx support
	cp -v $MySB_InstallDir/templates/usr.share.logwatch.default.conf.logfiles.nginx.conf.template /usr/share/logwatch/default.conf/logfiles/nginx.conf
	cp -v /usr/share/logwatch/default.conf/services/http.conf /usr/share/logwatch/default.conf/services/nginx.conf
	mv /usr/share/logwatch/default.conf/services/http.conf /usr/share/logwatch/default.conf/services/http.conf.bak
	perl -pi -e "s/^Title = \"httpd\"/Title = \"nginx\"/g" /usr/share/logwatch/default.conf/services/nginx.conf
	perl -pi -e "s/^LogFile = http/LogFile = nginx/g" /usr/share/logwatch/default.conf/services/nginx.conf
	cp -v /usr/share/logwatch/scripts/services/http /usr/share/logwatch/scripts/services/nginx

	if CheckCommand 0 logwatch; then
		sqlite3 -cmd '.timeout 150000' -echo $MySB_DB "UPDATE services SET to_install = '0', is_installed = '1' WHERE serv_name = 'LogWatch';"
	fi
fi

# -----------------------------------------
source $(dirname $0)/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################