#!/bin/bash 
# ----------------------------------
source /etc/MySB/inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___        
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_       
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_      
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__     
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_    
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_   
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_  
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__ 
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### install
PackagesManage install "libnss3-tools heirloom-mailx"
 
#### Create certificates
if [ -d /etc/MySB/ssl/MailX/ ]; then
	rm -rf /etc/MySB/ssl/MailX/
fi
mkdir -p /etc/MySB/ssl/MailX/
mkpasswd MailX > /etc/MySB/ssl/MailX/pwfile
certutil -f /etc/MySB/ssl/MailX/pwfile -N -d /etc/MySB/ssl/MailX

#### Get Provider Certificate
if [ "$SMTP" != "LOCAL" ]; then
	#### mail.rc
	(
	cat <<'EOF'
account <SMTP> {
set smtp-use-starttls
set ssl-verify=ignore
set smtp-auth=login
set smtp=smtp://<SMTP_HOST>:587
set from="<EMAILUSER>(MySB)"
set smtp-auth-user=<SMTP_USER>
set smtp-auth-password=<SMTP_PASS>
set ssl-verify=ignore
set nss-config-dir=/etc/MySB/ssl/MailX
}

EOF
	) > /root/mail.rc
	perl -pi -e "s/<SMTP>/$SMTP/g" /root/mail.rc
	perl -pi -e "s/<SMTP_HOST>/$SMTP_HOST/g" /root/mail.rc
	perl -pi -e "s/<EMAILUSER>/$EMAILUSER/g" /root/mail.rc
	perl -pi -e "s/<SMTP_USER>/$SMTP_USER/g" /root/mail.rc
	perl -pi -e "s/<SMTP_PASS>/$SMTP_PASS/g" /root/mail.rc

	case "$SMTP" in
		"OVH")
			echo -n | openssl s_client -connect ssl0.ovh.net:465 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /etc/MySB/ssl/MailX/ovh.crt
			certutil -A -n "OVH Internet Authority" -t "C,," -d /etc/MySB/ssl/MailX -i /etc/MySB/ssl/MailX/ovh.crt
			SMTP_HOST="ssl0.ovh.net"
			sed -i '/set smtp-use-starttls/d' /root/mail.rc
		;;
		"GMAIL")
			echo -n | openssl s_client -connect smtp.gmail.com:465 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /etc/MySB/ssl/MailX/gmail.crt
			certutil -A -n "Google Internet Authority" -t "C,," -d /etc/MySB/ssl/MailX -i /etc/MySB/ssl/MailX/gmail.crt
			SMTP_HOST="smtp.gmail.com"
		;;
		"YAHOO")
			echo -n | openssl s_client -connect smtp.mail.yahoo.com:465 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /etc/MySB/ssl/MailX/yahoo.crt
			certutil -A -n "Yahoo Internet Authority" -t "C,," -d /etc/MySB/ssl/MailX -i /etc/MySB/ssl/MailX/yahoo.crt
			SMTP_HOST="smtp.mail.yahoo.com"
		;;		
	esac
else
	echo "set from=\"$EMAILUSER(MySB)\"" >> /root/mail.rc
fi

# -----------------------------------------
source /etc/MySB/inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################