#!/bin/bash
# ----------------------------------
# shellcheck source=inc/includes_before
source "$(dirname "$0")"/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#	_\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#	 _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#	  _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#	   _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#		_\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#		 _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#		  _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
######################################################################
# https://computingforgeeks.com/how-to-setup-s3-compatible-object-storage-server-with-minio/
# https://www.digitalocean.com/community/tutorials/how-to-set-up-an-object-storage-server-using-minio-on-ubuntu-16-04
# Multi NginX location for each bucket: https://forum.nginx.org/read.php?11,281903
#
# https://docs.aws.amazon.com/fr_fr/AmazonS3/latest/dev/using-with-s3-actions.html
##################### FIRST LINE #####################################

#### Check for a new version / Install it
gfnInstallMinio
gfnInstallMinioClient
fnInstallGoofys

#### Config
case "${gsSwitch}" in
    'INSTALL' | 'UPGRADE')
        if (gfnCheckCommand 0 /usr/local/bin/minio) && [ -f /lib/systemd/system/minio.service ]; then
            gfnManageServices stop minio
        fi

        (! grep -q 'minio' /etc/group) && groupadd --system minio
        (! grep -q 'minio' /etc/passwd) && useradd -d /home/minio -s /usr/sbin/nologin --system -g minio minio

        #### /etc/default/minio
        gfnMinioEtcDefault

        install -v -o root -g root -m 0644 "${MySB_InstallDir}"/templates/minio/minio.service.tmpl /lib/systemd/system/minio.service
        systemctl daemon-reload
        systemctl enable minio.service
        install -d -v -o minio -g minio -m 0755 /etc/minio
        install -d -v -o minio -g minio -m 0755 /etc/minio/certs
        install -d -v -o minio -g minio -m 0755 /etc/minio/certs/CAs
        install -d -v -o minio -g minio -m 0755 /home/minio/data

        #### Certificate
        gfnMinioCertificate

        if (gfnCheckCommand 0 /usr/local/bin/minio) && [ -f /lib/systemd/system/minio.service ]; then
            gfnManageServices start minio
        fi

        #### Minio client host config (alias)
        gfnMinioHostConfig

        # Seedbox user
        # shellcheck source=inc/funcs_by_script/funcs_MySB_CreateUser
        source "${MySB_InstallDir}"/inc/funcs_by_script/funcs_MySB_CreateUser
        gfnMinioUsersBuckets update

        # Group
        # mc admin group add mysb mysb_users "${sAccessKey}"

        # Mark as installed
        if gfnCheckCommand 0 /usr/local/bin/minio; then
            cmdMySQL 'MySB_db' "UPDATE services SET to_install='0',is_installed='1' WHERE serv_name='Minio';" -v
        fi
        ;;
esac

# -----------------------------------------
# shellcheck source=inc/includes_after
source "$(dirname "$0")"/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################
