#!/bin/bash
# ----------------------------------
# shellcheck source=inc/includes_before
source "$(dirname "$0")"/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#	_\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#	 _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#	  _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#	   _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#		_\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#		 _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#		  _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################
# OVH:		https://docs.ovh.com/gb/en/dedicated/monitoring-ip-ovh/
# ONLINE:	https://documentation.online.net/fr/dedicated-server/hardware/monitoring
# HETZNER:	https://wiki.hetzner.de/index.php/System_Monitor_(SysMon)/en
######################################################################

case "${gsServerProvider}" in
    'OVH')
        if [ -f "${MySB_InstallDir}"/temp/monitoring.infos ]; then
            rm -f "${MySB_InstallDir}"/temp/monitoring.infos
        fi

        while [ ! -s "${MySB_InstallDir}"/temp/monitoring.infos ]; do
            tcpdump -v -t host "${gsSrvIpAddress}" | grep 'ICMP' >>"${MySB_InstallDir}"/temp/monitoring.infos &
            sleep 60
            kill $!
        done

        # shellcheck disable=SC2002
        OvhHostnames="$(cat "${MySB_InstallDir}"/temp/monitoring.infos | awk '{print $3}' | grep 'ovh' | sed -e 's/://g;')"
        OvhHostnames="$(echo "${OvhHostnames}" | sed -e 's/^ //g;' | sed 's/\s+$//' | sort | uniq)"
        # To replace with follow ?
        # OvhHostnames="$(grep 'ovh' "${MySB_InstallDir}"/temp/monitoring.infos | awk '{print $3}' | sed -e 's/://g;')"
        # OvhHostnames="$(echo "${OvhHostnames}" | sed -e 's/^ //g;s/\s+$//g;' | sort | uniq)"

        for Hostname in ${OvhHostnames}; do
            IPv4="$(nslookup -type=A "${Hostname}" | grep 'Add' | grep -v '#' | awk -F: '{ print $2 }' | sed -e 's/^ //g;')"
            if [ -n "${IPv4}" ]; then
                cmdMySQL 'MySB_db' "INSERT INTO providers_monitoring (provider,ipv4,hostname) VALUES ('OVH','${IPv4}/32','${HostName}');" -v
            fi
        done

        OvhHostnames="$(cmdMySQL 'MySB_db' "SELECT hostname FROM providers_monitoring WHERE provider = 'OVH' and hostname != '';")"
        for Hostname in ${OvhHostnames}; do
            IPv4="$(nslookup -type=A "${Hostname}" | grep 'Add' | grep -v '#' | awk -F: '{ print $2 }' | sed -e 's/^ //g;')"
            if [ -n "${IPv4}" ]; then
                cmdMySQL 'MySB_db' "UPDATE providers_monitoring SET ipv4 = '${IPv4}/32' WHERE provider = 'OVH' AND hostname = '${Hostname}';" -v
            fi
        done

        # RTM (IP.251)
        OvhRtmIp=""
        for ((i = 1; i <= 4; i += 1)); do
            case "${i}" in
                1) OvhRtmIp="$(echo "${gsSrvIpAddress}" | cut -d '.' -f 1)" ;;
                2 | 3) OvhRtmIp="${OvhRtmIp}.$(echo "${gsSrvIpAddress}" | cut -d '.' -f ${i})" ;;
                4) OvhRtmIp="${OvhRtmIp}.251" ;;
            esac
        done
        HostName="$(nslookup -type=A "${OvhRtmIp}" | grep 'name =' | awk '{ print $4 }' | sed 's/.\{1\}$//g')"
        cmdMySQL 'MySB_db' "INSERT INTO providers_monitoring (provider,ipv4,hostname) VALUES ('OVH','${OvhRtmIp}/32','${HostName}');" -v

        # SLA (IP.250)
        OvhSlaIp=""
        for ((i = 1; i <= 4; i += 1)); do
            case "${i}" in
                1) OvhSlaIp="$(echo "${gsSrvIpAddress}" | cut -d '.' -f 1)" ;;
                2 | 3) OvhSlaIp="${OvhSlaIp}.$(echo "${gsSrvIpAddress}" | cut -d '.' -f ${i})" ;;
                4) OvhSlaIp="${OvhSlaIp}.250" ;;
            esac
        done
        HostName="$(nslookup -type=A "${OvhSlaIp}" | grep 'name =' | awk '{ print $4 }' | sed 's/.\{1\}$//g')"
        cmdMySQL 'MySB_db' "INSERT INTO providers_monitoring (provider,ipv4,hostname) VALUES ('OVH','${OvhSlaIp}/32','${HostName}');" -v

        # Server HG (IP.249)
        OvhHgIp=""
        for ((i = 1; i <= 4; i += 1)); do
            case "${i}" in
                1) OvhHgIp="$(echo "${gsSrvIpAddress}" | cut -d '.' -f 1)" ;;
                2 | 3) OvhHgIp="${OvhHgIp}.$(echo "${gsSrvIpAddress}" | cut -d '.' -f ${i})" ;;
                4) OvhHgIp="${OvhHgIp}.249" ;;
            esac
        done
        HostName="$(nslookup -type=A "${OvhHgIp}" | grep 'name =' | awk '{ print $4 }' | sed 's/.\{1\}$//g')"
        cmdMySQL 'MySB_db' "INSERT INTO providers_monitoring (provider,ipv4,hostname) VALUES ('OVH','${OvhHgIp}/32','${HostName}');" -v
        ;;
    'HETZNER')
        # Delete all Hetzner IPs
        cmdMySQL 'MySB_db' "DELETE FROM providers_monitoring WHERE provider='HETZNER';" -v
        # Get all IPs of Hetzner Server Monitoring
        sHetznerIPv4="$(dig +short pool.sysmon.hetzner.com)"
        # Add IPs listing
        if [ -n "${sHetznerIPv4}" ]; then
            for sIPv4 in ${sHetznerIPv4}; do
                # Get IP's hostname
                HostName="$(nslookup -type=A "${sIPv4}" | grep 'name =' | awk '{ print $4 }' | sed 's/.\{1\}$//g')"
                cmdMySQL 'MySB_db' "INSERT INTO providers_monitoring (provider,ipv4,hostname) VALUES ('HETZNER','${sIPv4}/32','${HostName}');" -v
            done
        fi
        ;;
esac

# -----------------------------------------
# shellcheck source=inc/includes_after
source "$(dirname "$0")"/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################
