#!/bin/bash
# ----------------------------------
source $(dirname $0)/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### Install packages
PackagesManage install "mysql-server"

#### MySQL Secure
if [ -z $MySQL_RootPassword ] && [ -z $MySQL_MysbPassword ]; then
	MySQL_RootPassword="`GenPassword 16`"
	MySQL_MysbPassword="`GenPassword 8`"

	mysql -u root <<-EOF
	UPDATE mysql.user SET Password=PASSWORD('$RootPassword') WHERE User='root';
	DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
	DELETE FROM mysql.user WHERE User='';
	DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%';
	create database MySB_db;
	create user MySB_user;
	grant all on MySB_db.* to 'MySB_user'@'localhost' identified by '$MysbPassword';
	FLUSH PRIVILEGES;
	EOF

	# Add MySQL password into MySB config files
	echo "MySQL_RootPassword=\"$MySQL_RootPassword\"" >> /etc/MySB/config
	echo "MySQL_MysbPassword=\"$MySQL_MysbPassword\"" >> /etc/MySB/config
	NumLign=$(cat /etc/MySB/config.php | grep 'MySB_DB' -n -m 1 | cut -d ':' -f 1)
	(( NumLign-- ))
	sed -i ""$NumLign"i\define('MySQL_MysbPassword', '$MySQL_MysbPassword');" /etc/MySB/config.php
	sed -i ""$NumLign"i\define('MySQL_RootPassword', '$MySQL_RootPassword');" /etc/MySB/config.php
fi

if [ "$1" == "UPGRADE" ] && CheckCommand 0 mysql; then
	sqlite3 $MySB_DB .dump > $MySB_DB.dump
	cat $MySB_DB.dump | python $MySB_InstallDir/scripts/SQLiteToMySQL.py > $MySB_InstallDir/temp/MySB_MySQL.sql
	perl -pi -e "s/ ON CONFLICT ABORT//g" $MySB_InstallDir/temp/MySB_MySQL.sql
	perl -pi -e "s/ ON CONFLICT IGNORE//g" $MySB_InstallDir/temp/MySB_MySQL.sql
	perl -pi -e "s/BOOLEAN \(1\)/TINYINT \(1\)/g" $MySB_InstallDir/temp/MySB_MySQL.sql
	mysql -u MySB_user -p$MySQL_MysbPassword --database=MySB_db < $MySB_InstallDir/temp/MySB_MySQL.sql
fi

#### START services
ManageServices start "mysql"

# -----------------------------------------
source $(dirname $0)/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################