#!/bin/bash
# ----------------------------------
# shellcheck source=inc/includes_before
source "$(dirname "$0")"/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#	_\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#	 _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#	  _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#	   _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#		_\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#		 _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#		  _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
######################################################################
# https://wiki.debian-fr.xyz/Partage_NFS
# https://www.cyberciti.biz/faq/nfs4-server-debian-ubuntu-linux/
# https://help.ubuntu.com/community/NFSv4Howto
##################### FIRST LINE #####################################

if [ "${gbToInstall_NFS}" == "YES" ]; then
    #### install
    gfnPackageBundleInstall 'nfs-kernel-server'

    #### STOP services
    gfnManageServices stop "nfs-kernel-server"

    #### Disable IPv6
    perl -pi -e "s/^udp6/#udp6/g" /etc/netconfig
    perl -pi -e "s/^tcp6/#tcp6/g" /etc/netconfig

    #### /export directory
    [ ! -d /export ] && mkdir /export

    #### nfs-common
    install -v -o root -g root -m 0644 "${MySB_InstallDir}"/templates/nfs/etc.default.nfs-common.tmpl /etc/default/nfs-common

    #### nfs-kernel-server
    install -v -o root -g root -m 0644 "${MySB_InstallDir}"/templates/nfs/etc.default.nfs-kernel-server.tmpl /etc/default/nfs-kernel-server

    #### Systemd
    install -v -o root -g root -m 0644 "${MySB_InstallDir}"/templates/nfs/rpcbind.service.tmpl /lib/systemd/system/rpcbind.service
    systemctl disable rpcbind.service
    systemctl disable nfs-kernel-server.service
    systemctl daemon-reload

    #### Sysctl
    {
        echo "fs.nfs.nlm_tcpport=32768"
        echo "fs.nfs.nlm_udpport=32768"
    } >/etc/sysctl.d/999-nfs.conf
    sysctl --system

    if gfnCheckCommand 0 nfs-kernel-server; then
        cmdMySQL 'MySB_db' "UPDATE services SET to_install = '0', is_installed = '1' WHERE serv_name='NFS';" -v
    fi

    #### START services
    gfnManageServices start "nfs-kernel-server"
fi

# -----------------------------------------
# shellcheck source=inc/includes_after
source "$(dirname "$0")"/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################
