#!/bin/bash 
# ----------------------------------
source /etc/MySB/inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___        
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_       
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_      
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__     
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_    
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_   
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_  
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__ 
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################
#
# Usage:	OpenVPN$CEND {server|client <username>|zip <username> <user_passwaord>}
#
##################### FIRST LINE #####################################

if [ "$USAGE" == "ON" ]; then
	# if [ ! -z $IFPVEKERNEL ]; then
		# echo -e "${CRED}It seems that your system is an OpenVZ container.$CEND"
		# echo -e "${CRED}This script is currently unavailable.$CEND"
		# exit
	# fi
	if [ -z $1 ]; then
		echo -e "${CBLUE}Usage:$CEND	${CYELLOW}OpenVPN$CEND ${CGREEN}{server|client <username>|zip <username> <user_passwaord>} $CEND"
		exit
	fi		
fi

# if [ ! "`ps aux | grep /bin/bash | grep MySB_Install.sh`" = "" ] && [ "`screen -ls | grep MySB_CreateUser`" == "" ]; then
	# COMMAND="server"
# elif [ ! "`ps aux | grep MySB_Install.sh`" = "" ] && [ ! "`screen -ls | grep MySB_CreateUser`" = "" ]; then
	# COMMAND="client"
# else
	# COMMAND=$1
# fi

#### Var
COMMAND=$1
USERNAME=$2
USERPASSWORD=$3
SERVERNAME="server_$HOSTFQDN"
CLIENTNAME="client_${USERNAME}@$HOSTFQDN"
TAKEY="ta_$HOSTFQDN.key"
CACRT="ca_$HOSTFQDN.crt"
CAKEY="ca_$HOSTFQDN.key"
CRT="$SERVERNAME.crt"
CSR="$SERVERNAME.csr"
KEY="$SERVERNAME.key"
DH="dh1024_$HOSTFQDN.pem"

CreateServer() {
	#### install package
	PackagesManage install "openvpn"
	
	#### Files and Directory
	if [ ! -d /var/log/openvpn ]; then
		mkdir -p /var/log/openvpn
	fi
	if [ ! -d /etc/openvpn/clients ]; then
		mkdir -p /etc/openvpn/clients
	fi
	if [ ! -d /etc/openvpn/clients_config_dir ]; then
		mkdir -p /etc/openvpn/clients_config_dir
	fi	
	if [ ! -f /var/log/openvpn.log ]; then
		touch /var/log/openvpn/openvpn.log
	fi
	if [ ! -f /var/log/openvpn/openvpn-status.log ]; then
		touch /var/log/openvpn/openvpn-status.log
	fi
	if [ ! -d /etc/MySB/web/openvpn ]; then
		mkdir -p /etc/MySB/web/openvpn
	fi	
	if [ ! -d /etc/openvpn/easy-rsa ]; then
		mkdir -p /etc/openvpn/easy-rsa
		cp -r /usr/share/doc/openvpn/examples/easy-rsa/2.0/* /etc/openvpn/easy-rsa/
		chown -R $USER /etc/openvpn/easy-rsa/		
	fi		
	
	#### Initialize
	cd /etc/openvpn/easy-rsa/
	. ./vars
	export KEY_COUNTRY="US"
	export KEY_PROVINCE="CA"
	export KEY_CITY="SanFrancisco"
	export KEY_ORG="Fort-Funston"
	export KEY_EMAIL="MySB@$HOSTFQDN"
	export KEY_CN="MySB OpenVPN Server"
	export KEY_NAME="MySB OpenVPN Server"
	export KEY_OU="MySB OpenVPN Server"
	
	#### Create server
	./clean-all
	./build-dh
	./pkitool --initca
	./pkitool --server $SERVERNAME	
	/usr/sbin/openvpn --genkey --secret keys/ta.key

	#### Move created files
	cp keys/dh1024.pem /etc/openvpn/$DH
	cp keys/ca.crt /etc/openvpn/$CACRT
	cp keys/ca.key /etc/openvpn/$CAKEY
	cp keys/ta.key /etc/openvpn/$TAKEY
	mv keys/$CRT /etc/openvpn/
	mv keys/$KEY /etc/openvpn/
	
	#### Config file Server1 - routed IP tunnel (TUN)
	# start with a clean config file for a new user
	if [ -f /etc/openvpn/server1_tun.conf ]; then
		rm -f /etc/openvpn/server1_tun.conf
	fi	
	cp /etc/MySB/templates/openvpn.server.conf.template /etc/openvpn/server1_tun.conf
	# adapt this file
	sed -i "s/<PORT>/$OPENVPNPORT/g" /etc/openvpn/server1_tun.conf
	sed -i "s/<PROTO>/$OPENVPNPROTO/g" /etc/openvpn/server1_tun.conf
	sed -i "s/<TAKEY>/$TAKEY/g" /etc/openvpn/server1_tun.conf
	sed -i "s/<CA>/$CACRT/g" /etc/openvpn/server1_tun.conf
	sed -i "s/<CERT>/$CRT/g" /etc/openvpn/server1_tun.conf
	sed -i "s/<KEY>/$KEY/g" /etc/openvpn/server1_tun.conf
	sed -i "s/<DH>/$DH/g" /etc/openvpn/server1_tun.conf
	sed -i "s/;push \"dhcp-option DNS 8.8.4.4\"/push \"dhcp-option DNS 8.8.4.4\"/g" /etc/openvpn/server1_tun.conf	
	sed -i "s/;push \"dhcp-option DNS 8.8.8.8\"/push \"dhcp-option DNS 8.8.8.8\"/g" /etc/openvpn/server1_tun.conf	
	sed -i "s/;push \"redirect-gateway\"/push \"redirect-gateway\"/g" /etc/openvpn/server1_tun.conf	
	# and clean it (delete comments, delete unused option, delete blank line)
	sed -i '/#/d' /etc/openvpn/server1_tun.conf
	sed -i '/^;/d' /etc/openvpn/server1_tun.conf
	sed -i '/^$/d' /etc/openvpn/server1_tun.conf
	
	#### For network
	echo 1 > /proc/sys/net/ipv4/ip_forward
	perl -pi -e "s/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g" /etc/sysctl.conf	
}

CreateClient() {
	#### Initialize
	cd /etc/openvpn/easy-rsa/
	. ./vars
	export KEY_COUNTRY="US"
	export KEY_PROVINCE="CA"
	export KEY_CITY="SanFrancisco"
	export KEY_ORG="Fort-Funston"
	export KEY_EMAIL="MySB@$HOSTFQDN"
	export KEY_CN="MySB OpenVPN Client - $USERNAME"
	export KEY_NAME="MySB OpenVPN Client - $USERNAME"
	export KEY_OU="MySB OpenVPN Client - $USERNAME"
	
	#### Create client
	./pkitool $CLIENTNAME
	cd keys/

	#### Configuration file with separate files - routed IP tunnel (TUN)
	# start with a clean config file for a new user
	if [ -f /etc/openvpn/clients/${CLIENTNAME}_TUN.ovpn ]; then
		rm -f /etc/openvpn/clients/${CLIENTNAME}_TUN.ovpn
	fi	
	cp /etc/MySB/templates/openvpn.client.conf.template /etc/openvpn/clients/${CLIENTNAME}_TUN.ovpn
	# adapt this file
	sed -i "s/<PROTO>/$OPENVPNPROTO/g" /etc/openvpn/clients/${CLIENTNAME}_TUN.ovpn
	sed -i "s/<IPADDRESS>/$IPADDRESS/g" /etc/openvpn/clients/${CLIENTNAME}_TUN.ovpn	
	sed -i "s/<PORT>/$OPENVPNPORT/g" /etc/openvpn/clients/${CLIENTNAME}_TUN.ovpn
	sed -i "s/;ca ca.crt/ca $CACRT/g" /etc/openvpn/clients/${CLIENTNAME}_TUN.ovpn
	sed -i "s/;cert client.crt/cert $CLIENTNAME.crt/g" /etc/openvpn/clients/${CLIENTNAME}_TUN.ovpn
	sed -i "s/;key client.key/key $CLIENTNAME.key/g" /etc/openvpn/clients/${CLIENTNAME}_TUN.ovpn
	sed -i "s/;tls-auth ta.key 1/tls-auth $TAKEY 1/g" /etc/openvpn/clients/${CLIENTNAME}_TUN.ovpn
	# and clean it (delete comments, delete unused option, delete blank line)
	sed -i '/#/d' /etc/openvpn/clients/${CLIENTNAME}_TUN.ovpn
	sed -i '/^;/d' /etc/openvpn/clients/${CLIENTNAME}_TUN.ovpn
	sed -i '/^$/d' /etc/openvpn/clients/${CLIENTNAME}_TUN.ovpn
	
	#### Single configuration file (all in one) - routed IP tunnel (TUN)
	# start with a clean config file for a new user	
	if [ -f /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn ]; then
		rm -f /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn
	fi	
	cp /etc/MySB/templates/openvpn.client.conf.template /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn
	# adapt this file
	sed -i "s/<PROTO>/$OPENVPNPROTO/g" /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn
	sed -i "s/<IPADDRESS>/$IPADDRESS/g" /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn	
	sed -i "s/<PORT>/$OPENVPNPORT/g" /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn
	# and clean it (delete comments, delete unused option, delete blank line)
	sed -i '/#/d' /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn
	sed -i '/^;/d' /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn
	sed -i '/^$/d' /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn
	# add options in case
	echo "# Uncomment this option for username/password prompt" >> /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn
	echo ";auth-user-pass" >> /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn	
	# add certificate info in file config	
	echo "" >> /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn
	echo "<ca>" >> /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn
	cat /etc/openvpn/$CACRT >> /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn
	echo "</ca>" >> /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn
	echo "<cert>" >> /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn
	sed -n '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/p' $CLIENTNAME.crt >> /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn
	echo "</cert>" >> /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn
	echo "<key>" >> /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn	
	cat $CLIENTNAME.key >> /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn
	echo "</key>" >> /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn	
	echo "key-direction 1" >> /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn
	echo "<tls-auth>" >> /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn
	sed -n '/-----BEGIN OpenVPN Static key V1-----/,/-----END OpenVPN Static key V1-----/p' /etc/openvpn/$TAKEY >> /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn
	echo "</tls-auth>" >> /etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn		
	
	#### Move created files
	mv $CLIENTNAME.crt /etc/openvpn/clients/
	mv $CLIENTNAME.csr /etc/openvpn/clients/
	mv $CLIENTNAME.key /etc/openvpn/clients/
	chmod 400 /etc/openvpn/clients/*
}

ZipClientFiles() {
	if [ -f /etc/MySB/web/openvpn/openvpn_$USERNAME.zip ]; then
		rm -f /etc/MySB/web/openvpn/openvpn_$USERNAME.zip
	fi	
	zip -P "$USERPASSWORD" -j /etc/MySB/web/openvpn/openvpn_$USERNAME.zip\
		/etc/openvpn/clients/${CLIENTNAME}_single_TUN.ovpn\
		/etc/openvpn/clients/${CLIENTNAME}_TUN.ovpn\
		/etc/openvpn/$CACRT\
		/etc/openvpn/clients/$CLIENTNAME.crt\
		/etc/openvpn/clients/$CLIENTNAME.key\
		/etc/openvpn/$TAKEY
}

case "$COMMAND" in
	"server")
		#### Creating server config
		CreateServer
	;;
	"client")
		#### Creating user config
		if [ ! -z $USERNAME ]; then
			CreateClient
		fi
	;;
	"zip")
		#### ZIP user config files
		if [ ! -z $USERNAME ] && [ ! -z $USERPASSWORD ]; then
			ZipClientFiles
		fi
	;;	
	*)
		echo -e "${CBLUE}Usage:$CEND	${CYELLOW}bash /etc/MySB/install/OpenVPN$CEND ${CGREEN}{server|client <username>|zip <username> <user_passwaord>}$CEND"
		exit	
	;;	
esac

# -----------------------------------------
source /etc/MySB/inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################