#!/bin/bash
# ----------------------------------
source $(dirname $0)/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### Packages list
MySB_Install_Packages="`grep -rni 'TOOLS=' $MySB_InstallDir/install/MySB_Install.bsh | cut -d '"' -f 2`"
PackagesList_Standard="sudo htop build-essential automake libtool manpages-fr pkg-config curl unzip zip iperf csvtool whois vim nano ntpdate ntp update-notifier-common debian-goodies bridge-utils libxml2-dev libsigc++-2.0-dev libncurses5-dev libxmlrpc-c3-dev libcppunit-dev gnupg-curl python debianutils coreutils mailutils bc tcpdump bash-completion libcurl4-openssl-dev expect rsyslog lftp cksfv libav-tools idn pcregrep valgrind pslib1 libio-socket-ssl-perl libhttp-daemon-ssl-perl libsmbclient-dev tcl8.5 redis-server"

if ! CheckCommand 0 rar; then
	PackagesManage install "rar"
	if [ $? -gt 0 ]; then
		PackagesList_Standard="$PackagesList_Standard rar-free"
	fi
fi

if ! CheckCommand 0 unrar; then
	PackagesManage install "unrar"
	if [ $? -gt 0 ]; then
		PackagesList_Standard="$PackagesList_Standard unrar-free"
	fi
fi

#### Install packages (standard)
PackagesManage install "$MySB_Install_Packages $PackagesList_Standard"

#### Install packages (Backports)
PackagesManage install "subversion" "backports"

#### Purge packages
PackagesManage purge "heirloom-mailx"

# -----------------------------------------
source $(dirname $0)/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################