#!/bin/bash
# ----------------------------------
# shellcheck source=inc/includes_before
source "$(dirname "$0")"/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#	_\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#	 _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#	  _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#	   _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#		_\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#		 _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#		  _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### Packages list
MySB_Install_Packages="$(grep -rni 'TOOLS=' "${MySB_InstallDir}"/install/MySB_Install.bsh | awk -F'[(|)]' '{print $2}')"
PackagesList_Compress=(rar unrar unzip zip)
PackagesList_Tools=(htop iotop iperf csvtool whois vim nano tcpdump sysbench curl jq ssl-cert openssl fatrace)
PackagesList_Compil=(cmake build-essential autogen autoconf autoconf-archive automake pkg-config)
PackagesList_Utils=(bridge-utils debianutils coreutils mailutils cpufrequtils apache2-utils xz-utils ethtool)
PackagesList_ToPurge=(heirloom-mailx ntp minissdpd)
PackagesList_Standard=(sudo manpages-fr ntpdate debian-goodies bc bash-completion expect rsyslog lftp cksfv idn pcregrep valgrind pslib1 tcl8.5 whiptail python3 python3-pip python-pip apt-transport-https ca-certificates gnupg2 software-properties-common apt-config-auto-update bash-static)
PackagesList_Lib=(libtool libxml2-dev libsigc++-2.0-dev libncurses5-dev libcppunit-dev libcurl4-openssl-dev libio-socket-ssl-perl libsmbclient-dev zlib1g-dev libssl-dev libsystemd-dev)
PackagesList_Backports=(subversion libav-tools)

# For update of sources list
cmdMySQL 'MySB_db' "UPDATE system SET apt_update = 1, apt_date = '$(date +%Y-%m-%d\ %H:%M:%S)' WHERE id_system='1';" -v

#### Force install for depends
gfnPackagesManage install

#### Install packages (standard)
aAllPackages=("${MySB_Install_Packages[@]}" "${PackagesList_Standard[@]}" "${PackagesList_Compress[@]}" "${PackagesList_Tools[@]}" "${PackagesList_Compil[@]}" "${PackagesList_Utils[@]}" "${PackagesList_Lib[@]}")
gfnPackagesManage install "${aAllPackages[@]}"

#### Install packages (Backports)
aAllPackages=("${PackagesList_Backports[@]}")
gfnPackagesManage install "backports" "${aAllPackages[@]}"

#### Purge packages
aAllPackages=("${PackagesList_ToPurge[@]}")
gfnPackagesManage purge "${aAllPackages[@]}"

# -----------------------------------------
# shellcheck source=inc/includes_after
source "$(dirname "$0")"/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################
