#!/bin/bash
# ----------------------------------
source $(dirname $0)/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### Install packages
PackagesManage install "php5 php5-cli php5-fpm php5-curl php5-geoip php5-xmlrpc php5-gd php5-sqlite php5-mcrypt php5-json php5-mysql php5-intl php5-imagick php-xml-rss php5-apcu"

#### STOP services
ManageServices stop "php5-fpm"

#### Merge new config files
if [ -f /etc/php5/fpm/pool.d/www.conf.dpkg-dist ]; then mv -v /etc/php5/fpm/pool.d/www.conf.dpkg-dist /etc/php5/fpm/pool.d/www.conf; fi
if [ -f /etc/php5/fpm/php.ini.ucf-dist ]; then mv -v /etc/php5/fpm/php.ini.ucf-dist /etc/php5/fpm/php.ini; fi
if [ -f /etc/php5/cli/php.ini.ucf-dist ]; then mv -v /etc/php5/cli/php.ini.ucf-dist /etc/php5/cli/php.ini; fi

perl -pi -e "s/;listen = 127.0.0.1:9000/listen = \/var\/run\/php5-fpm.sock/g" /etc/php5/fpm/pool.d/www.conf
perl -pi -e "s/^;listen.owner = www-data/listen.owner = www-data/g" /etc/php5/fpm/pool.d/www.conf
perl -pi -e "s/^;listen.group = www-data/listen.group = www-data/g" /etc/php5/fpm/pool.d/www.conf
perl -pi -e "s/^;listen.mode = 0660/listen.mode = 0660/g" /etc/php5/fpm/pool.d/www.conf
perl -pi -e "s/^;request_terminate_timeout = 0/request_terminate_timeout = 300/g" /etc/php5/fpm/pool.d/www.conf
perl -pi -e "s/^expose_php = On/expose_php = Off/g" /etc/php5/fpm/php.ini
perl -pi -e "s/file_uploads = Off/file_uploads = On/g" /etc/php5/fpm/php.ini
perl -pi -e "s/post_max_size = 8M/post_max_size = 10M/g" /etc/php5/fpm/php.ini
perl -pi -e "s/upload_max_filesize = 2M/upload_max_filesize = 10M/g" /etc/php5/fpm/php.ini
perl -pi -e "s/^;date.timezone =/date.timezone = Europe\/Paris/g" /etc/php5/fpm/php.ini
perl -pi -e "s/^expose_php = On/expose_php = Off/g" /etc/php5/cli/php.ini
perl -pi -e "s/^;date.timezone =/date.timezone = Europe\/Paris/g" /etc/php5/cli/php.ini

ScriptInvoke 'source' "$MySB_InstallDir/scripts/UpdateGeoIP.bsh" "INSTALL"

#### START services
ManageServices start "php5-fpm"

# -----------------------------------------
source $(dirname $0)/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################