#!/bin/bash
# ----------------------------------
# shellcheck source=inc/includes_before
source "$(dirname "$0")"/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#	_\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#	 _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#	  _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#	   _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#		_\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#		 _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#		  _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### STOP services
gfnManageServices stop "nginx ${binPhpService} redis-server"

#### Redis
install -v -o root -g root -m 0755 -d "/etc/redis"
install -v -o root -g root -m 0777 ${MySB_InstallDir}/templates/php/etc.redis.redis.conf.tmpl /etc/redis/redis.conf
{
    echo "net.core.somaxconn=1024"
    echo "vm.overcommit_memory=1"
} >/etc/sysctl.d/999-redis.conf
sysctl --system

#### Install packages
sPeclModules="smbclient"
sDebModulesWithPecl=""
# gfnPackagesManage purge "$sDebModulesWithPecl"
sPackages=(redis-server php7.1-common php7.1-cli php7.1-fpm php7.1-imagick php7.1-dev php7.1-curl php7.1-gd php7.1-gmp php7.1-imap php7.1-intl php7.1-json php7.1-mcrypt php7.1-mysql php7.1-readline php7.1-sqlite3 php7.1-xmlrpc php7.1-msgpack php7.1-geoip php7.1-redis php7.1-xml php7.1-zip php7.1-mbstring php7.1-smbclient php-pear libgeoip-dev "$sDebModulesWithPecl")
gfnPackageBundleInstall "${sPackages[@]}"
gfnPackagesManage purge "apache2"

#### Reload new vars
# shellcheck source=/dev/null
source "${MySB_InstallDir}"/inc/vars

#### STOP services
gfnManageServices stop "nginx ${binPhpService} redis-server"

#### Redis
install -v -o root -g root -m 0755 -d "/etc/redis"
install -v -o redis -g redis -m 0640 ${MySB_InstallDir}/templates/php/etc.redis.redis.conf.tmpl /etc/redis/redis.conf

#### Configuration files
# ${gsPhpDir}/fpm/php-fpm.conf
install -v -o root -g root -m 0644 ${MySB_InstallDir}/templates/php/etc.php.7.1.fpm.php-fpm.conf.tmpl ${gsPhpDir}/fpm/php-fpm.conf
# ${gsPhpDir}/fpm/pool.d/www.conf
install -v -o root -g root -m 0644 ${MySB_InstallDir}/templates/php/etc.php.7.1.fpm.pool.d.www.conf.tmpl ${gsPhpDir}/fpm/pool.d/www.conf
# ${gsPhpDir}/fpm/php.ini
install -v -o root -g root -m 0644 ${MySB_InstallDir}/templates/php/etc.php.7.1.php.ini.tmpl ${gsPhpDir}/fpm/php.ini
# ${gsPhpDir}/cli/php.ini
install -v -o root -g root -m 0644 ${MySB_InstallDir}/templates/php/etc.php.7.1.php.ini.tmpl ${gsPhpDir}/cli/php.ini
perl -pi -e "s/disable_functions = /;disable_functions = /g" ${gsPhpDir}/cli/php.ini

#### Modules inventory
sExtDir="/usr/lib/php/20151012"
sAllExtList="$(echo ${sAllExtList} | xargs -n1 | sort -u | xargs | sed -e 's/^ //g;' | sed 's/\s+$//')"

#### PEAR/PECL config
update-ca-certificates --verbose --fresh &>/dev/null
pear config-set auto_discover 1
pear config-set php_ini ${gsPhpDir}/cli/php.ini
pear config-set ext_dir ${sExtDir}
pear update-channels
pear upgrade --force Console_GetoptPlus
pear upgrade --force pear/XML_Util
pear upgrade --force

#### Disable all modules
for Ext in $sPeclModules; do
    [ -f ${gsPhpDir}/mods-available/${Ext}.ini ] && phpdismod ${Ext}
    rm -fv ${gsPhpDir}/mods-available/${Ext}.ini
    [ -n "$(pecl list | grep "${Ext}")" ] && pecl uninstall ${Ext}
done
if [ -d "${sExtDir}-zts" ]; then
    sExtListZts="$(ls -A1 ${sExtDir}-zts | cut -d "." -f 1)"
    for Ext in ${sExtListZts}; do
        [ -f ${gsPhpDir}/mods-available/${Ext}.ini ] && phpdismod ${Ext}
        rm -fv ${gsPhpDir}/mods-available/${Ext}.ini
    done
    rm -rfv ${sExtDir}-zts
fi
for Ext in ${sAllExtList}; do
    [ -f ${sExtDir}/${Ext}.ini ] && phpdismod ${Ext}
    rm -fv ${gsPhpDir}/mods-available/${Ext}.ini
done

#### Enable all modules
for Ext in ${sAllExtList}; do
    case "${Ext}" in
        'opcache')
            echo "zend_extension=opcache.so" >${gsPhpDir}/mods-available/opcache.ini
            [ -z "$(php -m | grep 'opcache')" ] && $binPhpEnmod opcache
            ;;
        *)
            echo "extension=${Ext}.so" >${gsPhpDir}/mods-available/${Ext}.ini
            [ -z "$(php -m | grep "${Ext}")" ] && $binPhpEnmod ${Ext}
            ;;
    esac
done
for Ext in $sPeclModules; do
    case "${Ext}" in
        'smbclient')
            gfnGetRepoValues 'libsmbclient-php' && gfnRepoManageByType
            gfnRepoManageByType
            cd ${gsRepoDir}/ || continue
            phpize
            ./configure
            make
            make install
            make test
            echo "extension=smbclient.so" >${gsPhpDir}/mods-available/smbclient.ini
            $binPhpEnmod smbclient
            ;;
        'htscanner')
            pecl install htscanner
            echo "extension=htscanner.so" >${gsPhpDir}/mods-available/htscanner.ini
            $binPhpEnmod htscanner
            rm -fv ${gsPhpDir}/cli/conf.d/20-htscanner.ini
            ;;
    esac
done
chmod 644 ${sExtDir}/*.so

#### Check modules installation
${binPhpFpm} -i | grep 'htscanner'
echo
${binPhpFpm} -i | grep 'smbclient'

#### TMPFS
sed -i '/\/mnt\/tmpFS\/php/d' /etc/fstab
echo "# /mnt/tmpFS/php" >>/etc/fstab
echo "tmpfs /mnt/tmpFS/php tmpfs defaults,nosuid,noatime,mode=1777,size=32M 0 0" >>/etc/fstab
[ ! -d /mnt/tmpFS/php ] && mkdir -pv /mnt/tmpFS/php
[[ -z $(df -H | grep '/mnt/tmpFS/php') ]] && mount /mnt/tmpFS/php

#### GeoIP update
if gfnCheckCommand 0 geoipupdate; then geoipupdate; fi

#### START services
gfnManageServices start "redis-server ${binPhpService} nginx"

#### Composer
gfnGetRepoValues 'Composer'
gfnRepoManageByType
if [ "$gsVersionInstalled" != "$gsVersionLatest" ]; then
    gfnRepoManageByType
    chmod -v +x ${gsRepoDir}
    ${gsRepoDir} --version | grep 'Composer version'
fi
composer self-update

# -----------------------------------------
# shellcheck source=inc/includes_after
source "$(dirname "$0")"/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################
