#!/bin/bash
# ----------------------------------
source $(dirname $0)/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### VARs
Type="$1"

#### Install packages
if ! CheckCommand 0 postfix; then
	PackagesManage install "postfix"
fi

#### STOP services
#ManageServices stop "postfix"

#### Create certificates
if [ ! -f $MySB_InstallDir/ssl/postfix.cert ]; then
	ScriptInvoke 'source' "$MySB_InstallDir/install/Certificates" 'CreateServiceCertificate' 'postfix'
fi

if [ "$SMTP_Provider" != "LOCAL" ]; then
	#### Install packages
	if ! CheckCommand 0 stunnel4; then
		PackagesManage install "stunnel4 gnutls-bin"
	fi

	#### STOP services
	#ManageServices stop "stunnel4"	
	
	#### Create certificates
	if [ ! -f $MySB_InstallDir/ssl/stunnel.cert ]; then
		ScriptInvoke 'source' "$MySB_InstallDir/install/Certificates" 'CreateServiceCertificate' 'stunnel'
	fi

	#### stunnel
	if [ -f /var/log/stunnel4/stunnel.log ] && [ ! -h /var/log/stunnel4/stunnel.log ]; then
		rm -vf /var/log/stunnel4/stunnel.log
	fi
	if [ ! -f /var/lib/stunnel4/stunnel.log ]; then
		touch /var/lib/stunnel4/stunnel.log
		chmod 640 /var/lib/stunnel4/stunnel.log
		chown stunnel4:stunnel4 /var/lib/stunnel4/stunnel.log
	fi
	if [ ! -h /var/log/stunnel4/stunnel.log ]; then
		ln -s /var/lib/stunnel4/stunnel.log /var/log/stunnel4/stunnel.log
	fi
fi

#### main.cf
cp $MySB_InstallDir/templates/etc.postfix.main.conf.template /etc/postfix/main.cf
perl -pi -e "s/<hostname>/$HostNameFQDN/g" /etc/postfix/main.cf
perl -pi -e "s/<domain>/$(hostname -d)/g" /etc/postfix/main.cf
echo "$HostNameFQDN" > /etc/mailname

#### Alias
echo "# /etc/aliases" > /etc/aliases
echo "mailer-daemon: postmaster" >> /etc/aliases
echo "postmaster: root" >> /etc/aliases
echo "nobody: root" >> /etc/aliases
echo "hostmaster: root" >> /etc/aliases
echo "usenet: root" >> /etc/aliases
echo "news: root" >> /etc/aliases
echo "webmaster: root" >> /etc/aliases
echo "www: root" >> /etc/aliases
echo "ftp: root" >> /etc/aliases
echo "abuse: root" >> /etc/aliases
echo "noc: root" >> /etc/aliases
echo "security: root" >> /etc/aliases
echo "root: $MainUserEmail" >> /etc/aliases
newaliases

SMTP_Host="localhost"
SMTP_Port="25"
Smtp_Security="NOSSL"
postconf -e "relayhost = "

#### Only by choise of user
if [ "$SMTP_Provider" != "LOCAL" ]; then
	postconf -e "smtp_host_lookup = dns, native"
	postconf -e "default_transport = smtp"

	# Correcting SSL vulnerability (poodle)
	postconf -e 'smtpd_tls_mandatory_protocols=!SSLv1,!SSLv2,!SSLv3'
	postconf -e 'smtpd_tls_protocols=!SSLv1,!SSLv2,!SSLv3'
	postconf -e 'smtp_tls_protocols=!SSLv1,!SSLv2,!SSLv3'

	case "$SMTP_Provider" in
		"FREE")
			SMTP_Host="smtp.free.fr"
			SMTP_Port=465
			Smtp_Security=SSL
		;;
		"YAHOO")
			SMTP_Host="smtp.mail.yahoo.fr"
			SMTP_Port=465
			Smtp_Security=SSL
		;;
		"OVH")
			SMTP_Host="ssl0.ovh.net"
			SMTP_Port=465
			Smtp_Security=SSL
		;;
		"GMAIL")
			SMTP_Host="smtp.gmail.com"
			SMTP_Port=465
			Smtp_Security=SSL
		;;
	esac

	case "$Smtp_Security" in
		"SSL")
			# stunnel.conf
			cp $MySB_InstallDir/templates/etc.stunnel.stunnel.conf.template /etc/stunnel/stunnel.conf
			perl -pi -e "s/<InstallDir>/$MySB_InstallDirEscaped/g" /etc/stunnel/stunnel.conf
			perl -pi -e "s/<smtp_host>:<smtp_port>/$SMTP_Host:$SMTP_Port/g" /etc/stunnel/stunnel.conf
			perl -pi -e "s/ENABLED=0/ENABLED=1/g" /etc/default/stunnel4
			echo "127.0.0.1:23000              $SMTP_Username:$SMTP_Password" > /etc/postfix/sasl/sasl_passwd
			postconf -e "relayhost = 127.0.0.1:23000"
			postconf -e "smtp_sasl_auth_enable = yes"
			postconf -e "smtp_sasl_security_options = noanonymous"
			postconf -e "smtp_sasl_password_maps = hash:/etc/postfix/sasl/sasl_passwd"
			postconf -e "smtp_sasl_mechanism_filter = plain"
			postconf -e "smtp_tls_security_level = may"	
		;;
		"TLS")
			perl -pi -e "s/ENABLED=1/ENABLED=0/g" /etc/default/stunnel4
			postconf -e "smtp_sasl_auth_enable = yes"
			postconf -e "smtp_sasl_security_options = noanonymous"
			postconf -e "smtp_sasl_password_maps = hash:/etc/postfix/sasl/sasl_passwd"
			postconf -e "smtp_sasl_mechanism_filter = plain"
			postconf -e "relayhost = $SMTP_Host:$SMTP_Port"
			postconf -e "tls_random_source = dev:/dev/urandom"
			postconf -e "smtp_use_tls = yes"
			postconf -e "smtp_tls_note_starttls_offer = yes"
			postconf -e "smtp_tls_security_level = may"	
			postconf -e "smtp_sasl_tls_security_options = noanonymous"
			postconf -e "smtp_tls_scert_verifydepth = 5"
			postconf -e "smtp_tls_enforce_peername = no"
			postconf -e "smtp_tls_session_cache_database = btree:\${data_directory}/smtp_scache"
			postconf -e "smtp_tls_cert_file = $MySB_InstallDir/ssl/postfix.cert"
			postconf -e "smtp_tls_key_file = $MySB_InstallDir/ssl/postfix.key"	
			postconf -e "smtp_tls_policy_maps = hash:/etc/postfix/tls_policy"
			postconf -e "smtp_tls_CAfile = $MySB_InstallDir/ssl/CA/certs/cacert.pem"
		;;
	esac

	postmap /etc/postfix/sasl/sasl_passwd
	
	#### START services
	ServicesToRestart="stunnel4"

fi

sqlite3 -cmd '.timeout 150000' $MySB_DB "UPDATE services SET is_installed = '1' WHERE serv_name = 'Postfix';"
sqlite3 -cmd '.timeout 150000' $MySB_DB "UPDATE services SET is_installed = '1' WHERE serv_name = 'Stunnel';"
sqlite3 -cmd '.timeout 150000' $MySB_DB "UPDATE smtp SET smtp_provider = '$SMTP_Provider', smtp_username = '$SMTP_Username', smtp_passwd = '$SMTP_Password', smtp_host = '$SMTP_Host', smtp_port = '$SMTP_Port' WHERE id_smtp = '1';"

#### START services
if [ "$IsInstalled_DNScrypt" == "YES" ]; then
	ServicesToRestart="${ServicesToRestart} bind9 dnscrypt-proxy"
fi
ServicesToRestart="${ServicesToRestart} postfix"
ManageServices start "$ServicesToRestart"

#### Create new security rules
# if [ "$Type" == "INSTALL" ] || [ "$Type" == "UPGRADE" ]; then
	# ScriptInvoke 'source' "$MySB_InstallDir/bin/MySB_SecurityRules" 'create' 'SCREEN'
# fi

#### Add some hosts in cache
if [ "$Type" == "INSTALL" ] || [ "$Type" == "UPGRADE" ]; then
	if [ "$SMTP_Provider" != "LOCAL" ]; then
		ping -c5 $SMTP_Host
	fi
fi

#### Flush mail queue
if CheckCommand 0 postfix; then postfix flush; fi

# -----------------------------------------
source $(dirname $0)/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################