#!/bin/bash 
# ----------------------------------
source /etc/MySB/inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___        
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_       
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_      
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__     
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_    
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_   
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_  
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__ 
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### Install packages
PackagesManage install "postfix stunnel4 gnutls-bin"

#### Create certificates
ScriptInvoke 'source' '/etc/MySB/install/Certificates' 'CreateServiceCertificate' 'postfix'

if [ "$SMTP" != "LOCAL" ]; then
	#### Create certificates
	ScriptInvoke 'source' '/etc/MySB/install/Certificates' 'CreateServiceCertificate' 'stunnel'
	
	#### stunnel
	if [ -f /var/log/stunnel4/stunnel.log ]; then
		rm -f /var/log/stunnel4/stunnel.log
	fi
	if [ ! -f /var/lib/stunnel4/stunnel.log ]; then
		touch /var/lib/stunnel4/stunnel.log
		chmod 640 /var/lib/stunnel4/stunnel.log
		chown stunnel4:stunnel4 /var/lib/stunnel4/stunnel.log
	fi
	ln -s /var/lib/stunnel4/stunnel.log /var/log/stunnel4/stunnel.log	
fi

#### main.cf
cp /etc/MySB/templates/etc.postfix.main.conf.template /etc/postfix/main.cf
perl -pi -e "s/<hostname>/$HOSTNAME/g" /etc/postfix/main.cf
perl -pi -e "s/<domain>/$(hostname -d)/g" /etc/postfix/main.cf
echo "$HOSTNAME" > /etc/mailname

#### Alias
echo "# /etc/aliases" > /etc/aliases
echo "mailer-daemon: postmaster" >> /etc/aliases
echo "postmaster: root" >> /etc/aliases
echo "nobody: root" >> /etc/aliases
echo "hostmaster: root" >> /etc/aliases
echo "usenet: root" >> /etc/aliases
echo "news: root" >> /etc/aliases
echo "webmaster: root" >> /etc/aliases
echo "www: root" >> /etc/aliases
echo "ftp: root" >> /etc/aliases
echo "abuse: root" >> /etc/aliases
echo "noc: root" >> /etc/aliases
echo "security: root" >> /etc/aliases
echo "root: $EMAILUSER" >> /etc/aliases
newaliases

SMTP_HOST="localhost"
SMTP_PORT="25"
SMTP_SECURITY="NOSSL"
postconf -e "relayhost = "

# Correcting SSL vulnerability (poodle)
postconf -e 'smtpd_tls_mandatory_protocols=!SSLv2,!SSLv3'
postconf -e 'smtpd_tls_protocols=!SSLv2,!SSLv3'
postconf -e 'smtp_tls_protocols=!SSLv2,!SSLv3'

#### Only by choise of user
if [ "$SMTP" != "LOCAL" ]; then
	postconf -e "smtp_host_lookup = dns, native"
	postconf -e "default_transport = smtp"

	case "$SMTP" in
		"FREE")
			SMTP_HOST="smtp.free.fr"
			SMTP_PORT=465
			SMTP_SECURITY=SSL			
		;;
		"YAHOO")
			SMTP_HOST="smtp.mail.yahoo.fr"
			SMTP_PORT=465
			SMTP_SECURITY=SSL	
		;;		
		"OVH")
			SMTP_HOST="ssl0.ovh.net"
			SMTP_PORT=465
			SMTP_SECURITY=SSL
		;;
		"GMAIL")
			SMTP_HOST="smtp.gmail.com"
			SMTP_PORT=465
			SMTP_SECURITY=SSL
		;;		
	esac
	
	case "$SMTP_SECURITY" in
		"SSL")
			# stunnel.conf
			cp /etc/MySB/templates/etc.stunnel.stunnel.conf.template /etc/stunnel/stunnel.conf		
			perl -pi -e "s/<smtp_host>:<smtp_port>/$SMTP_HOST:$SMTP_PORT/g" /etc/stunnel/stunnel.conf
			perl -pi -e "s/ENABLED=0/ENABLED=1/g" /etc/default/stunnel4
			echo "127.0.0.1:23000              $SMTP_USER:$SMTP_PASS" > /etc/postfix/sasl/sasl_passwd
			postconf -e "relayhost = 127.0.0.1:23000"		
			postconf -e "smtp_sasl_auth_enable = yes"
			postconf -e "smtp_sasl_security_options = noanonymous"
			postconf -e "smtp_sasl_password_maps = hash:/etc/postfix/sasl/sasl_passwd"
			postconf -e "smtp_sasl_mechanism_filter = plain"
			postconf -e "smtp_tls_security_level = may"	
		;;	
		"TLS")
			perl -pi -e "s/ENABLED=1/ENABLED=0/g" /etc/default/stunnel4
			postconf -e "smtp_sasl_auth_enable = yes"
			postconf -e "smtp_sasl_security_options = noanonymous"
			postconf -e "smtp_sasl_password_maps = hash:/etc/postfix/sasl/sasl_passwd"	
			postconf -e "smtp_sasl_mechanism_filter = plain"
			postconf -e "relayhost = $SMTP_HOST:$SMTP_PORT"
			postconf -e "tls_random_source = dev:/dev/urandom"
			postconf -e "smtp_use_tls = yes"
			postconf -e "smtp_tls_note_starttls_offer = yes"		
			postconf -e "smtp_tls_security_level = may"	
			postconf -e "smtp_sasl_tls_security_options = noanonymous"
			postconf -e "smtp_tls_scert_verifydepth = 5"
			postconf -e "smtp_tls_enforce_peername = no"
			postconf -e "smtp_tls_session_cache_database = btree:\${data_directory}/smtp_scache"
			postconf -e "smtp_tls_cert_file = /etc/MySB/ssl/postfix.cert"
			postconf -e "smtp_tls_key_file = /etc/MySB/ssl/postfix.key"	
			postconf -e "smtp_tls_policy_maps = hash:/etc/postfix/tls_policy"
			postconf -e "smtp_tls_CAfile = /etc/MySB/ssl/CA/certs/cacert.pem"			
		;;		
	esac
	
	postmap /etc/postfix/sasl/sasl_passwd
fi

echo "$SMTP_HOST" > /etc/MySB/infos/smtp_host.info
echo "$SMTP_PORT" > /etc/MySB/infos/smtp_port.info
echo "$SMTP_SECURITY" > /etc/MySB/infos/smtp_security.info

# -----------------------------------------
source /etc/MySB/inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################