#!/bin/bash
# ----------------------------------
# shellcheck source=inc/includes_before
source "$(dirname "$0")"/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#	_\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#	 _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#	  _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#	   _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#		_\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#		 _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#		  _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### Quota, add journaled quotas to the interested partition
echo
echo "########## /etc/fstab (before)"
cat /etc/fstab

gfnFstabGeneration 'add_quota'

echo
echo "########## /etc/fstab (after)"
cat /etc/fstab

# Create quota files
echo
if (grep -q '[[:space:]]/home[[:space:]]' /etc/fstab); then
    if [[ ! -f /home/aquota.user ]]; then
        touch /home/aquota.user
        chmod -v 600 /home/aquota.user
    fi
    if [[ ! -f /home/aquota.group ]]; then
        touch /home/aquota.group
        chmod -v 600 /home/aquota.group
    fi
else
    if [[ ! -f /aquota.user ]]; then
        touch /aquota.user
        chmod -v 600 /aquota.user
    fi
    if [[ ! -f /aquota.group ]]; then
        touch /aquota.group
        chmod -v 600 /aquota.group
    fi
fi

#### Install packages
# #101 [BUG] Processus /usr/sbin/rpc.rquotad CPU burst (100%)
sPackages=(quota quotatool)
# gfnPackageBundleInstall "${sPackages[@]}"
gfnPackagesManage install 'testing' "${sPackages[@]}"

# Config
install -v -o root -g root -m 0644 "${MySB_InstallDir}"/templates/quota/etc.default.quota.tmpl /etc/default/quota
install -v -o root -g root -m 0644 "${MySB_InstallDir}"/templates/quota/etc.warnquota.conf.tmpl /etc/warnquota.conf
sed -i "s/<main_user_mail>/${gsMainUserEmail}/g;" /etc/warnquota.conf
sed -i "s/<mail_subject>/${Quota_MailSubject}/g;" /etc/warnquota.conf
sed -i "s/<mail_message>/${Quota_MailMessage}/g;" /etc/warnquota.conf

#### Check actuel quota
modprobe quota_v1
modprobe quota_v2
(! grep -q 'quota_v1' /etc/modules) && echo quota_v1 | tee -a /etc/modules
(! grep -q 'quota_v2' /etc/modules) && echo quota_v2 | tee -a /etc/modules
if (grep -q '[[:space:]]/home[[:space:]]' /etc/fstab); then
    mount -v -o remount /home
else
    mount -v -o remount /
fi

quotacheck -acguvmf
quotaoff -a
quotaon -avug
repquota -a

# -----------------------------------------
# shellcheck source=inc/includes_after
source "$(dirname "$0")"/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################
