#!/bin/bash
# ----------------------------------
source $(dirname $0)/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#	_\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#	 _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#	  _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#	   _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#		_\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#		 _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#		  _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### Quota, add journaled quotas to the interested partition
echo
echo "########## /etc/fstab (before)"
cat /etc/fstab

gfnFstabGeneration 'add_quota'

echo
echo "########## /etc/fstab (after)"
cat /etc/fstab

# Create quota files
echo
[ ! -f /aquota.user ] && touch /aquota.user && chmod -v 600 /aquota.user
[ ! -f /aquota.group ] && touch /aquota.group && chmod -v 600 /aquota.group
if [[ ! -z $(grep '[[:space:]]/home[[:space:]]' /etc/fstab) ]]; then
    [ ! -f /home/aquota.user ] && touch /home/aquota.user && chmod -v 600 /home/aquota.user
    [ ! -f /home/aquota.group ] && touch /home/aquota.group && chmod -v 600 /home/aquota.group
fi

#### Install packages
gfnPackageBundleInstall 'quota quotatool'
install -v -o root -g root -m 0644 $MySB_InstallDir/templates/other/etc.default.quota.tmpl /etc/default/quota
install -v -o root -g root -m 0644 $MySB_InstallDir/templates/other/etc.warnquota.conf.tmpl /etc/warnquota.conf
perl -pi -e "s/<main_user_mail>/$gsMainUserEmail/g" /etc/warnquota.conf
perl -pi -e "s/<mail_subject>/$Quota_MailSubject/g" /etc/warnquota.conf
perl -pi -e "s/<mail_message>/$Quota_MailMessage/g" /etc/warnquota.conf

#### Check actuel quota
modprobe quota_v1
modprobe quota_v2
mount -v -o remount /
[[ ! -z $(grep '[[:space:]]/home[[:space:]]' /etc/fstab) ]] && mount -v -o remount /home
quotacheck -acguvmf
quotaoff -a
quotaon -avug
repquota -a

# -----------------------------------------
source $(dirname $0)/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################
