#!/bin/bash
# ----------------------------------
source $(dirname $0)/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### Install packages
if ! CheckCommand 0 rkhunter; then
	PackagesManage install "rkhunter unhide unhide.rb"
fi

#### /etc/default/rkhunter
perl -pi -e "s/CRON_DAILY_RUN=\"\"/CRON_DAILY_RUN=\"true\"/g" /etc/default/rkhunter
perl -pi -e "s/CRON_DB_UPDATE=\"\"/CRON_DB_UPDATE=\"true\"/g" /etc/default/rkhunter
perl -pi -e "s/APT_AUTOGEN=\"false\"/APT_AUTOGEN=\"true\"/g" /etc/default/rkhunter

#### /etc/rkhunter.conf
perl -pi -e "s/ALLOW_SSH_ROOT_USER=no/ALLOW_SSH_ROOT_USER=yes/g" /etc/rkhunter.conf
perl -pi -e "s/#ALLOWHIDDENFILE/ALLOWHIDDENFILE/g" /etc/rkhunter.conf
perl -pi -e "s/#ALLOWHIDDENDIR/ALLOWHIDDENDIR/g" /etc/rkhunter.conf
perl -pi -e "s/DISABLE_TESTS=\"suspscan hidden_procs deleted_files packet_cap_apps apps\"/DISABLE_TESTS=\"suspscan hidden_procs deleted_files packet_cap_apps apps promisc\"/g" /etc/rkhunter.conf
NumLign=$(sed -n "/ALLOWHIDDENDIR=\"\/etc\/.etckeeper\"/=" /etc/rkhunter.conf)
(( NumLign++ ))
if [ "`cat /etc/rkhunter.conf | grep 'ALLOWHIDDENDIR' | grep '/dev/.udev'`" ]; then
	sed -i "${NumLign}i\ALLOWHIDDENDIR=\"/dev/.udev\"" /etc/rkhunter.conf
fi
if [ "`cat /etc/rkhunter.conf | grep 'ALLOWHIDDENDIR' | grep '/dev/.mdadm'`" ]; then
	sed -i "${NumLign}i\ALLOWHIDDENDIR=\"/dev/.mdadm\"" /etc/rkhunter.conf
fi
if [ "`cat /etc/rkhunter.conf | grep 'ALLOWHIDDENDIR' | grep '/dev/.initramfs'`" ]; then
	sed -i "${NumLign}i\ALLOWHIDDENDIR=\"/dev/.initramfs\"" /etc/rkhunter.conf
fi
NumLign=$(sed -n "/SCRIPTWHITELIST=\/usr\/sbin\/prelink/=" /etc/rkhunter.conf)
(( NumLign++ ))
if [ -z "`cat /etc/rkhunter.conf | grep 'SCRIPTWHITELIST' | grep '/usr/bin/unhide.rb'`" ]; then
	sed -i "${NumLign}i\SCRIPTWHITELIST=\/usr\/bin\/unhide.rb" /etc/rkhunter.conf
fi

#### Execute
rkhunter --versioncheck --nocolors
rkhunter --propupd --nocolors
rkhunter --update --nocolors
rkhunter --sk --check --report-warnings-only

# -----------------------------------------
source $(dirname $0)/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################