#!/bin/bash
# ----------------------------------
source $(dirname $0)/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### Install packages
RKHunterDir=$MySB_InstallDir"`Func_SQL_Command 'SELECT' 'MySB_db' 'dir' 'repositories' "name = 'RKHunter'"`"
RKHunterUrl="`Func_SQL_Command 'SELECT' 'MySB_db' 'url' 'repositories' "name = 'RKHunter'"`"
RKHunterFile="`Func_SQL_Command 'SELECT' 'MySB_db' 'file' 'repositories' "name = 'RKHunter'"`"
RKHunterVersion="`Func_SQL_Command 'SELECT' 'MySB_db' 'version' 'repositories' "name = 'RKHunter'"`"
if [ ! -f $MySB_InstallDir/files/$RKHunterFile ]; then
	curl --retry 2 -kSL -o "$MySB_InstallDir/files/$RKHunterFile" "$RKHunterUrl"
fi
if [ ! -d $RKHunterDir ] && [ -f $MySB_InstallDir/files/$RKHunterFile ]; then
	echo
	echo "########## RKHunter"
	echo "Directory : "$RKHunterDir
	echo "Version : "$RKHunterVersion
	echo "File : "$RKHunterFile
	echo "URL : "$RKHunterUrl
	echo
	tar -zxvf $MySB_InstallDir/files/$RKHunterFile -C $MySB_InstallDir/temp/
	SubDir="`tar -ztf $MySB_InstallDir/files/$RKHunterFile | sed -e 's@/.*@@' | uniq`"
	if [ -d $MySB_InstallDir/temp/$SubDir ]; then
		mv $MySB_InstallDir/temp/$SubDir $RKHunterDir
	fi
fi

cd $RKHunterDir/
if [ /etc/rkhunter.conf ]; then rm -vf /etc/rkhunter.conf; fi
./installer.sh --install

#### /etc/rkhunter.conf
perl -pi -e "s/^#ALLOW_SSH_ROOT_USER=no/ALLOW_SSH_ROOT_USER=yes/g" /etc/rkhunter.conf
perl -pi -e "s/^#APP_WHITELIST=\"\"/APP_WHITELIST=\"openssl:1.0.1e gpg:1.4.12\"/g" /etc/rkhunter.conf
perl -pi -e "s/^#ALLOWPROMISCIF=eth0/ALLOWPROMISCIF=eth0 tap0/g" /etc/rkhunter.conf

#### Execute
rkhunter --versioncheck --nocolors
rkhunter --propupd --nocolors
rkhunter --update --nocolors
rkhunter --sk --check --report-warnings-only

# -----------------------------------------
source $(dirname $0)/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################