#!/bin/bash
# ----------------------------------
source $(dirname $0)/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### Install rTorrent v0.9.2
if ! CheckCommand 0 rtorrent; then
	PackagesManage install "rtorrent buildtorrent mediainfo ffmpeg"
fi

#### Install rTorrent
# XMLRPC-C
XmlrpcDir=$MySB_InstallDir"`Func_SQL_Command 'SELECT' 'MySB_db' 'dir' 'repositories' "name = 'XMLRPC'"`"
XmlrpcUrl="`Func_SQL_Command 'SELECT' 'MySB_db' 'url' 'repositories' "name = 'XMLRPC'"`"
XmlrpcFile="`Func_SQL_Command 'SELECT' 'MySB_db' 'file' 'repositories' "name = 'XMLRPC'"`"
XmlrpcVersion="`Func_SQL_Command 'SELECT' 'MySB_db' 'version' 'repositories' "name = 'XMLRPC'"`"
echo
echo "########## XMLRPC-C"
echo "Directory : "$XmlrpcDir
echo "Version : "$XmlrpcVersion
echo "File : "$XmlrpcFile
echo "URL : "$XmlrpcUrl
echo
if [ -d $XmlrpcDir ]; then
	svn up --non-interactive --trust-server-cert $XmlrpcDir
	if [ $? -gt 0 ]; then
		svn switch $XmlrpcUrl $XmlrpcDir
	fi
else
	if [ -f $MySB_InstallDir/files/$XmlrpcFile ]; then
		unzip $MySB_InstallDir/files/$XmlrpcFile -d $MySB_InstallDir/temp/
		SubDir="`unzip -l $MySB_InstallDir/files/$XmlrpcFile | awk '{ print $4 }' | cut -d '/' -f 1 | uniq | sed '1,3d;$d'`"
		if [ -d $MySB_InstallDir/temp/$SubDir ]; then
			mv -v $MySB_InstallDir/temp/$SubDir $XmlrpcDir
		fi
		if [ -d $XmlrpcDir/.svn ]; then
			svn up --non-interactive --trust-server-cert $XmlrpcDir
			if [ $? -gt 0 ]; then
				svn switch $XmlrpcUrl $XmlrpcDir
			fi
		fi
	else
		svn co --non-interactive --trust-server-cert $XmlrpcUrl $XmlrpcDir
	fi
fi
cd $XmlrpcDir/
if [ -f config.mk ] && [ -f common.mk ]; then
	make clean
fi
#./configure --enable-libxml2-backend --disable-abyss-server --disable-cgi-server --disable-cplusplus --disable-libwww-client --disable-wininet-client
./configure --disable-abyss-server --disable-cgi-server --disable-cplusplus --disable-libwww-client --disable-wininet-client
make -j$PROCESSOR
make install

# LIBtorrent
LibtorrentDir=$MySB_InstallDir"`Func_SQL_Command 'SELECT' 'MySB_db' 'dir' 'repositories' "name = 'LibTorrent'"`"
LibtorrentUrl="`Func_SQL_Command 'SELECT' 'MySB_db' 'url' 'repositories' "name = 'LibTorrent'"`"
LibtorrentFile="`Func_SQL_Command 'SELECT' 'MySB_db' 'file' 'repositories' "name = 'LibTorrent'"`"
LibtorrentVersion="`Func_SQL_Command 'SELECT' 'MySB_db' 'version' 'repositories' "name = 'LibTorrent'"`"
echo
echo "########## LIBtorrent"
echo "Directory : "$LibtorrentDir
echo "Version : "$LibtorrentVersion
echo "File : "$LibtorrentFile
echo "URL : "$LibtorrentUrl
echo
if [ ! -f $MySB_InstallDir/files/$LibtorrentFile ]; then
	curl --retry 2 -kSL -o "$MySB_InstallDir/files/$LibtorrentFile" "$LibtorrentUrl"
fi
if [ ! -d $LibtorrentDir ] && [ -f $MySB_InstallDir/files/$LibtorrentFile ]; then
	tar -zxvf $MySB_InstallDir/files/$LibtorrentFile -C $MySB_InstallDir/temp/
	SubDir="`tar -ztf $MySB_InstallDir/files/$LibtorrentFile | sed -e 's@/.*@@' | uniq`"
	if [ -d $MySB_InstallDir/temp/$SubDir ]; then
		mv -v $MySB_InstallDir/temp/$SubDir $LibtorrentDir
	fi
fi
cd $LibtorrentDir/
make clean
./autogen.sh
./configure --with-posix-fallocate
make -j$PROCESSOR
make install

# rTorrent
RtorrentDir=$MySB_InstallDir"`Func_SQL_Command 'SELECT' 'MySB_db' 'dir' 'repositories' "name = 'rTorrent'"`"
RtorrentUrl="`Func_SQL_Command 'SELECT' 'MySB_db' 'url' 'repositories' "name = 'rTorrent'"`"
RtorrentFile="`Func_SQL_Command 'SELECT' 'MySB_db' 'file' 'repositories' "name = 'rTorrent'"`"
RtorrentVersion="`Func_SQL_Command 'SELECT' 'MySB_db' 'version' 'repositories' "name = 'rTorrent'"`"
echo
echo "########## rTorrent"
echo "Directory : "$LibtorrentDir
echo "Version : "$RtorrentVersion
echo "File : "$RtorrentFile
echo "URL : "$RtorrentUrl
echo
if [ ! -f $MySB_InstallDir/files/$RtorrentFile ]; then
	curl --retry 2 -kSL -o "$MySB_InstallDir/files/$RtorrentFile" "$RtorrentUrl"
fi
if [ ! -d $RtorrentDir ] && [ -f $MySB_InstallDir/files/$RtorrentFile ]; then
	tar -zxvf $MySB_InstallDir/files/$RtorrentFile -C $MySB_InstallDir/temp/
	SubDir="`tar -ztf $MySB_InstallDir/files/$RtorrentFile | sed -e 's@/.*@@' | uniq`"
	if [ -d $MySB_InstallDir/temp/$SubDir ]; then
		mv -v $MySB_InstallDir/temp/$SubDir $RtorrentDir
	fi
fi
cd $RtorrentDir/
make clean
./autogen.sh
./configure --with-xmlrpc-c=/usr/local/bin/xmlrpc-c-config
make -j$PROCESSOR
make install
ldconfig

# -----------------------------------------
source $(dirname $0)/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################