#!/bin/bash
# ----------------------------------
source $(dirname $0)/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### Install rTorrent v0.9.2
gfnPackageBundleInstall 'rtorrent buildtorrent mediainfo ffmpeg'

#### VARs
gnRTorrentUpgrade=0

#### Install rTorrent
# XMLRPC-C
gfnGetRepoValues 'XMLRPC' && gfnRepoManageByType
if [ $gnRepoUpgrade -eq 1 ] || [ "$gsSwitch" == "INSTALL" ]; then
	gnRTorrentUpgrade=1
	cd $gsRepoDir/ || exit 1
	if [ -f config.mk ] && [ -f common.mk ]; then
		make clean
	fi
	./configure --disable-abyss-server --disable-cgi-server --disable-cplusplus --disable-libwww-client --disable-wininet-client
	make -j$gsProcessors
	make install
	# Disable the upgrade job
	cmdMySQL 'MySB_db' "UPDATE repositories SET upgrade='0' WHERE name='XMLRPC';" -v
fi

# LIBtorrent
gfnGetRepoValues 'LibTorrent' && gfnRepoManageByType
if [ $gnRepoUpgrade -eq 1 ] || [ "$gsSwitch" == "INSTALL" ]; then
	gnRTorrentUpgrade=1
	cd $gsRepoDir/ || exit 1
	make clean
	./autogen.sh
	./configure --with-posix-fallocate
	make -j$gsProcessors
	make install
	# Disable the upgrade job
	cmdMySQL 'MySB_db' "UPDATE repositories SET upgrade='0' WHERE name='LibTorrent';" -v
fi

# rTorrent
gfnGetRepoValues 'rTorrent' && gfnRepoManageByType
if [ $gnRepoUpgrade -eq 1 ] || [ $gnRTorrentUpgrade -eq 1 ] || [ "$gsSwitch" == "INSTALL" ]; then
	cd $gsRepoDir/ || exit 1
	libtorrent_LIBS=/usr/local/lib/
	libtorrent_CFLAGS=/usr/local/lib/
	make clean
	./autogen.sh
	./configure --with-xmlrpc-c
	make -j$gsProcessors
	make install
	ldconfig
	# Disable the upgrade job
	cmdMySQL 'MySB_db' "UPDATE repositories SET upgrade='0' WHERE name='rTorrent';" -v
fi

# -----------------------------------------
source $(dirname $0)/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################