#!/bin/bash
# ----------------------------------
source $(dirname $0)/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### Install rTorrent v0.9.2
if ! CheckCommand 0 rtorrent; then
	PackagesManage install "rtorrent buildtorrent mediainfo ffmpeg"
fi

#### Install rTorrent v0.9.4
# XMLRPC-C
XmlrpcDir=$MySB_InstallDir"`sqlite3 -cmd '.timeout 150000' $MySB_DB \"SELECT dir FROM repositories WHERE name = 'XMLRPC'\"`"
XmlrpcUrl="`sqlite3 -cmd '.timeout 150000' $MySB_DB \"SELECT url FROM repositories WHERE name = 'XMLRPC'\"`"
XmlrpcFile="`sqlite3 -cmd '.timeout 150000' $MySB_DB \"SELECT file FROM repositories WHERE name = 'XMLRPC'\"`"
if [ ! -f $MySB_InstallDir/files/$XmlrpcFile ]; then
	wget --no-check-certificate $XmlrpcUrl -O $MySB_InstallDir/files/$XmlrpcFile
fi
if [ ! -d $XmlrpcDir ] && [ -f $MySB_InstallDir/files/$XmlrpcFile ]; then
	tar -zxvf $MySB_InstallDir/files/$XmlrpcFile -C $MySB_InstallDir/temp/	
	SubDir="`tar -ztf $MySB_InstallDir/files/$XmlrpcFile | sed -e 's@/.*@@' | uniq`"
	if [ -d $MySB_InstallDir/temp/$SubDir ]; then
		mv $MySB_InstallDir/temp/$SubDir $XmlrpcDir
	fi
fi
cd $XmlrpcDir/
make clean
./configure --enable-libxml2-backend --disable-abyss-server --disable-cgi-server --disable-cplusplus --disable-libwww-client --disable-wininet-client 
make -j$PROCESSOR
make install

# LIBtorrent 0.13.4
LibtorrentDir=$MySB_InstallDir"`sqlite3 -cmd '.timeout 150000' $MySB_DB \"SELECT dir FROM repositories WHERE name = 'LibTorrent'\"`"
LibtorrentUrl="`sqlite3 -cmd '.timeout 150000' $MySB_DB \"SELECT url FROM repositories WHERE name = 'LibTorrent'\"`"
LibtorrentFile="`sqlite3 -cmd '.timeout 150000' $MySB_DB \"SELECT file FROM repositories WHERE name = 'LibTorrent'\"`"
if [ ! -f $MySB_InstallDir/files/$LibtorrentFile ]; then
	wget --no-check-certificate $LibtorrentUrl -O $MySB_InstallDir/files/$LibtorrentFile
fi
if [ ! -d $LibtorrentDir ] && [ -f $MySB_InstallDir/files/$LibtorrentFile ]; then
	tar -zxvf $MySB_InstallDir/files/$LibtorrentFile -C $MySB_InstallDir/temp/	
	SubDir="`tar -ztf $MySB_InstallDir/files/$LibtorrentFile | sed -e 's@/.*@@' | uniq`"
	if [ -d $MySB_InstallDir/temp/$SubDir ]; then
		mv $MySB_InstallDir/temp/$SubDir $LibtorrentDir
	fi
fi
cd $LibtorrentDir/
make clean
./autogen.sh
./configure --with-posix-fallocate
make
make install

# rTorrent 0.9.4
RtorrentDir=$MySB_InstallDir"`sqlite3 -cmd '.timeout 150000' $MySB_DB \"SELECT dir FROM repositories WHERE name = 'rTorrent'\"`"
RtorrentUrl="`sqlite3 -cmd '.timeout 150000' $MySB_DB \"SELECT url FROM repositories WHERE name = 'rTorrent'\"`"
RtorrentFile="`sqlite3 -cmd '.timeout 150000' $MySB_DB \"SELECT file FROM repositories WHERE name = 'rTorrent'\"`"
if [ ! -f $MySB_InstallDir/files/$RtorrentFile ]; then
	wget --no-check-certificate $RtorrentUrl -O $MySB_InstallDir/files/$RtorrentFile
fi
if [ ! -d $RtorrentDir ] && [ -f $MySB_InstallDir/files/$RtorrentFile ]; then
	tar -zxvf $MySB_InstallDir/files/$RtorrentFile -C $MySB_InstallDir/temp/	
	SubDir="`tar -ztf $MySB_InstallDir/files/$RtorrentFile | sed -e 's@/.*@@' | uniq`"
	if [ -d $MySB_InstallDir/temp/$SubDir ]; then
		mv $MySB_InstallDir/temp/$SubDir $RtorrentDir
	fi
fi
cd $RtorrentDir/
make clean
./autogen.sh
./configure --with-xmlrpc-c=/usr/local/bin/xmlrpc-c-config
make
make install
ldconfig


#### Create certificates
if [ ! -f $MySB_InstallDir/ssl/rtorrent.cert ]; then
	ScriptInvoke 'source' "$MySB_InstallDir/install/Certificates" 'CreateServiceCertificate' 'rtorrent'
fi

# -----------------------------------------
source $(dirname $0)/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################