#!/bin/bash
# ----------------------------------
# shellcheck source=inc/includes_before
source "$(dirname "$0")"/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#	_\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#	 _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#	  _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#	   _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#		_\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#		 _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#		  _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### STOP services
gfnManageServices stop "cron"
gfnListCountUsers 'normal'
for seedUser in ${gsUsersList}; do
    if (systemctl status rtorrent-"${seedUser}" &>/dev/null); then
        systemctl stop rtorrent-"${seedUser}"
    fi
done

#### Install some tools for plugins
gfnPackageBundleInstall 'sox'

#### ruTorrent + Official Plugins
# Backup conf
if [ -d "${gsRutorrentDir}"/share/users ]; then
    mv -v "${gsRutorrentDir}"/share/users "${MySB_InstallDir}"/temp/rutorrent_share_users
fi
# ruTorrent
gfnGetRepoValues 'ruTorrent'
sVersionDB="$(cmdMySQL 'MySB_db' "SELECT version FROM repositories WHERE name='ruTorrent';")"
sVersionInstalled="$(cat "${gsRutorrentDir}"/version &>/dev//null || echo "Not installed")"
if [ "${sVersionDB}" != "${sVersionInstalled}" ] || [ "${gnRepoUpgrade}" -eq 1 ]; then
    if [ -f "${MySB_Files}/${gsRepoFile}" ] || [ "${gnRepoUpgrade}" -eq 1 ]; then
        gfnDeleteDirectory 1 "${gsRutorrentDir}"
    fi
fi

gfnRepoManageByType
rm -vf "${gsRepoDir}"/htaccess-example
rm -vf "${gsRepoDir}"/plugins/extsearch/engines/NNMClub.php
echo "${gsRepoVersion}" >"${gsRutorrentDir}"/version
# Restore conf
if [ -d "${MySB_InstallDir}"/temp/rutorrent_share_users ]; then
    if [ -d "${gsRutorrentDir}"/share/users ]; then
        gfnDeleteDirectory 1 "${gsRutorrentDir}"/share/users
    fi
    mv -v "${MySB_InstallDir}"/temp/rutorrent_share_users "${gsRutorrentDir}"/share/users
fi

#### Hack
install -v -o www-data -g www-data -m 0755 "${MySB_InstallDir}"/templates/rutorrent/rtorrent.php.tmpl "${gsRutorrentDir}"/php/rtorrent.php

#### Plugin Chat
gfnGetRepoValues 'ruTorrent Plugin Chat'
gfnRepoManageByType

#### ruTorrent Plugin Link Cakebox
if [ "${gbToInstall_Cakebox}" == "YES" ] || [ "${gbIsInstalled_Manager}" == "YES" ]; then
    gfnGetRepoValues 'ruTorrent Plugin Link Cakebox'
    gfnRepoManageByType
    chown -vR www-data:www-data "${gsRepoDir}"
    sed -i "s/'http:\/\/'.\$host;/'https:\/\/${gsHostNameFqdn}:${gsPort_MySB_HTTPS}\/cb\/';/g;" "${gsRepoDir}"/conf.php
    sed -i "s/torrents/rtorrent/g;" "${gsRepoDir}"/conf.php
fi

#### ruTorrent Plugin Link Manager
if [ "${gbToInstall_Manager}" == "YES" ] || [ "${gbIsInstalled_Manager}" == "YES" ]; then
    gfnGetRepoValues 'ruTorrent Plugin Link Manager'
    gfnRepoManageByType
    sed -i "s/http:\/\/seedbox-manager.ndd.tld/https:\/\/${gsHostNameFqdn}:${gsPort_MySB_HTTPS}\/sm\//g;" "${gsRepoDir}"/conf.php
fi

#### Plugin Logoff
gfnGetRepoValues 'ruTorrent Plugin Logoff'
gfnRepoManageByType

#### Plugin tAdd-Labels
gfnGetRepoValues 'ruTorrent Plugin LBLL-Suite'
gfnRepoManageByType

#### Plugin NFO
gfnGetRepoValues 'ruTorrent Plugin NFO'
gfnRepoManageByType
if [ ! -f "${gsRepoDir}"/lang/fr.js ]; then
    cp -v "${gsRepoDir}"/lang/en.js "${gsRepoDir}"/lang/fr.js
    perl -pi -e "s/NFO Viewer/Visionneuse NFO/g" "${gsRepoDir}"/lang/fr.js
    perl -pi -e "s/Could not open NFO/Impossible d'ouvrir le NFO/g" "${gsRepoDir}"/lang/fr.js
    perl -pi -e "s/ERROR/ERREUR/g" "${gsRepoDir}"/lang/fr.js
fi

#### Plugin Check SFV
gfnGetRepoValues 'ruTorrent Plugin Check SFV'
gfnRepoManageByType
if [ -f "${gsRepoDir}"/conf.php ]; then
    perl -pi -e "s/'';/'\/usr\/bin\/cksfv';/g" "${gsRepoDir}"/conf.php
fi
if [ ! -f "${gsRepoDir}"/lang/fr.js ]; then
    cp -v "${gsRepoDir}"/lang/en.js "${gsRepoDir}"/lang/fr.js
    perl -pi -e "s/Check SFV/V&eacute;rification SFV/g" "${gsRepoDir}"/lang/fr.js
fi

#### Plugin InstantSearch
gfnGetRepoValues 'ruTorrent Plugin InstantSearch'
gfnRepoManageByType

#### Plugin Show IP
gfnGetRepoValues 'ruTorrent Plugin Show IP'
gfnRepoManageByType

#### Plugin Speed Graph
gfnGetRepoValues 'ruTorrent Plugin Speed Graph'
gfnRepoManageByType
if [ ! -f "${gsRepoDir}"/lang/fr.js ]; then
    cp -v "${gsRepoDir}"/lang/en.js "${gsRepoDir}"/lang/fr.js
    perl -pi -e "s/Monitoring Time/Surveillance du temps/g" "${gsRepoDir}"/lang/fr.js
    perl -pi -e "s/Speed Graph/Graphique de vitesse/g" "${gsRepoDir}"/lang/fr.js
fi

#### Plugin Ratiocolor
gfnGetRepoValues 'ruTorrent Plugin RatioColor'
gfnRepoManageByType
if [ -f "${gsRepoDir}"/init.js ]; then
    perl -pi -e 's/changeWhat = "cell-background";/changeWhat = "font";/g' "${gsRepoDir}"/init.js
fi

#### Plugin Filemanager
gfnGetRepoValues 'ruTorrent Plugin FileManager'
gfnRepoManageByType

#### Plugin FileUpload
gfnGetRepoValues 'ruTorrent Plugin FileUpload'
gfnRepoManageByType

#### Plugin Fileshare
gfnGetRepoValues 'ruTorrent Plugin FileShare'
gfnRepoManageByType
if [ -f "${gsRepoDir}"/conf.php ]; then
    perl -pi -e "s/http:\/\/mydomain.com\/share.php/https:\/\/${gsHostNameFqdn}:${gsPort_MySB_HTTPS}\/fileshare.php/g" "${gsRepoDir}"/conf.php
fi

#### Plugin Mediastream
gfnGetRepoValues 'ruTorrent Plugin MediaStream'
gfnRepoManageByType
if [ -f "${gsRepoDir}"/conf.php ]; then
    perl -pi -e "s/http:\/\/mydomain.com\/stream\/view.php/https:\/\/${gsHostNameFqdn}:${gsPort_MySB_HTTPS}\/view/g" "${gsRepoDir}"/conf.php
fi

#### Plugin Stream
gfnGetRepoValues 'ruTorrent Plugin Stream'
gfnRepoManageByType
if [ -f "${gsRepoDir}"/config.php ]; then
    perl -pi -e "s/define\('USE_NGINX', false\);/define\('USE_NGINX', true\);/g" "${gsRepoDir}"/config.php
    perl -pi -e "s/define\('SCHEME', 'http'\);/define\('SCHEME', 'https'\);/g" "${gsRepoDir}"/config.php
fi

#### Plugin Pause WebUI
gfnGetRepoValues 'ruTorrent Plugin Pause WebUI'
gfnRepoManageByType

#### Plugin Mobile
gfnGetRepoValues 'ruTorrent Plugin Mobile'
gfnRepoManageByType

#### Plugin Mark for Rsync
gfnGetRepoValues 'ruTorrent Plugin Mark for Rsync'
gfnRepoManageByType

#### Plugin Sync
gfnGetRepoValues 'ruTorrent Plugin Sync'
gfnRepoManageByType

#### Plugin Autodl-irssi
#gfnGetRepoValues 'ruTorrent Plugin Autodl-irssi'
# gfnRepoManageByType

#### ruTorrent Theme Oblivion
if (! grep -q 'for Oblivion' "${gsRutorrentDir}"/css/style.css); then
    echo
    echo "########## ruTorrent Theme Oblivion"
    echo
    echo "" >>"${gsRutorrentDir}"/css/style.css
    echo "/* for Oblivion */" | tee -a "${gsRutorrentDir}"/css/style.css
    echo ".meter-value-start-color { background-color: #E05400 }" | tee -a "${gsRutorrentDir}"/css/style.css
    echo ".meter-value-end-color { background-color: #8FBC00 }" | tee -a "${gsRutorrentDir}"/css/style.css
    echo "::-webkit-scrollbar {width:12px;height:12px;padding:0px;margin:0px;}" | tee -a "${gsRutorrentDir}"/css/style.css
fi
perl -pi -e "s/\$defaultTheme \= \"\"\;/\$defaultTheme \= \"Oblivion\"\;/g" "${gsRutorrentPluginsDir}"/theme/conf.php

#### ruTorrent Theme club-QuickBox
gfnGetRepoValues 'ruTorrent Theme club-QuickBox'
gfnRepoManageByType

#### ruTorrent Theme MaterialDesign
gfnGetRepoValues 'ruTorrent Theme MaterialDesign'
gfnRepoManageByType

#### For _cloudflare plugin
pip install cloudscraper

#### Plowshare
gfnGetRepoValues 'Plowshare'
if [ "${gsSwitch}" == "REFRESH" ]; then
    gfnDeleteDirectory 1 "${gsRepoDir}"
fi
gfnRepoManageByType
if [[ ${gnRepoUpgrade} -eq 1 ]] || [ "${gsSwitch}" == "INSTALL" ]; then
    cd "${gsRepoDir}" || exit 1
    make clean
    make install
    # Disable the upgrade job
    cmdMySQL 'MySB_db' "UPDATE repositories SET upgrade='0' WHERE name='Plowshare';" -v
    cd .. && gfnDeleteDirectory 1 "${gsRepoDir:-/tmp/null}"/
fi

#### Create directories & change rights
echo
log_daemon_msg "Change owners and rights for files and directories"
gfnManageDirAndFiles 'global'
gfnStatusLSB

#### START services
if [ "${gsSwitch}" != "UPGRADE" ]; then
    gfnManageServices start "cron"

    for seedUser in ${gsUsersList}; do
        if [ -f /etc/init.d/rtorrent-"${seedUser}" ]; then
            gfnManageServices stop "rtorrent-${seedUser}"
            gfnManageServices start "rtorrent-${seedUser}"
        fi
    done
fi

# -----------------------------------------
# shellcheck source=inc/includes_after
source "$(dirname "$0")"/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################
