#!/bin/bash
# ----------------------------------
# shellcheck source=inc/includes_before
source "$(dirname "$0")"/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#	_\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#	 _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#	  _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#	   _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#		_\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#		 _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#		  _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
######################################################################
# https://computingforgeeks.com/how-to-setup-s3-compatible-object-storage-server-with-minio/
# https://www.digitalocean.com/community/tutorials/how-to-set-up-an-object-storage-server-using-minio-on-ubuntu-16-04
# Multi NginX location for each bucket: https://forum.nginx.org/read.php?11,281903
##################### FIRST LINE #####################################

#### Systemd
case "${gsSwitch}" in
    'INSTALL'|'UPGRADE')
        (! grep -q 'minio' /etc/group) && groupadd --system minio
        (! grep -q 'minio' /etc/passwd) && useradd -s /sbin/nologin --system -g minio minio
        install -v -o root -g root -m 0644 ${MySB_InstallDir}/templates/systemd/minio.service.tmpl /lib/systemd/system/minio.service
        systemctl daemon-reload
        systemctl enable minio.service
        install -d -v -o minio -g minio -m 0755 /etc/minio/certs
        install -d -v -o minio -g minio -m 0755 /usr/local/share/minio
        if [[ -f "/etc/letsencrypt/live/${gsHostNameFqdn}/privkey.pem" ]] && [[ -f "/etc/letsencrypt/live/${gsHostNameFqdn}/cert.pem" ]]; then
            cp "/etc/letsencrypt/live/${gsHostNameFqdn}/privkey.pem" /etc/minio/certs/private.key
            cp "/etc/letsencrypt/live/${gsHostNameFqdn}/cert.pem" /etc/minio/certs/public.crt
        fi
     ;;
esac

[ -f /etc/default/minio ] && source /etc/default/minio
MINIO_ACCESS_KEY="${MINIO_ACCESS_KEY:-$(gfnGenPassword 20)}"
MINIO_SECRET_KEY="${MINIO_SECRET_KEY:-$(gfnGenPassword 40)}"

#### /etc/default/minio
if [ ! -f /etc/default/minio ]; then
    {
        echo "# Volume to be used for Minio server."
        echo "MINIO_VOLUMES=\"/usr/local/share/minio/\""
        echo "# Use if you want to run Minio on a custom port."
        echo "MINIO_OPTS=\"-C /etc/minio --address ${gsHostNameFqdn}:9000\""
        echo "# Access Key of the server."
        echo "MINIO_ACCESS_KEY=\"${MINIO_ACCESS_KEY}\""
        echo "# Secret key of the server."
        echo "MINIO_SECRET_KEY=\"${MINIO_SECRET_KEY}\""
    } >/etc/default/minio
fi

#### /etc/minio/config.json
if [ ! -f /etc/minio/config.json ]; then
cat <<EOF >/etc/minio/config.json
{
    "version": "19",
    "credential": {
        "accessKey": "${MINIO_ACCESS_KEY}",
        "secretKey": "${MINIO_SECRET_KEY}"
    },
    "region": "us-east-1"
}
EOF
fi

#### Minio
fnInstallMinio() {
    gfnGetRepoValues 'Minio'

    if [ "${gsVersionInstalled}" != "${gsVersionLatest}" ]; then
        [ -f "${MySB_Files}/${gsRepoFile}" ] && mv -v "${MySB_Files}/${gsRepoFile}" "${MySB_Files}/${gsRepoFile}.tmp"
        gfnRepoManageByType
        [ -f "${MySB_Files}/${gsRepoFile}" ] && rm -fv "${MySB_Files}/${gsRepoFile}.tmp"
        chmod -v +x ${gsRepoDir}
        ${gsRepoDir} version
    fi
}

#### Goofys
fnInstallGoofys() {
    gfnGetRepoValues 'Goofys'

    if [ "${gsVersionInstalled}" != "${gsVersionLatest}" ]; then
        [ -f "${MySB_Files}/${gsRepoFile}" ] && mv -v "${MySB_Files}/${gsRepoFile}" "${MySB_Files}/${gsRepoFile}.tmp"
        gfnRepoManageByType
        [ -f "${MySB_Files}/${gsRepoFile}" ] && rm -fv "${MySB_Files}/${gsRepoFile}.tmp"
        chmod -v +x ${gsRepoDir}
        ${gsRepoDir} --version
    fi
}

fnInstallMinio
fnInstallGoofys

# -----------------------------------------
# shellcheck source=inc/includes_after
source "$(dirname "$0")"/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################
