#!/bin/bash
# ----------------------------------
source $(dirname $0)/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

if [ "$USAGE" == "ON" ]; then
	if [ "`screen -ls | grep SeedboxManager`" == "" ]; then
		if [ "$gbIsInstalled_Manager" == "NO" ]; then
			echo
			echo -e "${CYELLOW}SeedBox-Manager is not installed!$CEND"
			gfnQuestionGetString NO  "Install Seedbox-Manager? " gbToInstall_Manager $gbToInstall_Manager

			if [ "$gbToInstall_Manager" == "YES" ]; then
				gfnQuestionGetString NO  "Contact email for Seedbox-Manager: " gsMainUserEmail $gsMainUserEmail
			fi

			cmdMySQL 'MySB_db' "UPDATE services SET to_install = '$(echo $gbToInstall_Manager | sed 's/NO/0/g;' | sed 's/YES/1/g;')' WHERE serv_name='Seedbox-Manager';" -v
		fi
	fi
fi

if [ "$gbToInstall_Manager" == "YES" ]; then
	#### NginX
	install -v -o root -g root -m 0644 $MySB_InstallDir/templates/nginx/etc.nginx.locations.seedbox-manager.conf.tmpl /etc/nginx/locations/Seedbox-Manager.conf
	perl -pi -e "s/<InstallDir>/$gsInstallDirEscaped/g" /etc/nginx/locations/Seedbox-Manager.conf

	#### Seedbox-Manager
	gfnGetRepoValues 'Seedbox-Manager'
	if [ "$1" == "REFRESH" ] || [ $gnRepoUpgrade -eq 1 ]; then
		if [ -d $gsManagerDir/conf ]; then
			mv -v $gsManagerDir/conf $MySB_InstallDir/temp/sm_conf
		fi
		gfnDeleteDirectory 1 "$gsManagerDir"
	fi
	gfnRepoManageByType

	cd $gsManagerDir/
	composer update

	if [ -d $MySB_InstallDir/temp/sm_conf ]; then
		mv -v $MySB_InstallDir/temp/sm_conf $gsManagerDir/conf
	fi

	#### Install
	cd ./source/
	chmod +x install.sh && ./install.sh

	#### Language FR
	perl -pi -e "s/Les accès FTP - SFTP - Transdroid/Les accès FTPs - sFTP - Transdroid/g" $gsManagerDir/locale/core.fr.yml
	perl -pi -e "s/Serveur FTP et SFTP/Serveur FTPs et sFTP/g" $gsManagerDir/locale/core.fr.yml
	perl -pi -e "s/ \(s\)FTP//g" $gsManagerDir/locale/core.fr.yml
	perl -pi -e "s/ Port FTP/ Port FTPs/g" $gsManagerDir/locale/core.fr.yml
	#### Language EN
	perl -pi -e "s/FTP \/ SFTP \/ Transdroid - Access/FTPs \/ sFTP \/ Transdroid - Access/g" $gsManagerDir/locale/core.en.yml
	perl -pi -e "s/FTP and SFTP Server/FTPs and sFTP Server/g" $gsManagerDir/locale/core.en.yml
	perl -pi -e "s/ \(S\)FTP//g" $gsManagerDir/locale/core.en.yml
	perl -pi -e "s/ FTP port/ FTPs port/g" $gsManagerDir/locale/core.en.yml
	perl -pi -e "s/ SFTP port/ sFTP port/g" $gsManagerDir/locale/core.en.yml
	#### Template
	perl -pi -e "s/\(s\)ftp:\/\///g" $gsManagerDir/view/index.twig.html
	perl -pi -e "s/https:\/\/filezilla.fr\//http:\/\/filezilla-project.org\//g" $gsManagerDir/view/index.twig.html
	#### src/Seedbox/FileConfiguration.php
	perl -pi -e "s/seedbox-/MySB-/g" $gsManagerDir/src/Seedbox/FileConfiguration.php
	perl -pi -e "s/-ftp/-ftps/g" $gsManagerDir/src/Seedbox/FileConfiguration.php
	nNumLine=$(cat $gsManagerDir/src/Seedbox/FileConfiguration.php | grep 'base_ftp_url' -n -m 1 | cut -d ':' -f 1)
	sed -i '/base_ftp_url/d' $gsManagerDir/src/Seedbox/FileConfiguration.php
	sed -i ""$nNumLine"i\                'base_ftp_url' => ''," $gsManagerDir/src/Seedbox/FileConfiguration.php
	#### src/Controller/DownloadController.php
	nNumLine=$(cat $gsManagerDir/src/Controller/DownloadController.php | grep 'getServerParams' -n -m 1 | cut -d ':' -f 1)
	(( nNumLine++ ))
	sed -i ""$nNumLine"i\        \$host = strstr(\$host, ':', true);" $gsManagerDir/src/Controller/DownloadController.php
	#### Clean cache
	rm -rfv $gsManagerDir/cache/*

	#### ruTorrent Plugin Link Manager
	gfnGetRepoValues 'ruTorrent Plugin Link Manager' && gfnRepoManageByType
	sed -i "s/http:\/\/seedbox-manager.ndd.tld/https:\/\/$gsHostNameFqdn:$gsPort_HTTPS\/sm\//g;" $gsRepoDir/conf.php

	#### Create directories & change rights
	gfnManageDirAndFiles 'global'

	if gfnCheckCommand 0 $gsManagerDir/reboot-rtorrent; then
		cmdMySQL 'MySB_db' "UPDATE services SET to_install = '0', is_installed = '1' WHERE serv_name='Seedbox-Manager';" -v
	fi

	#### START services
	gfnManageServices start "nginx"
fi

# -----------------------------------------
source $(dirname $0)/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################