#!/bin/bash 
# ----------------------------------
source /etc/MySB/inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___        
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_       
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_      
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__     
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_    
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_   
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_  
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__ 
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### Change working directory
cd /etc/MySB/files

log_daemon_msg "Create sources.list file"
#### source.list
cp /etc/MySB/templates/sources.list.debian.template /etc/apt/sources.list
sed -i "s/<debian_version>/$DEBIAN_VERSION/g;" /etc/apt/sources.list
StatusLSB

#### dotdeb php 5.5
echo "# dotdeb php 5.5" > /etc/apt/sources.list.d/dotdeb_php55.list
echo "" >> /etc/apt/sources.list.d/dotdeb_php55.list
echo "# wget http://www.dotdeb.org/dotdeb.gpg" >> /etc/apt/sources.list.d/dotdeb_php55.list
echo "# apt-key add dotdeb.gpg" >> /etc/apt/sources.list.d/dotdeb_php55.list
echo "" >> /etc/apt/sources.list.d/dotdeb_php55.list
echo "deb http://packages.dotdeb.org <debian_version>-php55 all" >> /etc/apt/sources.list.d/dotdeb_php55.list
echo "deb-src http://packages.dotdeb.org <debian_version>-php55 all" >> /etc/apt/sources.list.d/dotdeb_php55.list
sed -i "s/<debian_version>/$DEBIAN_VERSION/g;"  /etc/apt/sources.list.d/dotdeb_php55.list
wget http://www.dotdeb.org/dotdeb.gpg
apt-key add dotdeb.gpg
rm -f dotdeb.gpg

#### nginx 1.6
echo "# nginx 1.6" > /etc/apt/sources.list.d/dotdeb.list
echo "" >> /etc/apt/sources.list.d/dotdeb.list
echo "# wget http://www.dotdeb.org/dotdeb.gpg" >> /etc/apt/sources.list.d/dotdeb.list
echo "# apt-key add dotdeb.gpg" >> /etc/apt/sources.list.d/dotdeb.list
echo "" >> /etc/apt/sources.list.d/dotdeb.list
echo "deb http://packages.dotdeb.org/ <debian_version> all" >> /etc/apt/sources.list.d/dotdeb.list
echo "deb-src http://packages.dotdeb.org/ <debian_version> all" >> /etc/apt/sources.list.d/dotdeb.list
sed -i "s/<debian_version>/$DEBIAN_VERSION/g;"  /etc/apt/sources.list.d/dotdeb.list
wget http://nginx.org/keys/nginx_signing.key
apt-key add nginx_signing.key
rm -f nginx_signing.key

#/bin/bash /etc/MySB/bin/MySB_UpgradeSystem
#source /etc/MySB/bin/MySB_UpgradeSystem
ScriptInvoke 'source' '/etc/MySB/bin/MySB_UpgradeSystem'
	
# -----------------------------------------
source /etc/MySB/inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################