#!/bin/bash
# ----------------------------------
source $(dirname $0)/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### Install packages
PackagesManage install "sqlite3"

#### Create databases
if CheckCommand 0 sqlite3; then
	if [ -f $Wolf_DB ] || [ -s $Wolf_DB ]; then
		sqlite3 -cmd '.timeout 150000' $Wolf_DB "DELETE FROM secure_token WHERE 1"
		sqlite3 -cmd '.timeout 150000' $Wolf_DB "UPDATE user SET name = '', email = '', username = '', password = '', salt = '', last_login = '', last_failure = '', last_failure = '', created_on = '', updated_on = '' WHERE id = '2';"
	fi
fi

if [ "$1" == "UPGRADE" ] && [ -s $MySB_DB ] && CheckCommand 0 sqlite3; then
	#### Add column 'forwarder' to 'dnscrypt_resolvers' table
	sqlite3 -cmd '.timeout 150000' -echo $MySB_DB < $MySB_InstallDir/upgrade/dnscrypt_resolvers_v3.0.sql
	#### Add column 'method' to 'renting' table
	sqlite3 -cmd '.timeout 150000' -echo $MySB_DB < $MySB_InstallDir/upgrade/renting_v3.0.sql
	#### Update repositories
	sqlite3 -cmd '.timeout 150000' -echo $MySB_DB "DELETE FROM repositories WHERE 1;"
	sqlite3 -cmd '.timeout 150000' -echo $MySB_DB < $MySB_InstallDir/upgrade/repositories_v3.0.sql
	#### Add column 'dnscrypt' to 'system' table
	sqlite3 -cmd '.timeout 150000' -echo $MySB_DB < $MySB_InstallDir/upgrade/system_v3.0.sql
	#### Add column 'language' to 'users' table
	sqlite3 -cmd '.timeout 150000' -echo $MySB_DB < $MySB_InstallDir/upgrade/users_v3.0.sql
	#### Add column 'last_update' to 'users_addresses' table
	sqlite3 -cmd '.timeout 150000' -echo $MySB_DB < $MySB_InstallDir/upgrade/users_addresses_v3.0.sql
	#### Add column 'pgl_list_name' to 'blocklists' table
	sqlite3 -cmd '.timeout 150000' -echo $MySB_DB < $MySB_InstallDir/upgrade/blocklists_v3.0.sql
	#### Add new services
	sqlite3 -cmd '.timeout 150000' -echo $MySB_DB "INSERT INTO services (serv_name,to_install,is_installed) VALUES (\"ownCloud\",\"0\",\"0\");"
	#### Update language for all users
	ListingUsers
	if [ ! -z "$UsersList" ]; then
		for FnUser in $UsersList; do
			sqlite3 -cmd '.timeout 150000' -echo $MySB_DB "UPDATE users SET language = '$EnvLang' WHERE users_ident = '$FnUser';"
		done
	fi
fi

# -----------------------------------------
source $(dirname $0)/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################