#!/bin/bash
# ----------------------------------
source $(dirname $0)/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### Install packages
PackagesManage install "sqlite3"

#### Create databases
if CheckCommand 0 sqlite3; then
	if [ ! -f $MySB_DB ] || [ ! -s $MySB_DB ]; then sqlite3 -cmd '.timeout 150000' -echo $MySB_DB < $MySB_InstallDir/templates/MySB_2015-04-25.dump.sql; fi
	if [ -f $Wolf_DB ] || [ -s $Wolf_DB ]; then
		sqlite3 -cmd '.timeout 150000' $Wolf_DB "DELETE FROM secure_token WHERE 1"
		sqlite3 -cmd '.timeout 150000' $Wolf_DB "UPDATE user SET name = '', email = '', username = '', password = '', salt = '', last_login = '', last_failure = '', last_failure = '', created_on = '', updated_on = '' WHERE id = '2';"	
	fi
fi

if [ "$1" == "UPGRADE" ] && [ -s $MySB_DB ] && CheckCommand 0 sqlite3; then
	#### Update Repositories
	# ruTorrent Plugin tAdd-Labels
	sqlite3 -cmd '.timeout 150000' $MySB_DB "UPDATE repositories SET version = '1.1', file = 'tadd-labels_1.1.tar.gz', old_file = 'lbll-suite_0.8.1.tar.gz', url = 'http://rutorrent-tadd-labels.googlecode.com/files/tadd-labels_1.1.tar.gz' WHERE name = 'ruTorrent Plugin tAdd-Labels';"
	# NodeJS
	sqlite3 -cmd '.timeout 150000' $MySB_DB "UPDATE repositories SET version = '0.12.2', file = 'node-v0.12.2.tar.gz', old_file = 'node_v0.10.35.tar.gz', url = 'http://nodejs.org/dist/v0.12.2/node-v0.12.2.tar.gz' WHERE name = 'NodeJS';"
fi

# -----------------------------------------
source $(dirname $0)/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################