#!/bin/bash
# ----------------------------------
source $(dirname $0)/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### Install packages
PackagesToInstall="ssh openssh-server"

if ! CheckCommand 0 sshpass; then
	PackagesToInstall="$PackagesToInstall sshpass"
fi
if [ ! -z "$PackagesToInstall" ]; then
	PackagesManage install "$PackagesToInstall" "backports"
fi

cp -v $MySB_InstallDir/templates/etc.ssh.sshd_config.tmpl /etc/ssh/sshd_config
perl -pi -e "s/<port_ssh>/$Port_SSH/g" /etc/ssh/sshd_config
if [ -f /etc/ssh/sshd_config.orig ]; then
	rm -vf /etc/ssh/sshd_config.orig
fi

if [ "`cat /etc/group | grep sshdusers`" == "" ]; then
	groupadd sshdusers
fi
if [ "`cat /etc/group | grep MySB_users`" == "" ]; then
	groupadd MySB_users
fi
if [ "`cat /etc/group | grep sshdusers | grep root`" == "" ]; then
	usermod -a -G sshdusers root
fi
if [ ! -d /usr/share/terminfo/l/ ]; then
	mkdir -pv /usr/share/terminfo/l/
fi
cp /lib/terminfo/l/linux /usr/share/terminfo/l/

if [ ! -d /home/MySB_share ]; then
	mkdir -v /home/MySB_share
fi

#### /etc/motd
figlet MySB $MySB_CurrentVersion > /etc/motd
echo >> /etc/motd
cat /etc/motd

chown root:MySB_users /home/MySB_share
chmod 770 /home/MySB_share

#### START services
ManageServices start "ssh"

# -----------------------------------------
source $(dirname $0)/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################