#!/bin/bash 
# ----------------------------------
source /etc/MySB/inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___        
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_       
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_      
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__     
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_    
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_   
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_  
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__ 
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### install
PackagesManage install "ssh openssh-server"

perl -pi -e "s/^Port 22/Port $NEWSSHPORT/g" /etc/ssh/sshd_config
perl -pi -e "s/^#Protocol 2/Protocol 2/g" /etc/ssh/sshd_config
perl -pi -e "s/^X11Forwarding yes/X11Forwarding no/g" /etc/ssh/sshd_config
perl -pi -e "s/Subsystem sftp \/usr\/lib\/openssh\/sftp-server/Subsystem sftp internal-sftp -l ERROR/g" /etc/ssh/sshd_config

if [ "`cat /etc/ssh/sshd_config | grep 'DebianBanner'`" == "" ];then
	awk '{ print } /UsePAM yes/ { print "DebianBanner no" }' /etc/ssh/sshd_config > /etc/MySB/files/sshd_config
	mv /etc/MySB/files/sshd_config /etc/ssh/sshd_config
fi

if [ "`cat /etc/ssh/sshd_config | grep 'AllowGroups sshdusers MySB_users'`" == "" ];then
	echo "" >> /etc/ssh/sshd_config
	echo "AllowGroups sshdusers MySB_users" >> /etc/ssh/sshd_config
fi
if [ "`cat /etc/ssh/sshd_config | grep 'Match Group MySB_users'`" == "" ];then
	echo "" >> /etc/ssh/sshd_config
	echo "Match Group MySB_users" >> /etc/ssh/sshd_config
	echo "        ChrootDirectory %h" >> /etc/ssh/sshd_config
	echo "        ForceCommand internal-sftp" >> /etc/ssh/sshd_config	
	echo "        AllowTcpForwarding no" >> /etc/ssh/sshd_config
	echo "        X11Forwarding no" >> /etc/ssh/sshd_config
else
	if [ "`cat /etc/ssh/sshd_config | grep 'ChrootDirectory /home/%u'`" != "" ];then
		perl -pi -e "s/ChrootDirectory \/home\/%u/ChrootDirectory %u/g" /etc/ssh/sshd_config
	fi
	if [ "`cat /etc/ssh/sshd_config | grep 'AllowTcpForwarding no'`" == "" ];then
		awk '{ print } /ForceCommand internal-sftp/ { print "        AllowTcpForwarding no" }' /etc/ssh/sshd_config > /etc/MySB/files/sshd_config
		mv /etc/MySB/files/sshd_config /etc/ssh/sshd_config
	fi
	if [ "`cat /etc/ssh/sshd_config | grep 'X11Forwarding no'`" == "" ];then
		awk '{ print } /ForceCommand internal-sftp/ { print "        X11Forwarding no" }' /etc/ssh/sshd_config > /etc/MySB/files/sshd_config
		mv /etc/MySB/files/sshd_config /etc/ssh/sshd_config
	fi	
fi

if [ "`cat /etc/group | grep sshdusers`" == "" ];then
	groupadd sshdusers
fi
if [ "`cat /etc/group | grep MySB_users`" == "" ];then
	groupadd MySB_users
fi
if [ "`cat /etc/group | grep sshdusers | grep root`" == "" ]; then
	usermod -a -G sshdusers root
fi
if [ ! -d /usr/share/terminfo/l/ ];then
	mkdir -p /usr/share/terminfo/l/
fi
cp /lib/terminfo/l/linux /usr/share/terminfo/l/

if [ ! -d /home/MySB_share ];then
	mkdir /home/MySB_share
fi

chown root:MySB_users /home/MySB_share
chmod 776 /home/MySB_share

# -----------------------------------------
source /etc/MySB/inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################