#!/bin/bash
# ----------------------------------
# shellcheck source=inc/includes_before
source "$(dirname "$0")"/../inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#	_\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#	 _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#	  _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#	   _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#		_\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#		 _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#		  _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### Shellcheck
gfnGetRepoValues 'Shellcheck'
if [ "$gsVersionInstalled" != "$gsVersionLatest" ]; then
    [ -f "${MySB_Files}/${gsRepoFile}" ] && mv -v "${MySB_Files}/${gsRepoFile}" "${MySB_Files}/${gsRepoFile}.tmp"
    gfnRepoManageByType
    tar --xz -xvf "${MySB_Files}/${gsRepoFile}" -C /tmp/
    mv -v /tmp/shellcheck-stable/shellcheck /usr/bin/shellcheck
    chmod -v +x /usr/bin/shellcheck
    /usr/bin/shellcheck --version
    rm -rfv /tmp/shellcheck-stable
    [ -f "${MySB_Files}/${gsRepoFile}" ] && rm -fv "${MySB_Files}/${gsRepoFile}.tmp"
fi

#### GeoIP update
gfnGetRepoValues 'GeoIPupdate' && gfnRepoManageByType
if [ "$gsVersionInstalled" != "$gsVersionLatest" ]; then
    # Change architecture if needed
    case $(getconf LONG_BIT) in
        32) gsRepoURL="${gsRepoURL//amd64/386}" ;;
    esac

    # Download DEB file
    [ -f "${gsRepoDir}/${gsRepoFile}" ] && mv -v "${gsRepoDir}/${gsRepoFile}" "${gsRepoDir}/${gsRepoFile}.tmp"
    gfnRepoManageByType
    [ -f "${gsRepoDir}/${gsRepoFile}" ] && rm -fv "${gsRepoDir}/${gsRepoFile}.tmp"

    if [ -f "${gsRepoDir}/${gsRepoFile}" ]; then
        dpkg -i "${gsRepoDir}/${gsRepoFile}"
    fi

    install -v -o root -g root -m 0644 $MySB_InstallDir/templates/other/etc.geoip.conf.tmpl /etc/GeoIP.conf

    # Disable the upgrade job
    cmdMySQL 'MySB_db' "UPDATE repositories SET upgrade='0' WHERE name='GeoIPupdate';" -v
fi

#### Composer
# gfnGetRepoValues 'Composer'
# gfnRepoManageByType
# if [ "$gsVersionInstalled" != "$gsVersionLatest" ]; then
#     gfnRepoManageByType
#     chmod -v +x ${gsRepoDir}
#     ${gsRepoDir} --version | grep 'Composer version'
# fi
# composer self-update

#### NodeJS
gfnGetRepoValues 'NodeJS' && gfnRepoManageByType
if [ $gnRepoUpgrade -eq 1 ] || [ "$gsSwitch" == "INSTALL" ]; then
    cd ${gsRepoDir} || exit
    if [ -d out/ ]; then
        make clean
    fi
    ./configure
    make -j$gsProcessors
    make install
    /sbin/ldconfig
    # Disable the upgrade job
    cmdMySQL 'MySB_db' "UPDATE repositories SET upgrade='0' WHERE name='NodeJS';" -v
fi

#### Python
echo
echo "########## Python"
# Update certificates for python
update-ca-certificates --fresh &>/dev/null
# Install PyOpenSSL for Python
pip install PyOpenSSL
pip3 install PyOpenSSL

#### Bower
echo
echo "########## Bower"
npm install -g npm-check-updates
npm install -g bower
bower update --allow-root

# -----------------------------------------
# shellcheck source=inc/includes_after
source "$(dirname "$0")"/../inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################
