#!/bin/bash 
# ----------------------------------
source /etc/MySB/inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### Color Bash Prompt for ROOT
if [ "`cat /root/.bashrc | grep 'PS1=' | sed '/#/d'`" == "" ]; then
	echo "PS1='\[\e[0;31m\]\u\[\e[m\] \[\e[1;34m\]\w\[\e[m\] \[\e[0;31m\]\$ \[\e[m\]\[\e[0;37m\]'" | tee -a /root/.bashrc &> /dev/null
fi

#### Coloration syntaxic for vim
perl -pi -e "s/\"syntax on/syntax on/g" /etc/vim/vimrc

#### Coloration syntaxic for nano
(
cat <<'EOF'
## ini highlighting
syntax "ini" "\.ini(\.old|~)?$"
color brightred "=.*$"
color green "="
color brightblue "-?[0-9\.]+\s*($|;)"
color brightmagenta "ON|OFF|On|Off|on|off\s*($|;)"
color brightcyan "^\s*\[.*\]"
color cyan "^\s*[a-zA-Z0-9_\.]+"
color brightyellow ";.*$"

EOF
) > /usr/share/nano/ini.nanorc

(
cat <<'EOF'
## Generic *.conf file syntax highlighting
syntax "conf" "\.(c(onf|nf|fg))$"
icolor yellow ""(\\.|[^"])*""
icolor brightyellow start="=" end="$"
icolor magenta start="(^|[[:space:]])[0-9a-z-]" end="="
icolor brightred "(^|[[:space:]])((\[|\()[0-9a-z_!@#$%^&*-]+(\]|\)))"
color green "[[:space:]][0-9.KM]+"
color cyan start="(^|[[:space:]])(#|;).*$" end="$"
color brightblue "(^|[[:space:]])(#|;)"

EOF
) > /usr/share/nano/conf.nanorc

if [ "`cat /etc/nanorc | grep '## Config Files (.ini)'`" == "" ]; then
	echo "
	## Config Files (.ini)
	include \"/usr/share/nano/ini.nanorc\"
	" >> /etc/nanorc
fi

if [ "`cat /etc/nanorc | grep '## Config Files (.conf)'`" == "" ]; then
	echo "
	## Config Files (.conf)
	include \"/usr/share/nano/conf.nanorc\"
	" >> /etc/nanorc
fi

#### Change timezone
if [ ! -z $TimeZone ]; then
	echo "$TimeZone" > /etc/timezone
	sed -i "s/UTC/LOCAL/g;" /etc/adjtime
	dpkg-reconfigure -f noninteractive tzdata
fi

#### Harden kernel using /etc/sysctl.conf
# Protection SYN flood
perl -pi -e "s/^#net.ipv4.tcp_syncookies=1/net.ipv4.tcp_syncookies=1/g" /etc/sysctl.conf
perl -pi -e "s/^#net.ipv4.conf.all.rp_filter=1/net.ipv4.conf.all.rp_filter=1/g" /etc/sysctl.conf
if [ "`cat /etc/sysctl.conf | grep 'net.ipv4.tcp_max_syn_backlog=1024'`" == "" ]; then
	echo "net.ipv4.tcp_max_syn_backlog=1024" >> /etc/sysctl.conf
fi
# Swappiness
MEMORY=`free -m | grep Mem | awk '{ print $2 }'`
SWAP=`free -m | grep Swap | awk '{ print $2 }'`
if [ "$MEMORY" -lt "2048" ] && [ "$SWAP" != "0" ]; then
	echo 80 > /proc/sys/vm/swappiness
	if [ "`cat /etc/sysctl.conf | grep 'vm.swappiness'`" == "" ]; then
		echo "vm.swappiness = 80" >> /etc/sysctl.conf
	fi
fi

#### locale
locale > /etc/MySB/files/locale

#### Hostname
echo "$HostNameFQDN" > /etc/hostname
sh /etc/init.d/hostname.sh

sed -i '/127.0.0.1/d' /etc/hosts
sed -i '/127.0.1.1/d' /etc/hosts
sed -i '/'$SrvIpAddress'/d' /etc/hosts
sed -i '/^$/d' /etc/hosts 
echo "
127.0.0.1       localhost.localdomain localhost
127.0.1.1       $HostNameFQDN $(hostname -s)
$SrvIpAddress       $HostNameFQDN $(hostname -s)
" >> /etc/hosts

#### Resolv.conf
if [ "`cat /etc/resolv.conf | grep '127.0.0.1'`" == "" ]; then
	sed -i '/nameserver/d' /etc/resolv.conf
	(
	cat <<'EOF'
nameserver 208.67.220.220
nameserver 8.8.8.8
nameserver 4.2.2.1
nameserver 208.67.222.222
nameserver 8.8.4.4
nameserver 4.2.2.2
nameserver 4.2.2.3
nameserver 4.2.2.4
nameserver 4.2.2.5
nameserver 4.2.2.6
EOF
	) >> /etc/resolv.conf
fi

#### Sudo
echo "www-data ALL = (root) NOPASSWD: /bin/bash /etc/MySB/scripts/ApplyConfig.bsh*" > /etc/sudoers.d/MySB_nginx

#### CRON for Synchro NTP, LogServer, DynamicAddressResolver, MySB_UpdateGitHubRepo
crontab -l > /tmp/crontab.tmp

# Synchro NTP
sed -i '/ntpdate/d' /tmp/crontab.tmp
echo "0 0,6,12,18 * * * /usr/sbin/ntpdate 0.fr.pool.ntp.org &> /dev/null 2>&1" >> /tmp/crontab.tmp
# Log HTML
sed -i '/LogServer/d' /tmp/crontab.tmp
echo "0 */1 * * * /bin/bash /etc/MySB/scripts/LogServer.bsh CRON &> /dev/null 2>&1" >> /tmp/crontab.tmp
# Dynamic Address Resolver
sed -i '/DynamicAddressResolver/d' /tmp/crontab.tmp
echo "*/5 * * * * /bin/bash /etc/MySB/scripts/DynamicAddressResolver.bsh $$ CRON &> /dev/null 2>&1" >> /tmp/crontab.tmp
# Update Actual Git Repo of MySB
sed -i '/MySB_UpdateGitHubRepo/d' /tmp/crontab.tmp
echo "0 12 */2 * * /bin/bash /etc/MySB/bin/MySB_UpdateGitHubRepo CRON &> /dev/null 2>&1" >> /tmp/crontab.tmp
# Check update for MySB
sed -i '/MySB_UpgradeMe/d' /tmp/crontab.tmp
echo "0 4 */3 * * /bin/bash /etc/MySB/bin/MySB_UpgradeMe CRON &> /dev/null 2>&1" >> /tmp/crontab.tmp
# GeoIP
sed -i '/UpdateGeoIP.bsh/d' /tmp/crontab.tmp
MAXIMUM=58 # DO NOT REMOVE
MINIMUM=1 # DO NOT REMOVE
UPGEOIP=$((MINIMUM+RANDOM*(1+MAXIMUM-MINIMUM)/32767))
echo "$UPGEOIP 2 9 * * /bin/bash /etc/MySB/scripts/UpdateGeoIP.bsh &> /dev/null 2>&1" >> /tmp/crontab.tmp
# rTorrent Blocklists
sed -i '/BlocklistsRTorrent/d' /tmp/crontab.tmp
echo "0 23 * * * /bin/bash /etc/MySB/scripts/BlocklistsRTorrent.bsh CRON &> /dev/null 2>&1" >> /tmp/crontab.tmp

crontab /tmp/crontab.tmp
rm -f /tmp/crontab.tmp

#### Add iptables-restore to interfaces
if [ "`cat /etc/network/interfaces | grep 'post-up iptables-restore < /etc/iptables.up.rules'`" == "" ]; then
	NumLign=$(sed -n "/iface eth0 inet/=" /etc/network/interfaces)
	(( NumLign++ ))
	sed -i "${NumLign}i\        post-up iptables-restore < /etc/iptables.up.rules" /etc/network/interfaces
fi

#### SSH Keygen
if [ ! -d /root/.ssh/ ]; then
	mkdir /root/.ssh/.ssh/ &> /dev/null
fi
if [ ! -f /root/.ssh/id_rsa ]; then
	ssh-keygen -q -t rsa -b 2048 -N "" -f /root/.ssh/id_rsa &> /dev/null
fi

#### AES-NI Crypto Acceleration
if [ -z $IFPVEKERNEL ]; then
	if [ "`cat /proc/cpuinfo | grep aes`" != "" ]; then	
		## load
		modprobe aesni_intel
		
		if [ "`lsmod | grep aes	`" != "" ]; then	
			## make permanent
			if [ "`cat /etc/modules | grep 'aesni_intel'`" == "" ]; then
				echo aesni_intel >> /etc/modules
			fi
			if [ "`cat /etc/environment | grep 'OPENSSL_ia32cap=~0x200000200000000'`" == "" ]; then
				echo "OPENSSL_ia32cap=~0x200000200000000" >> /etc/environment
			fi
		fi
	fi
fi

#### Check new version by cron


#### START services
ManageServices start "cron"

# FirewallAndSecurity Boot Up
cp /etc/MySB/templates/etc.init.FirewallAndSecurity.template /etc/init.d/FirewallAndSecurity
chmod +x /etc/init.d/FirewallAndSecurity
#update-rc.d FirewallAndSecurity defaults 98
update-rc.d FirewallAndSecurity defaults

# -----------------------------------------
source /etc/MySB/inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################