#!/bin/bash 
# ----------------------------------
source /etc/MySB/inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___        
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_       
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_      
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__     
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_    
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_   
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_  
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__ 
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

#### Coloration syntaxic for vim
perl -pi -e "s/\"syntax on/syntax on/g" /etc/vim/vimrc

#### Coloration syntaxic for nano
(
cat <<'EOF'
## ini highlighting
syntax "ini" "\.ini(\.old|~)?$"
color brightred "=.*$"
color green "="
color brightblue "-?[0-9\.]+\s*($|;)"
color brightmagenta "ON|OFF|On|Off|on|off\s*($|;)"
color brightcyan "^\s*\[.*\]"
color cyan "^\s*[a-zA-Z0-9_\.]+"
color brightyellow ";.*$"

EOF
) > /usr/share/nano/ini.nanorc

(
cat <<'EOF'
## Generic *.conf file syntax highlighting
syntax "conf" "\.(c(onf|nf|fg))$"
icolor yellow ""(\\.|[^"])*""
icolor brightyellow start="=" end="$"
icolor magenta start="(^|[[:space:]])[0-9a-z-]" end="="
icolor brightred "(^|[[:space:]])((\[|\()[0-9a-z_!@#$%^&*-]+(\]|\)))"
color green "[[:space:]][0-9.KM]+"
color cyan start="(^|[[:space:]])(#|;).*$" end="$"
color brightblue "(^|[[:space:]])(#|;)"

EOF
) > /usr/share/nano/conf.nanorc

echo "
## Config Files (.ini)
include \"/usr/share/nano/ini.nanorc\"

## Config Files (.conf)
include \"/usr/share/nano/conf.nanorc\"">> /etc/nanorc

#### Change timezone
if [ ! -z $TIMEZONE ]; then
	echo "$TIMEZONE" > /etc/timezone
	sed -i "s/UTC/LOCAL/g;" /etc/adjtime
	dpkg-reconfigure -f noninteractive tzdata
fi

#### locale
locale > /etc/MySB/files/locale

#### Hostname
echo "$HOSTFQDN" > /etc/hostname
sh /etc/init.d/hostname.sh

sed -i '/127.0.0.1/d' /etc/hosts
sed -i '/127.0.1.1/d' /etc/hosts
sed -i '/'$IPADDRESS'/d' /etc/hosts
sed -i '/^$/d' /etc/hosts 
echo "
127.0.0.1       localhost.localdomain localhost
127.0.1.1       $HOSTFQDN $(hostname -s)
$IPADDRESS       $HOSTFQDN $(hostname -s)
" >> /etc/hosts

#### Resolv.conf
echo "nameserver 8.8.4.4" > /etc/resolv.conf
echo "nameserver 8.8.8.8" >> /etc/resolv.conf

#### Synchro NTP, cache, swappiness (if not OpenVZ)
if [ -z $IFPVEKERNEL ]; then
	#### Free cache server
	## To free pagecache
	#sync; echo 1 > /proc/sys/vm/drop_caches
	## To release dentries and inodes
	#sync; echo 2 > /proc/sys/vm/drop_caches
	## To free pagecache, dentries and inodes
	sync; echo 3 > /proc/sys/vm/drop_caches
	## Default
	#sync; echo 0 > /proc/sys/vm/drop_caches
	
	#### cron
	crontab -l > /tmp/crontab.tmp
	sed -i '/drop_caches/d' /tmp/crontab.tmp
	sed -i '/ntpdate/d' /tmp/crontab.tmp
	echo "30 0 * * * sync; echo 3 > /proc/sys/vm/drop_caches &> /dev/null" >> /tmp/crontab.tmp
	echo "0 0,6,12,18 * * * /usr/sbin/ntpdate 0.fr.pool.ntp.org &> /dev/null" >> /tmp/crontab.tmp
	crontab /tmp/crontab.tmp
	rm /tmp/crontab.tmp
fi

MEMORY=`free -m | grep Mem | awk '{ print $2 }'`
SWAP=`free -m | grep Swap | awk '{ print $2 }'`

if [ "$MEMORY" -lt "2048" ] && [ "$SWAP" != "0" ]; then
	echo 80 > /proc/sys/vm/swappiness
	echo "vm.swappiness = 80" >> /etc/sysctl.conf
fi

#### Add iptables-restore to interfaces
awk '{ print } /iface eth0 inet/ { print "        post-up iptables-restore < /etc/iptables.up.rules" }' /etc/network/interfaces > /etc/MySB/files/interfaces
rm -f /etc/network/interfaces
cp /etc/MySB/files/interfaces /etc/network/interfaces

#### LogServer.sh
crontab -l > /tmp/crontab.tmp
sed -i '/LogServer.sh/d' /tmp/crontab.tmp
echo "0 */2 * * * /bin/bash /etc/MySB/scripts/LogServer.sh STDOUT &> /dev/null 2>&1" >> /tmp/crontab.tmp
crontab /tmp/crontab.tmp
rm /tmp/crontab.tmp

#### SSH Keygen
if [ ! -d /root/.ssh/ ]; then
	mkdir /root/.ssh/.ssh/ &> /dev/null
fi
if [ ! -f /root/.ssh/id_rsa ]; then
	ssh-keygen -q -t rsa -b 2048 -N "" -f /root/.ssh/id_rsa &> /dev/null
fi

# AES-NI Crypto Acceleration
if [ "`cat /proc/cpuinfo | grep aes	`" != "" ]; then	
	## load
	modprobe aesni_intel
	
	if [ "`lsmod | grep aes	`" != "" ]; then	
		## make permanent
		echo aesni_intel >> /etc/modules
		echo "OPENSSL_ia32cap=~0x200000200000000" >> /etc/environment
	fi
fi
	
# -----------------------------------------
source /etc/MySB/inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################