#!/bin/bash 
# ----------------------------------
source /etc/MySB/inc/includes_before
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___        
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_       
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_      
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__     
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_    
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_   
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_  
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__ 
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################
#
# Usage:	Webmin <port>
#
##################### FIRST LINE #####################################

if [ "$USAGE" == "ON" ]; then
	if [ -z $WEBMINPORT ]; then
		if [ -z $1 ]; then
			echo -e "${CBLUE}Usage:$CEND	${CYELLOW}Webmin$CEND ${CGREEN}<port>$CEND"
			exit
		else
			WEBMINPORT=$1
		fi
	fi
fi

#if webmin isup, download key
WEBMINDOWN=YES
ping -c1 -w2 www.webmin.com
if [ $? -eq 0 ] ; then
	cd /etc/MySB/files
	wget -t 5 http://www.webmin.com/jcameron-key.asc -O /etc/MySB/files/jcameron-key.asc
	apt-key add /etc/MySB/files/jcameron-key.asc
	rm -f /etc/MySB/files/jcameron-key.asc
	if [ $? -eq 0 ] ; then
		WEBMINDOWN=NO
	fi
fi

if [ "$WEBMINDOWN" == "NO" ] ; then
	#add webmin source
	echo "# Webmin" > /etc/apt/sources.list.d/webmin.list
	echo "" >> /etc/apt/sources.list.d/webmin.list
	echo "# wget -t 5 http://www.webmin.com/jcameron-key.asc" >> /etc/apt/sources.list.d/webmin.list
	echo "# apt-key add jcameron-key.asc" >> /etc/apt/sources.list.d/webmin.list
	echo "" >> /etc/apt/sources.list.d/webmin.list
	echo "deb http://download.webmin.com/download/repository sarge contrib" >> /etc/apt/sources.list.d/webmin.list
fi

if [ "$WEBMINDOWN" == "NO" ]; then
	PackagesManage install "webmin"
	
	ScriptInvoke 'source' '/etc/MySB/install/Certificates' 'CreateServiceCertificate' 'webmin'
	
	cat /etc/MySB/ssl/webmin.cert > /etc/webmin/miniserv.pem
	cat /etc/MySB/ssl/webmin.key >> /etc/webmin/miniserv.pem
	
	perl -pi -e "s/10000/$WEBMINPORT/g" /etc/webmin/miniserv.conf
	perl -pi -e "s/force_init=0/force_init=1/g" /etc/webmin/firewall/config
	
	echo "$WEBMINPORT" > /etc/MySB/infos/port_webmin.info
	echo "YES" > /etc/MySB/infos/install_webmin.info
	
	# Webmin modules
	if [ ! -f /etc/MySB/files/openvpn.wbm ]; then
		wget --no-check-certificate -O /etc/MySB/files/openvpn.wbm $WBM_webmin_openvpn
	fi	
	if [ ! -f /etc/MySB/files/nginx.wbm ]; then
		wget --no-check-certificate -O /etc/MySB/files/nginx.wbm $WBM_webmin_nginx
	fi		
	if [ ! -f /etc/MySB/files/dlna.wbm ]; then
		wget --no-check-certificate -O /etc/MySB/files/dlna.wbm $WBM_webmin_dlna
	fi		
	if [ -f /etc/MySB/files/openvpn.wbm ]; then
		perl /usr/share/webmin/install-module.pl /etc/MySB/files/openvpn.wbm
		rm -f /etc/MySB/files/dlna.wbm
	fi	
	if [ -f /etc/MySB/files/nginx.wbm ]; then
		perl /usr/share/webmin/install-module.pl /etc/MySB/files/nginx.wbm
		rm -f /etc/MySB/files/dlna.wbm
	fi	
	if [ -f /etc/MySB/files/dlna.wbm ]; then
		perl /usr/share/webmin/install-module.pl /etc/MySB/files/dlna.wbm
		rm -f /etc/MySB/files/dlna.wbm
	fi		
fi

# -----------------------------------------
source /etc/MySB/inc/includes_after
# -----------------------------------------
##################### LAST LINE ######################################