#!/bin/bash
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

Header_Install_0="${CRED}############################################################$CEND
${CRED}#$CEND ${CYELLOW}À la fin de l'installation, vous recevrez un e-mail.$CEND
${CRED}#$CEND ${CYELLOW}Il répertorie les informations sur votre compte.$CEND
${CRED}# IMPORTANT:$CEND ${CYELLOW}Rappelez-vous également de vérifier le dossier SPAM de votre compte de messagerie...$CEND
${CRED}############################################################$CEND"
Header_CurrentFile="Fichier actuel:"

Global_NO="NON"
Global_YES="OUI"
Global_Again="Encore:"
Global_Done="${CGREEN}Fait !$CEND"
Global_Failed="${CRED}Echec !$CEND"
Global_SeeYouLater="${CYELLOW}OK, à plus tard ...$CEND"
Global_WantToContinue="Voulez-vous continuer, tapez '$Global_YES' ? "
Global_OwnerAndRights="Changement des propriétaires et des droits pour les fichiers et répertoires"
Global_FinalSecurityRules="Création des règles finaes de sécurité"

Global_Error_StatusSTD="${CRED}On dirait que quelque chose ne va pas, vérifiez le log '$MySB_InstallDir/logs/$ScriptName.*', abandon.$CEND"

##################### LAST LINE ######################################