#!/bin/bash
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################

CreateUser_Usage="Utilisateurs disponibles: "
CreateUser_Username="Nom d'utilisateur à créer: "
CreateUser_Password="Mot de passe pour l'utilisateur"
CreateUser_SFTP="L'utilisateur peut se connecter via sFTP ? "
CreateUser_Email="Adresse e-mail pour cet utilisateur ? "

CreateUser_InsertInfoDB="Ajout des informations de l'utilisateur dans la base de données"
CreateUser_UpdateInfoDB="Mise à jour des informations de l'utilisateur dans la base de données"

##################### LAST LINE ######################################