#!/bin/bash
# ----------------------------------
#  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
#   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
#    _\/\\\//\\\____/\\\//\\\____/\\\__/\\\__\//\\\______\///__\/\\\_______\/\\\_
#     _\/\\\\///\\\/\\\/_\/\\\___\//\\\/\\\____\////\\\_________\/\\\\\\\\\\\\\\__
#      _\/\\\__\///\\\/___\/\\\____\//\\\\\________\////\\\______\/\\\/////////\\\_
#       _\/\\\____\///_____\/\\\_____\//\\\____________\////\\\___\/\\\_______\/\\\_
#        _\/\\\_____________\/\\\__/\\_/\\\______/\\\______\//\\\__\/\\\_______\/\\\_
#         _\/\\\_____________\/\\\_\//\\\\/______\///\\\\\\\\\\\/___\/\\\\\\\\\\\\\/__
#          _\///______________\///___\////__________\///////////_____\/////////////_____
#			By toulousain79 ---> https://github.com/toulousain79/
#
######################################################################
#
#	Copyright (c) 2013 toulousain79 (https://github.com/toulousain79/)
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
##################### FIRST LINE #####################################

Upgrade_Banner="
${CRED}Si vous perdez la connexion lors de l'installation, démarrez une nouvelle session SSH et exécutez la commande suivante:$CEND
${CGREEN}	screen -r MySB_Upgrade$CEND

${CYELLOW}La mise à niveau peut prendre de 30 à 60 minutes environ.
Cela dépendra de la configuration de votre serveur et des services installés.$CEND"

Upgrade_ReadingDatabaseInfos="Lecture des informations de la base de données"
Upgrade_ActivatingProgressPage="Activation de la page \"Mise à jour en cours\""
Upgrade_DisablingProgressPage="Désactivation de la page \"Mise à jour en cours\""
Upgrade_StoppingCronAndRtorrent="Arrêt du service CRON et des sessions rTorrent"
Upgrade_UpdatingClock="Mise à jour de l'horloge"
Upgrade_NothingToDo="${CGREEN}Rien à faire !$CEND"
Upgrade_UpgradeFinished="${CGREEN}Mise à niveau terminée avec succès !$CEND"
Upgrade_RebootNow="Voulez-vous redémarrer votre seedbox maintenant (recommandé) ?"
Upgrade_AllNeededPackages="Installation de tous les paquets requis"
Upgrade_DownloadAll="Téléchargement de tous les fichiers en une fois (GIT, SVN, TAR.GZ, WBM)"

Upgrade_Cleaning="Nettoyage"
Upgrade_RestartServices="Redémarrage des services"

######################################################################

Upgrade_MoveAndDelete="Déplacement et suppression de certains fichiers et répertoires"
Upgrade_UpdateDatabase="Mise à jour de la base de données MySB"
Upgrade_UpdateDebianSources="Mise à jour des sources Debian et mise à niveau du système"

Upgrade_Webmin="Installation et configuration de Webmin"
Upgrade_VSFTPd="Installation et configuration de VSFTPd"
Upgrade_NginX="Installation et configuration de NginX"
Upgrade_NFS="Installation et configuration de NFS"
Upgrade_Samba="Installation et configuration de Samba"
Upgrade_RefreshMe="Actualisation de rTorrent, ruTorrent, Manager, Cakebox et LoadAvg (cela peut prendre un certain temps, merci de patienter)"
Upgrade_DNScrypt="Installation et configuration de DNScrypt-proxy"

##################### LAST LINE ######################################